PROC 1
	;SET_EVENT_PWORLD_QUEUE 201 0
	ADD_SYS_MSG_START
	SET_SYS_MSG_MODE 6 0 0
	ADD_SYS_MSG 紧张，刺激的尖峰时刻即将到来，请各位抓紧时间前往卡丽熙[时间城]处参加，活动开启5分钟后不可进入！
	SVR_MSG_INFO


	SET_EVENT_PWORLD 1 200
ENDPROC

PROC 2 
    ; ADD_SYS_MSG_START
    ; SET_SYS_MSG_MODE 4 0 0	
    ; ADD_SYS_MSG 欢乐嘉年华活动结束了，等待下次吧
    ; SVR_MSG_INFO

ENDPROC


