proc 1
	ADD_SYS_MSG_START 
  	ADD_SYS_MSG 双倍经验时间开始了！
	SET_SYS_MSG_MODE 6 0 0 
	SVR_MSG_INFO

	SET_SVR_STATUS 1052 2 14400 1
;	SET_EVENT_BULLETIN 1 14400 30 双倍经验活动火热进行中！
endproc

PROC 2
	ADD_SYS_MSG_START 
  	ADD_SYS_MSG 双倍经验时间结束了，敬请期待下次活动！
	SET_SYS_MSG_MODE 6 0 0 
	SVR_MSG_INFO
ENDPROC

