/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef VERSION_SVR_CONF_DESC_H
#define VERSION_SVR_CONF_DESC_H


#ifndef TDR_METALIB_VERSION_SVR_VERSION 
#define TDR_METALIB_VERSION_SVR_VERSION 	2555 /*version of metalib*/
#endif

#ifndef TDR_METALIB_VERSION_SVR_HASH 
#define TDR_METALIB_VERSION_SVR_HASH 	"69abb8e607155f549e28659cc7a9bdfb" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */



#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagversion_svrconf;
typedef struct tagversion_svrconf                  	VERSION_SVRCONF;
typedef struct tagversion_svrconf                  	*LPVERSION_SVRCONF;

struct tagversion_svrrun_status;
typedef struct tagversion_svrrun_status            	VERSION_SVRRUN_STATUS;
typedef struct tagversion_svrrun_status            	*LPVERSION_SVRRUN_STATUS;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagversion_svrconf
{
    unsigned int Count;                          
    UPDATAPACK UpPack[MAX_UP_VERSION_NUM];     
    unsigned int JumpCount;                      
    UPJUMPPACK JumpPack[MAX_UP_JUMP_NUM];      
    char XmlPath[256];                   
};

struct tagversion_svrrun_status
{
    int RecvCltMsg;                     
    int SendCltMsgFail;                 
    int BadCltMsg;                      
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* VERSION_SVR_CONF_DESC_H */
