//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WorldEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_MAPVIEWINFO                 103
#define IDR_MAINFRAME                   128
#define IDR_WorldEditorTYPE             129
#define IDD_RES_BROWER                  130
#define IDD_HEIGHTMAP                   131
#define IDD_TERRAIN_TEXTURE             132
#define IDD_GENERAL_WATER               133
#define IDD_REFLECT_WATER               134
#define IDD_WATER_EDIT                  135
#define IDD_MODEL_EDIT                  136
#define IDD_CREATE_MAP                  137
#define IDD_LIGHT_EDIT                  138
#define IDD_AREA_EDIT                   139
#define IDD_ENVIRONMENT_EDIT            140
#define IDD_NPC_EDIT                    141
#define IDD_DIALOG_TILETEX_LAYERINFO    142
#define IDD_DIALOG_MODELINFO            143
#define IDD_DIALOG_PROCEDIT             146
#define IDD_FIND                        148
#define IDD_BEACHNAMEDLG                149
#define IDC_EDIT_CAMERA_X               1000
#define IDC_RADARVIEW                   1001
#define IDC_RES_PREVIEW                 1002
#define IDC_COMBO_MODELINFO_ANIM        1002
#define IDC_RES_TREE                    1003
#define IDC_CHECK_BIG_VISIBLE           1003
#define IDC_CHECK_RENDER_LIGHTS         1003
#define IDC_CHECK_DISPLAYAREA           1003
#define IDC_CHECK_DISPLAY_NPC           1003
#define IDC_COMBO_MODELINFO_TYPE        1003
#define IDC_CHECK1                      1003
#define IDC_CHECK_LIGHT_SHADOW          1003
#define IDC_CHECK_EDITBEACH             1003
#define IDC_CHECK_SMALL_VISIBLE         1004
#define IDC_CHECK_RENDER_LIGHTMODELS    1004
#define IDC_CHECK_EDIT_NPC              1004
#define IDC_EDIT_HMAP_BRUSHSIZE         1005
#define IDC_CHECK_DETAIL_VISIBLE        1005
#define IDC_EDIT_TEXBRUSH_SIZE          1005
#define IDC_EDIT_TEXREPEAT_LAYER1       1005
#define IDC_EDIT_MODELINFO_PATH         1005
#define IDC_EDIT_HMAP_BRUSHSTRENGTH     1006
#define IDC_CHECK_PLANT_VISIBLE         1006
#define IDC_EDIT_TEXBRUSH_STRENGTH      1006
#define IDC_EDIT_TEXREPEAT_LAYER2       1006
#define IDC_CHECK_BIG_LOCK              1007
#define IDC_EDIT_TEXREPEAT_LAYER3       1007
#define IDC_CHECK_SMALL_LOCK            1008
#define IDC_EDIT_MAP_GRIDSIZEX          1008
#define IDC_EDIT_TEXREPEAT_LAYER4       1008
#define IDC_CHECK_DETAIL_LOCK           1009
#define IDC_EDIT_MAP_SIZEZ              1009
#define IDC_EDIT_EFFECT_RANGE           1009
#define IDC_EDIT_TEXNAME_LAYER1         1009
#define IDC_CHECK_PLANT_LOCK            1010
#define IDC_EDIT_MAP_GRIDSIZEZ          1010
#define IDC_BUTTON_LOADLIGHTS           1010
#define IDC_BUTTON_ADDAREA              1010
#define IDC_EDIT_TEXNAME_LAYER2         1010
#define IDC_RADIO_BIG_MODEL             1011
#define IDC_EDIT_MAP_HEIGHT             1011
#define IDC_BUTTON_SAVEAREA             1011
#define IDC_EDIT_SOUND_VOLUME           1011
#define IDC_EDIT_TEXNAME_LAYER3         1011
#define IDC_RADIO_SMALL_MODEL           1012
#define IDC_EDIT_MAP_MAXHEIGHT          1012
#define IDC_BUTTON_LOADAREA             1012
#define IDC_EDIT_EFFECT_RESPATH         1012
#define IDC_EDIT_TEXNAME_LAYER4         1012
#define IDC_RADIO_DETAIL_MODEL          1013
#define IDC_EDIT_MAP_TEXREPEAT          1013
#define IDC_BUTTON_DELAREA              1013
#define IDC_RADIO_PLANT_MODEL           1014
#define IDC_EDIT_MAP_COORDX             1014
#define IDC_BUTTON_ADDAREA_PROC         1014
#define IDC_CHECK_CLIFF_DELTERRAIN      1015
#define IDC_EDIT_MAP_COORDZ             1015
#define IDC_BUTTON_SAVEPROC_TODB        1015
#define IDC_CHECK_MODEL_SNAPGRID        1016
#define IDC_BUTTON_PASTEAREA            1016
#define IDC_BUTTON_HMAP_SMOOTH          1017
#define IDC_CHECK_MODEL_SNAPWATER       1017
#define IDC_BUTTON_DEFAULT_TEXTURE      1017
#define IDC_BUTTON_SELECTAREA           1017
#define IDC_SLIDER_MODELAREA_MINSCALE   1018
#define IDC_BUTTON_COPYAREA             1018
#define IDC_BUTTON_TEXSHAPE             1019
#define IDC_CHECK_CLIFF_AUTOLINK        1020
#define IDC_EDIT_DEFAULT_TEXTURE        1020
#define IDC_EDIT_MAPNAME                1021
#define IDC_CHECK_LIGHT_LOCKHEIGHT      1021
#define IDC_CHECK_GLOBAL_LOCK           1021
#define IDC_EDIT_MAP_SIZEX              1022
#define IDC_EDIT_MAP_ID                 1023
#define IDC_COMBO_HMAP_EDITCURVE        1024
#define IDC_BUTTON_DEL_NPC              1024
#define IDC_CHECK_GRASS_VISIBLE         1024
#define IDC_COMBO_HMAP_TRIMMODE         1025
#define IDC_EDIT_PLANT_SCALE            1025
#define IDC_BTN_LOADAMBIENT             1025
#define IDC_BUTTON_SAVENPC_TODB         1025
#define IDC_CHECK_LINKMESH_LOCK         1025
#define IDC_CHECK_LINKMESH_VISIBLE      1025
#define IDC_COMBO_HMAP_LIFTMODE         1026
#define IDC_RADIO_LINKMESH_MODEL        1026
#define IDC_BUTTON_COPYJINGYING_TODB    1026
#define IDC_SPIN_HMAP_BRUSHSIZE         1027
#define IDC_BUTTON_LOADNPC_FROMDB       1027
#define IDC_SPIN_HMAP_BRUSHSTRENGTH     1028
#define IDC_COMBO_TEX_LAYER             1028
#define IDC_SLIDER_MODELAREA_SIZE       1029
#define IDC_SPIN_TEXBRUSH_SIZE          1029
#define IDC_LIST_AREA                   1029
#define IDC_LIST_NPC_RES                1029
#define IDC_SLIDER_MODELAREA_NUM        1030
#define IDC_SPIN_TEXBRUSH_STRENGTH      1030
#define IDC_LIST_NPC_INST               1030
#define IDC_SPIN_PLANT_SCALE            1031
#define IDC_SLIDER_MODELAREA_MAXSCALE   1032
#define IDC_COMBO_TEX_PAINTSHAPE        1032
#define IDC_SLIDER_HEIGHTFOG_FAR        1032
#define IDC_EDIT_MODELAREA_SIZE         1033
#define IDC_LIST_LIGHTS                 1033
#define IDC_SLIDER_HEIGHTFOG_NEAR       1033
#define IDC_EDIT_MODELAREA_NUM          1034
#define IDC_SPIN_DIR_HORIZON            1034
#define IDC_EDIT_MODELAREA_MINSCALE     1035
#define IDC_SPIN_DIR_VERTICAL           1035
#define IDC_EDIT_MODELAREA_MAXSCALE     1036
#define IDC_BUTTON_SETENVDATA           1036
#define IDC_BUTTON_MODELAREA_EDIT       1037
#define IDC_CHECK_DRAW_RADARMAP         1037
#define IDC_BUTTON1                     1038
#define IDC_BUTTON_PREVIEW_BGCOLOR      1038
#define IDC_BUTTON_WATER_ENVMAP         1038
#define IDC_BUTTON_GET_PREVIEWDIR       1038
#define IDC_FIND                        1038
#define IDC_BUTTON_LOADPROC_FROMDB      1038
#define IDC_BEACHNAMEOK                 1038
#define IDC_BUTTON_EFFECT_COLOR         1039
#define IDC_SPIN_TEXREPEAT_LAYER2       1041
#define IDC_SPIN_TEXREPEAT_LAYER1       1042
#define IDC_SPIN_TEXREPEAT_LAYER3       1043
#define IDC_SPIN_TEXREPEAT_LAYER4       1044
#define IDC_RADIO_LAYER1                1044
#define IDC_SPIN_MODELINFO_PITCH        1045
#define IDC_SLIDER_TEXBRUSH_SIZE        1045
#define IDC_SPIN_MODELINFO_YAW          1046
#define IDC_RADIO_LAYER2                1046
#define IDC_SPIN_MODELINFO_ROLL         1047
#define IDC_RADIO_LAYER3                1047
#define IDC_SPIN_MODELINFO_SCALE        1048
#define IDC_RADIO_LAYER4                1048
#define IDC_RADIO_LAYER5                1049
#define IDC_RADIO_LAYER6                1050
#define IDC_RADIO_LAYER7                1051
#define IDC_RADIO_LAYER8                1052
#define IDC_RADIO_LAYER9                1053
#define IDC_RADIO_PAINTSHAPE_CIRCLE     1054
#define IDC_SLIDER_HMAP_BRUSHSIZE       1055
#define IDC_SLIDER_HMAP_BRUSHSTRENGTH   1056
#define IDC_RADIO_HMAPCURVE_SOFT        1057
#define IDC_SLIDER_TEXBRUSH_STRENGTH    1058
#define IDC_RADIO_HMAPCURVE_SMOOTH      1058
#define IDC_SLIDER_DIR_HORIZON          1058
#define IDC_SLIDER_PLANT_SCALE          1059
#define IDC_RADIO_HMAPCURVE_SLOPE       1059
#define IDC_SLIDER_DIR_VERTICAL         1059
#define IDC_RADIO_RES_ALL               1059
#define IDC_RADIO_PAINTSHAPE_RECT       1060
#define IDC_RADIO_HMAPCURVE_HARD        1060
#define IDC_RADIO_RES_MODEL             1060
#define IDC_EDIT_SKYMODEL               1060
#define IDC_RADIO_PAINTSHAPE_RANDOMCIRCLE 1061
#define IDC_RADIO_HMAPCURVE_FLAT        1061
#define IDC_RADIO_RES_TILETEX           1061
#define IDC_EDIT_SKYMODEL2              1061
#define IDC_EDIT_BGMUSIC                1061
#define IDC_BTN_REFLECTWATERCOLOR1      1061
#define IDC_RADIO_PAINTSHAPE_RANDOMRECT 1062
#define IDC_RADIO_HMAPCURVE_DITCH       1062
#define IDC_EDIT_REFLECTWATERALPHA1     1062
#define IDC_EDIT_CAMERAEFFECT           1062
#define IDC_RADIO_HMAPTRIM_NONE         1063
#define IDC_EDIT_REFLECTWATERDEPTH1     1063
#define IDC_EDIT_BGSOUND                1063
#define IDC_RADIO_HMAPTRIM_TRIM         1064
#define IDC_BTN_REFLECTWATERCOLOR2      1064
#define IDC_RADIO_HMAPTRIM_RECOVER      1065
#define IDC_EDIT_HEIGHTFOG_NEAR         1065
#define IDC_RADIO_HMAP_LIFT             1066
#define IDC_EDIT_HEIGHTFOG_FAR          1066
#define IDC_EDIT_WATER_ENVMAP           1066
#define IDC_RADIO_HMAP_LOWER            1067
#define IDC_EDIT_DISTFOG_NEAR           1067
#define IDC_SLIDER_WATER_SPEED          1067
#define IDC_EDIT_DISTFOG_FAR            1068
#define IDC_SLIDER_WATER_UVREPEAT       1068
#define IDC_SLIDER_WATER_AMP            1069
#define IDC_SLIDER5                     1070
#define IDC_SLIDER_BLOOM_WIDTH          1070
#define IDC_SLIDER_BLOOM_EXPOSURE       1071
#define IDC_SLIDER_BLOOM_AMP            1072
#define IDC_SLIDER_SHADOWDENSITY        1073
#define IDC_EDIT_LINK_MAPID             1074
#define IDC_COMBO_TOPLIGHT_SHADOW       1075
#define IDC_EDIT_MODELINFO_X            1076
#define IDC_COMBO1                      1076
#define IDC_COMBO_EFFECT_EDITMODE       1076
#define IDC_POINT_MODE                  1076
#define IDC_EDIT_MODELINFO_Y            1077
#define IDC_EDIT_EFFECT_X               1077
#define IDC_EDIT_MODELINFO_Z            1078
#define IDC_EDIT_LINK_POSX              1078
#define IDC_EDIT_EFFECT_Y               1078
#define IDC_EDIT_MODELINFO_PITCH        1079
#define IDC_EDIT_LINK_POSY              1079
#define IDC_EDIT_EFFECT_Z               1079
#define IDC_EDIT_MODELINFO_YAW          1080
#define IDC_EDIT_LINK_DIR               1080
#define IDC_EDIT_EFFECT_NAME            1080
#define IDC_EDIT_MODELINFO_ROLL         1081
#define IDC_EDIT_BACK_POSX              1081
#define IDC_BUTTON_EFFECT_PATH          1081
#define IDC_EDIT_MODELINFO_SCALE        1082
#define IDC_EDIT_BACK_POSY              1082
#define IDC_EDIT_BACK_DIR               1083
#define IDC_CHECK_REFLECTED             1083
#define IDC_BUTTON_LOAD_NPC             1084
#define IDC_BUTTON_DELETE_NPC           1084
#define IDC_BUTTON_DEL_ALLNPC           1084
#define IDC_CHECK_REFRACTED             1084
#define IDC_EDIT_MUSICVOLUME            1084
#define IDC_EDIT_LINK_CAMERADIR         1084
#define IDC_EDIT_BGSOUNDVOL             1085
#define IDC_EDIT_PREVIEW_ACTORDIR       1085
#define IDC_EDIT_NPCID_FILTER           1085
#define IDC_CHECK_REFRACTED2            1085
#define IDC_CHECK_TRANSABLE             1085
#define IDC_EDIT_PREVIEW_CAMERADIR      1086
#define IDC_EDIT_NPCID_FILTER2          1086
#define IDC_EDIT_NPCNAME_FILTER         1086
#define IDC_EDIT_WATERALPHA1            1087
#define IDC_EDIT_LINK_SCRIPT            1087
#define IDC_EDIT_REFLECTWATERALPHA3     1088
#define IDC_EDIT_REFLECTWATERALPHA2     1088
#define IDC_EDIT_PREVIEW_ACTORY         1088
#define IDC_EDIT_PREVIEW_ACTORX         1089
#define IDC_CUSTOM1                     1089
#define IDC_CURVEWND                    1090
#define IDC_RADIO_HMAPCURVE_CURVE       1091
#define IDC_SLIDER_GRASS                1092
#define IDC_RESNAME                     1093
#define IDC_MODELLIST                   1094
#define IDC_PASTE                       1095
#define IDC_BTNAME                      1097
#define IDC_EDIT_WATERDEPTH1            1098
#define IDC_COMBO_WATERTYPE             1099
#define IDC_EDIT_REFLECTWATERDEPTH2     1099
#define IDC_BTN_WATERCOLOR1             1100
#define IDC_BTN_WATERCOLOR2             1101
#define IDC_EDIT_WATERALPHA2            1102
#define IDC_EDIT_WATERDEPTH2            1103
#define IDC_COMBO_WATERTEXTURE          1104
#define IDC_EDIT_WATERHEIGHT            1105
#define IDC_SLIDER_WATERTEXREPEAT       1106
#define IDC_BEACHTEXTURE_USE            1106
#define IDC_BTN_DIFFUSE_COLOR           1107
#define IDC_BUVSPEED                    1107
#define IDC_BTN_SPECULAR_COLOR          1108
#define IDC_BT_DELETE                   1108
#define IDC_BTN_AMBIENT_COLOR           1109
#define IDC_BEACHLIST                   1109
#define IDC_BTN_DISTFOG_COLOR           1110
#define IDC_BEACHWIDTH                  1110
#define IDC_CHECK_DISTFOG_ENABLE        1111
#define IDC_BEACHDELETE                 1111
#define IDC_SLIDER_DISTFOG_NEAR         1112
#define IDC_BEACH_COPY                  1112
#define IDC_SLIDER_DISTFOG_FAR          1113
#define IDC_BEACHHEIGHT                 1113
#define IDC_CHECK_HEIGHTFOG_ENABLE      1114
#define IDC_BEACH_ADD                   1114
#define IDC_BTN_HEIGHTFOG_COLOR         1115
#define IDC_UREPEAT                     1115
#define IDC_EDIT_DIR_HORIZON            1116
#define IDC_VREPEAT                     1116
#define IDC_BTN_TOPLIGHT_COLOR          1117
#define IDC_BEACHMASK                   1117
#define IDC_EDIT_DIR_VERTICAL           1118
#define IDC_BEACHMASK_USE               1118
#define IDC_BM_DELETE                   1119
#define IDC_BTN_SKYMODEL                1120
#define IDC_BUVRANGE                    1120
#define IDC_BTN_BGMUSIC                 1121
#define IDC_RENAME                      1121
#define IDC_BTN_SAVE_AMBIENT            1122
#define IDC_EDIT_BEACHNAME              1122
#define IDC_BTN_CAMERAEFFECT            1123
#define IDC_BTN_BGSOUND                 1124
#define IDC_BTN_SKYMODEL_CLEAR          1125
#define IDC_EDIT_TEXNAME_SHADOW         1125
#define IDC_BTN_BGMUSIC_CLEAR           1126
#define IDC_SOUNDTIME0                  1126
#define IDC_BTN_BGSOUND_CLEAR           1127
#define IDC_SOUNDTIME1                  1127
#define IDC_BTN_CAMERAEFFECT_CLEAR      1128
#define IDC_FULLRANGE                   1129
#define IDC_SOUNDISLOOP                 1130
#define IDC_RADIO_LAYER90               1131
#define IDC_RADIO_LAYER10               1131
#define IDC_IMPORT_WALKBMP              1132
#define IDC_CHECK_GLOBALMODEL_VISIBLE   1200
#define IDC_CHECK_GLOBALMODEL_LOCK      1201
#define IDC_RADIO_GLOBAL_MODEL          1202
#define IDC_SLIDER1                     11043
#define IDC_SLIDER2                     11044
#define IDC_SLIDER3                     11045
#define IDC_SLIDER4                     11046
#define ID_32771                        32771
#define ID_RESBROWER                    32772
#define ID_VIEW_RESBROWER               32773
#define ID_32774                        32774
#define ID_VIEW_EDITBAR                 32775
#define ID_Menu                         32776
#define ID_32779                        32779
#define ID_Menu32780                    32780
#define ID_32781                        32781
#define ID_32782                        32782
#define ID_EXP_MASK_FILE                32783
#define ID_EXP_AREA_FILE                32784
#define ID_EXPORT_MASK_FILE             32785
#define ID_EXPORT_AREA_FILE             32786
#define ID_32787                        32787
#define ID_CAL_NAVI_MAP                 32788
#define ID_32789                        32789
#define ID_CAL_STATIC_LIGHT             32790
#define ID_32791                        32791
#define ID_CAL_DIR_LIGHT                32792
#define ID_EDIT_SELECT                  32794
#define ID_EDITMODE_MOVE                32795
#define ID_EDITMODE_ROTATE              32799
#define ID_EDITMODE_SCALE               32800
#define ID_EDITMODE_ADD                 32802
#define ID_EDITMODE_SELECT              32803
#define ID_32804                        32804
#define ID_COPY_WALK_TO_FLY             32805
#define ID_32806                        32806
#define ID_EXPORT_OBJFILE               32807
#define ID_32808                        32808
#define ID_PREVIEW_CAMERA_ANIM          32809
#define ID_32810                        32810
#define ID_VIEW_BACKCOLOR               32811
#define ID_FINDMODEL                    32812
#define ID_32813                        32813
#define ID_32814                        32814
#define ID_32815                        32815
#define ID_EXPORT_OBJTERRAIN            32816
#define ID_EXPORT_OBJTERRAINANDWATER    32817
#define ID_32818                        32818
#define ID_32819                        32819
#define ID_BEAST_BAKE                   32820
#define ID_SHOW_BEASTBACK               32821
#define ID_BEASTBAKE                    32822
#define ID_32823                        32823
#define ID_USECAMERARENDERTARGET        32824
#define ID_32825                        32825
#define ID_TERRAIN_USE_LIGHTMAP         32826
#define ID_VIEW_PREVIEW                 61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32827
#define _APS_NEXT_CONTROL_VALUE         1133
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
