/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef SIGN_SERVICE_CONF_DESC_H
#define SIGN_SERVICE_CONF_DESC_H


#ifndef TDR_METALIB_SIGN_SERVICE_VERSION 
#define TDR_METALIB_SIGN_SERVICE_VERSION 	10 /*version of metalib*/
#endif

#ifndef TDR_METALIB_SIGN_SERVICE_HASH 
#define TDR_METALIB_SIGN_SERVICE_HASH 	"179c097501e740513cd4c55bc68a6391" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */

#define TORMSVR_STRING_LEN                       	256
#define TORM_MAX_CHANNEL                         	256
#define TORM_MAX_DBCONN                          	32
#define TORM_MAX_TABLE                           	128
#define TORM_MAX_DBMETALIB                       	128
#define TORM_MAX_CACHEMETA                       	128
#define TORM_MAX_RECORDS_NUM_PERSELECT           	100 	/* 单个select查询能检索出的记录行最大数目 */
#define TORM_MAX_CACHE_PERCENT_SYN_SCTMSLCT_RES  	80 	/* 当将自定义查询条件中的记录添加的cache中时，如果cache使用比例超过此值时停止添加记录到cache中 */
#define SIGN_MAX_REGION_NUM                      	16

/* SOAP_ENCODING_TYPE*/
enum tagSOAP_ENCODING_TYPE 
{
    SOAP_ENCODING_TYPE_UTF8 = 0, 	/* UTF8 */
    SOAP_ENCODING_TYPE_GBK = 1, 	/* GBK */
};


#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagTORMConnectDBInfo;
typedef struct tagTORMConnectDBInfo                	TORMCONNECTDBINFO;
typedef struct tagTORMConnectDBInfo                	*LPTORMCONNECTDBINFO;

struct tagRegionDBInfo;
typedef struct tagRegionDBInfo                     	REGIONDBINFO;
typedef struct tagRegionDBInfo                     	*LPREGIONDBINFO;

struct tagRegionAuthInfo;
typedef struct tagRegionAuthInfo                   	REGIONAUTHINFO;
typedef struct tagRegionAuthInfo                   	*LPREGIONAUTHINFO;

struct tagsign_serviceconf;
typedef struct tagsign_serviceconf                 	SIGN_SERVICECONF;
typedef struct tagsign_serviceconf                 	*LPSIGN_SERVICECONF;

struct tagsign_servicerun_status;
typedef struct tagsign_servicerun_status           	SIGN_SERVICERUN_STATUS;
typedef struct tagsign_servicerun_status           	*LPSIGN_SERVICERUN_STATUS;



/*   Define structs/unions.   */

#pragma pack(1)

/* dbms server  info */
struct tagTORMConnectDBInfo
{
    int IDX;                            
    int MajorVersion;                   
    int MinVersion;                     
    char DBMSName[TORMSVR_STRING_LEN];   
    char DBMSConnectionInfo[TORMSVR_STRING_LEN];
    char DBMSCurDatabaseName[TORMSVR_STRING_LEN];
    char DBMSUser[TORMSVR_STRING_LEN];   
    char DBMSPassword[TORMSVR_STRING_LEN];
    char DBMSSock[TORMSVR_STRING_LEN];   
};

/* RegionDBInfo */
struct tagRegionDBInfo
{
    int RegionID;                       
    TORMCONNECTDBINFO DBConnectInfo;                  
};

/* RegionDBInfo */
struct tagRegionAuthInfo
{
    int RegionID;                       
    char AuthIP[24];                      	/*   auth_svr的IP地址 */
    int AuthPort;                        	/*   auth_svr绑定的端口 */
};

struct tagsign_serviceconf
{
    char SpawnIP[24];                     	/*   spawn-fcgi绑定的IP地址 */
    int SpawnPort;                       	/*   spawn-fcgi绑定的端口 */
    int SpawnNum;                        	/*   spawn-fcgi数量,绑定的端口为SpawnPort递增1 */
    int RegionAuthNum;                   	/*   大区验证服务器数量 */
    REGIONAUTHINFO RegionAuthInfo[SIGN_MAX_REGION_NUM]; 	/*   大区验证服务器信息 */
    int ChannelKeyStart;                
    char FcgiWebServerIPList[512];        	/*   配置Fastcgi Web服务器的ip地址列表以逗号(,)分割,不在列表内的ip地址将被禁止访问,未设置则全部允许访问|FCGI_WEB_SERVER_ADDRS */
    int SoapEncoding;                    	/*   soap输入输出编码格式 Bind Macrosgroup:SOAP_ENCODING_TYPE,*/
    char RoleDBMetaFile[128];             	/*   role_db_meta.tdr 路径 */
    TORMCONNECTDBINFO ServiceDBInfo;                   	/*   操作失败日志数据库 */
};

struct tagsign_servicerun_status
{
    int Res;                            
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* SIGN_SERVICE_CONF_DESC_H */
