/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef PROTO_SS_H
#define PROTO_SS_H


#ifndef TDR_METALIB_PROTO_SS_VERSION 
#define TDR_METALIB_PROTO_SS_VERSION 	150 /*version of metalib*/
#endif

#ifndef TDR_METALIB_PROTO_SS_HASH 
#define TDR_METALIB_PROTO_SS_HASH 	"b60a5d9e454c89b9d695fe79ad3bfd3a" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */

#define TFRAMEHEAD_CMD_START                     	0
#define TFRAMEHEAD_CMD_STOP                      	1
#define TFRAMEHEAD_CMD_INPROC                    	2
#define TFRAMEHEAD_CMD_RELAY                     	3
#define TFRAMEHEAD_CMD_NOTIFY                    	4
#define TFRAMEHEAD_CMD_SETROUTING                	5
#define TFRAMEHEAD_MAX_BATCH_IDENT               	512
#define TFRAMEHEAD_EXTRA_IP                      	1
#define TFRAMEHEAD_TIMESTAMP_TIMEVAL             	1
#define SERLIZER_NAME_LEN                        	32
#define TFRAMEHEAD_SET_ROUTING                   	1
#define TFRAMEHEAD_CONNECTKEY_LEN                	16
#define MAXROLENAME                              	32
#define REPORT_MAX_WORLD                         	10
#define MAX_DATA_NUM                             	24

/* BROADCAST_FLAG*/
enum tagBROADCAST_FLAG 
{
    BROADCAST_FLAG_NO = 0, 
    BROADCAST_FLAG_GROUP = 1, 
    BROADCAST_FLAG_ALL = 2, 
};

/* SSCmd*/
enum tagSSCmd 
{
    DIR_REPORT = 0, 
    ZONE_CTRL = 1, 
    CS_CTRL = 2, 
    RECORD_DIR_INFO = 3, 
    DIR_INFO_HOUR = 4, 
    DIR_INFO_DB = 5, 
    AAS_GAME_REQ = 6, 
    AAS_GAME_RES = 7, 
    INFORMER_GET_ACCOUNT_REQ = 8, 
    INFORMER_GET_ACCOUNT_RES = 9, 
    UPDATE_ACCOUNT_REP = 10, 
    CASH_BILL_REQ = 11, 
    CASH_BILL_RES = 12, 
    QUERY_BILL_REQ = 13, 
    QUERY_BILL_RES = 14, 
};

/* CtrlCmd*/
enum tagCtrlCmd 
{
    TEST_REQ = 0, 
    TEST_RES = 1, 
    SHUTDOWN_REQ = 2, 
    SHUTDOWN_RES = 3, 
    LOADSCRIPT_REQ = 4, 
    LOADSCRIPT_RES = 5, 
    RELOAD_REQ = 6, 
    RELOAD_RES = 7, 
};

/* CsCmd*/
enum tagCsCmd 
{
    BLOCKPLAYER_REQ = 0, 
    BLOCKPLAYER_RES = 1, 
    ROLE_LIST_REQ = 2, 
    ROLE_LIST_RES = 3, 
    SILENCE_ROLE_REQ = 4, 
    SILENCE_ROLE_RES = 5, 
    ZONE_REQ = 6, 
    ZONE_RES = 7, 
    GET_ROLE_DETAIL_REQ = 12, 
    GET_ROLE_DETAIL_RES = 13, 
    SET_ROLE_DETAIL_REQ = 14, 
    SET_ROLE_DETAIL_RES = 15, 
    GET_ROLE_SKILLINFO_REQ = 16, 
    GET_ROLE_SKILLINFO_RES = 17, 
    SET_ROLE_SKILLINFO_REQ = 18, 
    SET_ROLE_SKILLINFO_RES = 19, 
    GET_ROLE_ITEMLIST_REQ = 24, 
    GET_ROLE_ITEMLIST_RES = 25, 
    SET_ROLE_ITEMLIST_REQ = 26, 
    SET_ROLE_ITEMLIST_RES = 27, 
    GET_ROLE_DIATHESIS_REQ = 28, 
    GET_ROLE_DIATHESIS_RES = 29, 
    SET_ROLE_DIATHESIS_REQ = 30, 
    SET_ROLE_DIATHESIS_RES = 31, 
    GET_ROLE_TASK_REQ = 32, 
    GET_ROLE_TASK_RES = 33, 
    GET_ROLE_MAIL_LIST_REQ = 34, 
    GET_ROLE_MAIL_LIST_RES = 35, 
    GET_ROLE_MAIL_REQ = 36, 
    GET_ROLE_MAIL_RES = 37, 
    RESTORE_ROLE_REQ = 38, 
    RESTORE_ROLE_RES = 39, 
    DEL_ROLE_MAIL_REQ = 40, 
    DEL_ROLE_MAIL_RES = 41, 
    SEND_MAIL_REQ = 42, 
    SEND_MAIL_RES = 43, 
    GET_ACCOUNT_INFO_FROM_UIN_REQ = 46, 
    GET_ACCOUNT_ID_FROM_ROLENAME_EX_REQ = 47, 
    GET_ACCOUNT_ID_FROM_LOGINNAME_EX_REQ = 48, 
    GET_ACCOUNT_INFO_RES = 49, 
    GET_ACCOUNT_ID_RES = 50, 
    GET_ACCOUNT_ROLELIST_REQ = 51, 
    GET_ACCOUNT_ROLELIST_RES = 52, 
    SET_ACCOUNT_SILENCE_REQ = 53, 
    SET_ACCOUNT_SILENCE_RES = 54, 
    SET_ACCOUNT_FREEZE_REQ = 55, 
    SET_ACCOUNT_FREEZE_RES = 56, 
    DEL_ROLE_TASK_REQ = 57, 
    DEL_ROLE_TASK_RES = 58, 
    CTL_DEL_ROLE_MAIL_REQ = 59, 
    CTL_DEL_ROLE_MAIL_RES = 60, 
    CTL_SEND_MAIL_REQ = 61, 
    CTL_SEND_MAIL_RES = 62, 
    CHG_ROLE_NAME_REQ = 63, 
    CHG_ROLE_NAME_RES = 64, 
    BLOCK_ACCOUNT_REQ = 65, 
    BLOCK_ACCOUNT_RES = 66, 
    SILENCE_ACCOUNT_REQ = 67, 
    SILENCE_ACCOUNT_RES = 68, 
    CTL_BLOCK_ACCOUNT_REQ = 69, 
    CTL_BLOCK_ACCOUNT_RES = 70, 
    CTL_SILENCE_ACCOUNT_REQ = 71, 
    CTL_SILENCE_ACCOUNT_RES = 72, 
    COPY_ROLE_REQ = 73, 
    COPY_ROLE_RES = 74, 
    GET_BULLETIN_LIST_REQ = 75, 
    GET_BULLETIN_LIST_RES = 76, 
    ADD_BULLETIN_REQ = 77, 
    ADD_BULLETIN_RES = 78, 
    DEL_BULLETIN_REQ = 79, 
    DEL_BULLETIN_RES = 80, 
    CTL_GET_BULLETIN_LIST_REQ = 81, 
    CTL_GET_BULLETIN_LIST_RES = 82, 
    CTL_ADD_BULLETIN_REQ = 83, 
    CTL_ADD_BULLETIN_RES = 84, 
    CTL_DEL_BULLETIN_REQ = 85, 
    CTL_DEL_BULLETIN_RES = 86, 
    SET_ACCOUNT_ROLENAME_REQ = 87, 
    SET_ACCOUNT_ROLENAME_RES = 88, 
    CREATE_ITEM_REQ = 89, 
    CREATE_ITEM_RES = 90, 
    UPDATE_ROLELIST_CACHE_REQ = 91, 
    UPDATE_ROLELIST_CACHE_RES = 92, 
    CHG_ROLE_POS_REQ = 93, 
    CHG_ROLE_POS_RES = 94, 
    GET_ROLE_RIDE_REQ = 95, 
    GET_ROLE_RIDE_RES = 96, 
    SET_ROLE_RIDE_REQ = 97, 
    SET_ROLE_RIDE_RES = 98, 
    GET_ROLE_QIYUELIST_REQ = 99, 
    GET_ROLE_QIYUELIST_RES = 100, 
    SET_ROLE_QIYUE_REQ = 101, 
    SET_ROLE_QIYUE_RES = 102, 
    ADD_ROLE_QIYUE_REQ = 103, 
    ADD_ROLE_QIYUE_RES = 104, 
    DEL_ROLE_QIYUE_REQ = 105, 
    DEL_ROLE_QIYUE_RES = 106, 
    MODIFY_ROLE_FAIRY_REQ = 107, 
    MODIFY_ROLE_FAIRY_RES = 108, 
    GET_ROLE_PET_REQ = 109, 
    GET_ROLE_PET_RES = 110, 
    SET_ROLE_PET_REQ = 111, 
    SET_ROLE_PET_RES = 112, 
    OUTLINE_RES = 113, 
    ADD_ROLE_DESIGNATION_REQ = 114, 
    ADD_ROLE_DESIGNATION_RES = 115, 
    DEL_ROLE_DESIGNATION_REQ = 116, 
    DEL_ROLE_DESIGNATION_RES = 117, 
    GET_ROLE_DESIGNATION_LIST_REQ = 118, 
    GET_ROLE_DESIGNATION_LIST_RES = 119, 
    SET_ROLE_RESPACT_REQ = 120, 
    SET_ROLE_RESPACT_RES = 121, 
    DEL_ROLE_RESPACT_REQ = 128, 
    DEL_ROLE_RESPACT_RES = 129, 
    GET_ROLE_RESPACT_LIST_REQ = 130, 
    GET_ROLE_RESPACT_LIST_RES = 131, 
};

/* RoleFittingOp*/
enum tagRoleFittingOp 
{
    ROLE_FITTING_DEL = 0, 
    ROLE_FITTING_MODIFY = 1, 
    ROLE_FITTING_ADD = 2, 
};

/* RoleFairyOp*/
enum tagRoleFairyOp 
{
    ROLE_FAIRY_DEL = 0, 
    ROLE_FAIRY_MODIFY = 1, 
    ROLE_FAIRY_ADD = 2, 
};

/* RoleSkillOp*/
enum tagRoleSkillOp 
{
    ROLE_SKILL_DEL = 0, 
    ROLE_SKILL_MODIFY = 1, 
    ROLE_SKILL_ADD = 2, 
};

/* RoleDiathesisOp*/
enum tagRoleDiathesisOp 
{
    ROLE_DIATHESIS_DEL = 0, 
    ROLE_DIATHESIS_MODIFY = 1, 
    ROLE_DIATHESIS_ADD = 2, 
};

/* RoleItemOp*/
enum tagRoleItemOp 
{
    ROLE_ITEM_DEL = 0, 
    ROLE_ITEM_MODIFY = 1, 
    ROLE_ITEM_ADD = 2, 
};
#define MAX_SCRIPT_NAME                          	128

/* LOADSCRIPT_TYPE*/
enum tagLOADSCRIPT_TYPE 
{
    LOADSCRIPT_ONE = 0, 
    LOADSCRIPT_ALL = 1, 
};
#define CS_ASYN_DATA                             	40960
#define INFORMER_ACCOUNT_LOGIN_NAME_LEN          	51
#define INFORMER_BIRTHDAY_LEN                    	9
#define ACC_PATTERN_LEN                          	256
#define ACC_MAX_RES                              	64
#define ROLE_MAX_RES                             	60
#define ROLE_GRID_MAX_RES                        	64

/* CS_ERR*/
enum tagCS_ERR 
{
    CS_ERR_SUCCEEDED = 0, 	/* 操作成功 */
    CS_ERR_SYS = -1, 	/* 系统错误 */
    CS_ERR_NET = -2, 	/* 网络错误 */
    CS_ERR_TDR = -3, 	/* TDR错误 */
    CS_ERR_ARGS = -4, 	/* 参数错误 */
    CS_ERR_ONLINE = -5, 	/* 操作必须角色不在线 */
};

/* RolePetOp*/
enum tagRolePetOp 
{
    ROLE_PET_DEL = 0, 	/* 删除 */
    ROLE_PET_MODIFY = 1, 	/* 修改 */
    ROLE_PET_ADD = 2, 	/* 增加 */
};

/* RoleRideOp*/
enum tagRoleRideOp 
{
    ROLE_RIDE_DEL = 0, 	/* 删除 */
    ROLE_RIDE_MODIFY = 1, 	/* 修改 */
    ROLE_RIDE_ADD = 2, 	/* 增加 */
};

/* AAS_ACT_TYPE*/
enum tagAAS_ACT_TYPE 
{
    AAS_GAME_START = 0, 	/* 开始游戏 */
    AAS_GAME_ACTIVE = 1, 	/* 心跳包 */
    AAS_GAME_END = 2, 	/* 退出游戏 */
    AAS_TIME_SET = 3, 	/* 设置防沉迷时间 */
};


#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagTIPInfo;
typedef struct tagTIPInfo                          	TIPINFO;
typedef struct tagTIPInfo                          	*LPTIPINFO;

union tagTFrameHeadData;
typedef union  tagTFrameHeadData                   	TFRAMEHEADDATA;
typedef union  tagTFrameHeadData                   	*LPTFRAMEHEADDATA;

struct tagTFrameAuthJC;
typedef struct tagTFrameAuthJC                     	TFRAMEAUTHJC;
typedef struct tagTFrameAuthJC                     	*LPTFRAMEAUTHJC;

union tagTFrameAuthData;
typedef union  tagTFrameAuthData                   	TFRAMEAUTHDATA;
typedef union  tagTFrameAuthData                   	*LPTFRAMEAUTHDATA;

struct tagTFrameCmdStart;
typedef struct tagTFrameCmdStart                   	TFRAMECMDSTART;
typedef struct tagTFrameCmdStart                   	*LPTFRAMECMDSTART;

struct tagTFrameCmdStop;
typedef struct tagTFrameCmdStop                    	TFRAMECMDSTOP;
typedef struct tagTFrameCmdStop                    	*LPTFRAMECMDSTOP;

struct tagTFrameIdent;
typedef struct tagTFrameIdent                      	TFRAMEIDENT;
typedef struct tagTFrameIdent                      	*LPTFRAMEIDENT;

struct tagTFrameCmdInProc;
typedef struct tagTFrameCmdInProc                  	TFRAMECMDINPROC;
typedef struct tagTFrameCmdInProc                  	*LPTFRAMECMDINPROC;

struct tagTFrameCmdRelay;
typedef struct tagTFrameCmdRelay                   	TFRAMECMDRELAY;
typedef struct tagTFrameCmdRelay                   	*LPTFRAMECMDRELAY;

struct tagTFrameCmdSetRouting;
typedef struct tagTFrameCmdSetRouting              	TFRAMECMDSETROUTING;
typedef struct tagTFrameCmdSetRouting              	*LPTFRAMECMDSETROUTING;

union tagTRoutingOption;
typedef union  tagTRoutingOption                   	TROUTINGOPTION;
typedef union  tagTRoutingOption                   	*LPTROUTINGOPTION;

struct tagTFrameCmdNotify;
typedef struct tagTFrameCmdNotify                  	TFRAMECMDNOTIFY;
typedef struct tagTFrameCmdNotify                  	*LPTFRAMECMDNOTIFY;

union tagTFrameCmdData;
typedef union  tagTFrameCmdData                    	TFRAMECMDDATA;
typedef union  tagTFrameCmdData                    	*LPTFRAMECMDDATA;

struct tagTTimeVal;
typedef struct tagTTimeVal                         	TTIMEVAL;
typedef struct tagTTimeVal                         	*LPTTIMEVAL;

union tagTTimeStampData;
typedef union  tagTTimeStampData                   	TTIMESTAMPDATA;
typedef union  tagTTimeStampData                   	*LPTTIMESTAMPDATA;

struct tagtframehead;
typedef struct tagtframehead                       	TFRAMEHEAD;
typedef struct tagtframehead                       	*LPTFRAMEHEAD;

struct tagSSPkgHead;
typedef struct tagSSPkgHead                        	SSPKGHEAD;
typedef struct tagSSPkgHead                        	*LPSSPKGHEAD;

struct tagSSDirReport;
typedef struct tagSSDirReport                      	SSDIRREPORT;
typedef struct tagSSDirReport                      	*LPSSDIRREPORT;

struct tagHourData;
typedef struct tagHourData                         	HOURDATA;
typedef struct tagHourData                         	*LPHOURDATA;

struct tagRePortData;
typedef struct tagRePortData                       	REPORTDATA;
typedef struct tagRePortData                       	*LPREPORTDATA;

struct tagSSRePortDataAll;
typedef struct tagSSRePortDataAll                  	SSREPORTDATAALL;
typedef struct tagSSRePortDataAll                  	*LPSSREPORTDATAALL;

struct tagSSWorldInfoHour;
typedef struct tagSSWorldInfoHour                  	SSWORLDINFOHOUR;
typedef struct tagSSWorldInfoHour                  	*LPSSWORLDINFOHOUR;

struct tagSSDirInfoHour;
typedef struct tagSSDirInfoHour                    	SSDIRINFOHOUR;
typedef struct tagSSDirInfoHour                    	*LPSSDIRINFOHOUR;

struct tagDirInfoDB;
typedef struct tagDirInfoDB                        	DIRINFODB;
typedef struct tagDirInfoDB                        	*LPDIRINFODB;

struct tagSSDirInfoDB;
typedef struct tagSSDirInfoDB                      	SSDIRINFODB;
typedef struct tagSSDirInfoDB                      	*LPSSDIRINFODB;

struct tagZoneChgRoleNameReq;
typedef struct tagZoneChgRoleNameReq               	ZONECHGROLENAMEREQ;
typedef struct tagZoneChgRoleNameReq               	*LPZONECHGROLENAMEREQ;

struct tagZoneChgRoleNameRes;
typedef struct tagZoneChgRoleNameRes               	ZONECHGROLENAMERES;
typedef struct tagZoneChgRoleNameRes               	*LPZONECHGROLENAMERES;

struct tagZoneTestReq;
typedef struct tagZoneTestReq                      	ZONETESTREQ;
typedef struct tagZoneTestReq                      	*LPZONETESTREQ;

struct tagZoneOutLineRes;
typedef struct tagZoneOutLineRes                   	ZONEOUTLINERES;
typedef struct tagZoneOutLineRes                   	*LPZONEOUTLINERES;

struct tagZoneTestRes;
typedef struct tagZoneTestRes                      	ZONETESTRES;
typedef struct tagZoneTestRes                      	*LPZONETESTRES;

struct tagZoneShutDownReq;
typedef struct tagZoneShutDownReq                  	ZONESHUTDOWNREQ;
typedef struct tagZoneShutDownReq                  	*LPZONESHUTDOWNREQ;

struct tagZoneShutDownRes;
typedef struct tagZoneShutDownRes                  	ZONESHUTDOWNRES;
typedef struct tagZoneShutDownRes                  	*LPZONESHUTDOWNRES;

struct tagZoneBlockPlayerReq;
typedef struct tagZoneBlockPlayerReq               	ZONEBLOCKPLAYERREQ;
typedef struct tagZoneBlockPlayerReq               	*LPZONEBLOCKPLAYERREQ;

struct tagZoneBlockPlayerRes;
typedef struct tagZoneBlockPlayerRes               	ZONEBLOCKPLAYERRES;
typedef struct tagZoneBlockPlayerRes               	*LPZONEBLOCKPLAYERRES;

struct tagZoneRoleInfo;
typedef struct tagZoneRoleInfo                     	ZONEROLEINFO;
typedef struct tagZoneRoleInfo                     	*LPZONEROLEINFO;

struct tagZoneRoleBaseInfo;
typedef struct tagZoneRoleBaseInfo                 	ZONEROLEBASEINFO;
typedef struct tagZoneRoleBaseInfo                 	*LPZONEROLEBASEINFO;

struct tagZoneRoleListReq;
typedef struct tagZoneRoleListReq                  	ZONEROLELISTREQ;
typedef struct tagZoneRoleListReq                  	*LPZONEROLELISTREQ;

struct tagSSRoleList;
typedef struct tagSSRoleList                       	SSROLELIST;
typedef struct tagSSRoleList                       	*LPSSROLELIST;

struct tagZoneRoleListRes;
typedef struct tagZoneRoleListRes                  	ZONEROLELISTRES;
typedef struct tagZoneRoleListRes                  	*LPZONEROLELISTRES;

struct tagZoneSilenceRoleReq;
typedef struct tagZoneSilenceRoleReq               	ZONESILENCEROLEREQ;
typedef struct tagZoneSilenceRoleReq               	*LPZONESILENCEROLEREQ;

struct tagZoneSilenceRoleRes;
typedef struct tagZoneSilenceRoleRes               	ZONESILENCEROLERES;
typedef struct tagZoneSilenceRoleRes               	*LPZONESILENCEROLERES;

struct tagZoneGetRoleBaseInfoReq;
typedef struct tagZoneGetRoleBaseInfoReq           	ZONEGETROLEBASEINFOREQ;
typedef struct tagZoneGetRoleBaseInfoReq           	*LPZONEGETROLEBASEINFOREQ;

struct tagZoneGetRoleBaseInfoRes;
typedef struct tagZoneGetRoleBaseInfoRes           	ZONEGETROLEBASEINFORES;
typedef struct tagZoneGetRoleBaseInfoRes           	*LPZONEGETROLEBASEINFORES;

struct tagZoneSetRoleBaseInfoReq;
typedef struct tagZoneSetRoleBaseInfoReq           	ZONESETROLEBASEINFOREQ;
typedef struct tagZoneSetRoleBaseInfoReq           	*LPZONESETROLEBASEINFOREQ;

struct tagZoneSetRoleBaseInfoRes;
typedef struct tagZoneSetRoleBaseInfoRes           	ZONESETROLEBASEINFORES;
typedef struct tagZoneSetRoleBaseInfoRes           	*LPZONESETROLEBASEINFORES;

struct tagZoneGetRoleDetailReq;
typedef struct tagZoneGetRoleDetailReq             	ZONEGETROLEDETAILREQ;
typedef struct tagZoneGetRoleDetailReq             	*LPZONEGETROLEDETAILREQ;

struct tagZoneGetRoleDetailRes;
typedef struct tagZoneGetRoleDetailRes             	ZONEGETROLEDETAILRES;
typedef struct tagZoneGetRoleDetailRes             	*LPZONEGETROLEDETAILRES;

struct tagZoneSetRoleDetailReq;
typedef struct tagZoneSetRoleDetailReq             	ZONESETROLEDETAILREQ;
typedef struct tagZoneSetRoleDetailReq             	*LPZONESETROLEDETAILREQ;

struct tagZoneSetRoleDetailRes;
typedef struct tagZoneSetRoleDetailRes             	ZONESETROLEDETAILRES;
typedef struct tagZoneSetRoleDetailRes             	*LPZONESETROLEDETAILRES;

struct tagZoneGetRoleSkillInfoReq;
typedef struct tagZoneGetRoleSkillInfoReq          	ZONEGETROLESKILLINFOREQ;
typedef struct tagZoneGetRoleSkillInfoReq          	*LPZONEGETROLESKILLINFOREQ;

struct tagZoneGetRoleSkillInfoRes;
typedef struct tagZoneGetRoleSkillInfoRes          	ZONEGETROLESKILLINFORES;
typedef struct tagZoneGetRoleSkillInfoRes          	*LPZONEGETROLESKILLINFORES;

struct tagZoneSetRoleFairyReq;
typedef struct tagZoneSetRoleFairyReq              	ZONESETROLEFAIRYREQ;
typedef struct tagZoneSetRoleFairyReq              	*LPZONESETROLEFAIRYREQ;

struct tagZoneSetRoleFairyRes;
typedef struct tagZoneSetRoleFairyRes              	ZONESETROLEFAIRYRES;
typedef struct tagZoneSetRoleFairyRes              	*LPZONESETROLEFAIRYRES;

struct tagZoneSetRoleSkillInfoReq;
typedef struct tagZoneSetRoleSkillInfoReq          	ZONESETROLESKILLINFOREQ;
typedef struct tagZoneSetRoleSkillInfoReq          	*LPZONESETROLESKILLINFOREQ;

struct tagZoneSetRoleSkillInfoRes;
typedef struct tagZoneSetRoleSkillInfoRes          	ZONESETROLESKILLINFORES;
typedef struct tagZoneSetRoleSkillInfoRes          	*LPZONESETROLESKILLINFORES;

struct tagZoneSetRoleDiathesisReq;
typedef struct tagZoneSetRoleDiathesisReq          	ZONESETROLEDIATHESISREQ;
typedef struct tagZoneSetRoleDiathesisReq          	*LPZONESETROLEDIATHESISREQ;

struct tagZoneSetRoleDiathesisRes;
typedef struct tagZoneSetRoleDiathesisRes          	ZONESETROLEDIATHESISRES;
typedef struct tagZoneSetRoleDiathesisRes          	*LPZONESETROLEDIATHESISRES;

struct tagZoneGetRoleDiathesisReq;
typedef struct tagZoneGetRoleDiathesisReq          	ZONEGETROLEDIATHESISREQ;
typedef struct tagZoneGetRoleDiathesisReq          	*LPZONEGETROLEDIATHESISREQ;

struct tagZoneGetRoleDiathesisRes;
typedef struct tagZoneGetRoleDiathesisRes          	ZONEGETROLEDIATHESISRES;
typedef struct tagZoneGetRoleDiathesisRes          	*LPZONEGETROLEDIATHESISRES;

struct tagZoneGetRoleItemListReq;
typedef struct tagZoneGetRoleItemListReq           	ZONEGETROLEITEMLISTREQ;
typedef struct tagZoneGetRoleItemListReq           	*LPZONEGETROLEITEMLISTREQ;

struct tagZoneGetRoleItemListRes;
typedef struct tagZoneGetRoleItemListRes           	ZONEGETROLEITEMLISTRES;
typedef struct tagZoneGetRoleItemListRes           	*LPZONEGETROLEITEMLISTRES;

struct tagZoneGetRoleTaskReq;
typedef struct tagZoneGetRoleTaskReq               	ZONEGETROLETASKREQ;
typedef struct tagZoneGetRoleTaskReq               	*LPZONEGETROLETASKREQ;

struct tagZoneGetRoleTaskRes;
typedef struct tagZoneGetRoleTaskRes               	ZONEGETROLETASKRES;
typedef struct tagZoneGetRoleTaskRes               	*LPZONEGETROLETASKRES;

struct tagZoneDelRoleTaskReq;
typedef struct tagZoneDelRoleTaskReq               	ZONEDELROLETASKREQ;
typedef struct tagZoneDelRoleTaskReq               	*LPZONEDELROLETASKREQ;

struct tagZoneDelRoleTaskRes;
typedef struct tagZoneDelRoleTaskRes               	ZONEDELROLETASKRES;
typedef struct tagZoneDelRoleTaskRes               	*LPZONEDELROLETASKRES;

struct tagZoneSetRoleItemListReq;
typedef struct tagZoneSetRoleItemListReq           	ZONESETROLEITEMLISTREQ;
typedef struct tagZoneSetRoleItemListReq           	*LPZONESETROLEITEMLISTREQ;

struct tagZoneSetRoleItemListRes;
typedef struct tagZoneSetRoleItemListRes           	ZONESETROLEITEMLISTRES;
typedef struct tagZoneSetRoleItemListRes           	*LPZONESETROLEITEMLISTRES;

struct tagZoneLoadScriptReq;
typedef struct tagZoneLoadScriptReq                	ZONELOADSCRIPTREQ;
typedef struct tagZoneLoadScriptReq                	*LPZONELOADSCRIPTREQ;

struct tagZoneReLoadReq;
typedef struct tagZoneReLoadReq                    	ZONERELOADREQ;
typedef struct tagZoneReLoadReq                    	*LPZONERELOADREQ;

struct tagZoneLoadScriptRes;
typedef struct tagZoneLoadScriptRes                	ZONELOADSCRIPTRES;
typedef struct tagZoneLoadScriptRes                	*LPZONELOADSCRIPTRES;

struct tagZoneReLoadRes;
typedef struct tagZoneReLoadRes                    	ZONERELOADRES;
typedef struct tagZoneReLoadRes                    	*LPZONERELOADRES;

union tagSSCtrlCmd;
typedef union  tagSSCtrlCmd                        	SSCTRLCMD;
typedef union  tagSSCtrlCmd                        	*LPSSCTRLCMD;

struct tagAsynReq;
typedef struct tagAsynReq                          	ASYNREQ;
typedef struct tagAsynReq                          	*LPASYNREQ;

struct tagAsynRes;
typedef struct tagAsynRes                          	ASYNRES;
typedef struct tagAsynRes                          	*LPASYNRES;

struct tagInformerAccount;
typedef struct tagInformerAccount                  	INFORMERACCOUNT;
typedef struct tagInformerAccount                  	*LPINFORMERACCOUNT;

struct tagSSGetAccountReq;
typedef struct tagSSGetAccountReq                  	SSGETACCOUNTREQ;
typedef struct tagSSGetAccountReq                  	*LPSSGETACCOUNTREQ;

struct tagSSGetAccountRes;
typedef struct tagSSGetAccountRes                  	SSGETACCOUNTRES;
typedef struct tagSSGetAccountRes                  	*LPSSGETACCOUNTRES;

struct tagAccGetInfoFromUinReq;
typedef struct tagAccGetInfoFromUinReq             	ACCGETINFOFROMUINREQ;
typedef struct tagAccGetInfoFromUinReq             	*LPACCGETINFOFROMUINREQ;

struct tagAccGetIDFromRoleNameExReq;
typedef struct tagAccGetIDFromRoleNameExReq        	ACCGETIDFROMROLENAMEEXREQ;
typedef struct tagAccGetIDFromRoleNameExReq        	*LPACCGETIDFROMROLENAMEEXREQ;

struct tagAccGetIDFromLoginNameExReq;
typedef struct tagAccGetIDFromLoginNameExReq       	ACCGETIDFROMLOGINNAMEEXREQ;
typedef struct tagAccGetIDFromLoginNameExReq       	*LPACCGETIDFROMLOGINNAMEEXREQ;

struct tagSSAccInfo;
typedef struct tagSSAccInfo                        	SSACCINFO;
typedef struct tagSSAccInfo                        	*LPSSACCINFO;

struct tagAccGetInfoRes;
typedef struct tagAccGetInfoRes                    	ACCGETINFORES;
typedef struct tagAccGetInfoRes                    	*LPACCGETINFORES;

struct tagAccIDInfo;
typedef struct tagAccIDInfo                        	ACCIDINFO;
typedef struct tagAccIDInfo                        	*LPACCIDINFO;

struct tagAccGetIDRes;
typedef struct tagAccGetIDRes                      	ACCGETIDRES;
typedef struct tagAccGetIDRes                      	*LPACCGETIDRES;

struct tagAccSetSilenceReq;
typedef struct tagAccSetSilenceReq                 	ACCSETSILENCEREQ;
typedef struct tagAccSetSilenceReq                 	*LPACCSETSILENCEREQ;

struct tagAccSetSilenceRes;
typedef struct tagAccSetSilenceRes                 	ACCSETSILENCERES;
typedef struct tagAccSetSilenceRes                 	*LPACCSETSILENCERES;

struct tagAccSetFreezeReq;
typedef struct tagAccSetFreezeReq                  	ACCSETFREEZEREQ;
typedef struct tagAccSetFreezeReq                  	*LPACCSETFREEZEREQ;

struct tagAccSetFreezeRes;
typedef struct tagAccSetFreezeRes                  	ACCSETFREEZERES;
typedef struct tagAccSetFreezeRes                  	*LPACCSETFREEZERES;

struct tagAccSetRoleNameReq;
typedef struct tagAccSetRoleNameReq                	ACCSETROLENAMEREQ;
typedef struct tagAccSetRoleNameReq                	*LPACCSETROLENAMEREQ;

struct tagAccSetRoleNameRes;
typedef struct tagAccSetRoleNameRes                	ACCSETROLENAMERES;
typedef struct tagAccSetRoleNameRes                	*LPACCSETROLENAMERES;

struct tagAccGetRoleListReq;
typedef struct tagAccGetRoleListReq                	ACCGETROLELISTREQ;
typedef struct tagAccGetRoleListReq                	*LPACCGETROLELISTREQ;

struct tagSSAccRoleLite;
typedef struct tagSSAccRoleLite                    	SSACCROLELITE;
typedef struct tagSSAccRoleLite                    	*LPSSACCROLELITE;

struct tagAccGetRoleListRes;
typedef struct tagAccGetRoleListRes                	ACCGETROLELISTRES;
typedef struct tagAccGetRoleListRes                	*LPACCGETROLELISTRES;

struct tagZoneConnCtx;
typedef struct tagZoneConnCtx                      	ZONECONNCTX;
typedef struct tagZoneConnCtx                      	*LPZONECONNCTX;

struct tagZoneGetMailListReq;
typedef struct tagZoneGetMailListReq               	ZONEGETMAILLISTREQ;
typedef struct tagZoneGetMailListReq               	*LPZONEGETMAILLISTREQ;

struct tagZoneGetMailListRes;
typedef struct tagZoneGetMailListRes               	ZONEGETMAILLISTRES;
typedef struct tagZoneGetMailListRes               	*LPZONEGETMAILLISTRES;

struct tagZoneGetMailReq;
typedef struct tagZoneGetMailReq                   	ZONEGETMAILREQ;
typedef struct tagZoneGetMailReq                   	*LPZONEGETMAILREQ;

struct tagZoneGetMailRes;
typedef struct tagZoneGetMailRes                   	ZONEGETMAILRES;
typedef struct tagZoneGetMailRes                   	*LPZONEGETMAILRES;

struct tagZoneDelMailReq;
typedef struct tagZoneDelMailReq                   	ZONEDELMAILREQ;
typedef struct tagZoneDelMailReq                   	*LPZONEDELMAILREQ;

struct tagZoneDelMailRes;
typedef struct tagZoneDelMailRes                   	ZONEDELMAILRES;
typedef struct tagZoneDelMailRes                   	*LPZONEDELMAILRES;

struct tagZoneCtlDelMailReq;
typedef struct tagZoneCtlDelMailReq                	ZONECTLDELMAILREQ;
typedef struct tagZoneCtlDelMailReq                	*LPZONECTLDELMAILREQ;

struct tagZoneCtlDelMailRes;
typedef struct tagZoneCtlDelMailRes                	ZONECTLDELMAILRES;
typedef struct tagZoneCtlDelMailRes                	*LPZONECTLDELMAILRES;

struct tagZoneSendMailReq;
typedef struct tagZoneSendMailReq                  	ZONESENDMAILREQ;
typedef struct tagZoneSendMailReq                  	*LPZONESENDMAILREQ;

struct tagZoneSendMailRes;
typedef struct tagZoneSendMailRes                  	ZONESENDMAILRES;
typedef struct tagZoneSendMailRes                  	*LPZONESENDMAILRES;

struct tagZoneCtlSendMailReq;
typedef struct tagZoneCtlSendMailReq               	ZONECTLSENDMAILREQ;
typedef struct tagZoneCtlSendMailReq               	*LPZONECTLSENDMAILREQ;

struct tagZoneCtlSendMailRes;
typedef struct tagZoneCtlSendMailRes               	ZONECTLSENDMAILRES;
typedef struct tagZoneCtlSendMailRes               	*LPZONECTLSENDMAILRES;

struct tagZoneBlockAccountReq;
typedef struct tagZoneBlockAccountReq              	ZONEBLOCKACCOUNTREQ;
typedef struct tagZoneBlockAccountReq              	*LPZONEBLOCKACCOUNTREQ;

struct tagZoneBlockAccountRes;
typedef struct tagZoneBlockAccountRes              	ZONEBLOCKACCOUNTRES;
typedef struct tagZoneBlockAccountRes              	*LPZONEBLOCKACCOUNTRES;

struct tagZoneSilenceAccountReq;
typedef struct tagZoneSilenceAccountReq            	ZONESILENCEACCOUNTREQ;
typedef struct tagZoneSilenceAccountReq            	*LPZONESILENCEACCOUNTREQ;

struct tagZoneSilenceAccountRes;
typedef struct tagZoneSilenceAccountRes            	ZONESILENCEACCOUNTRES;
typedef struct tagZoneSilenceAccountRes            	*LPZONESILENCEACCOUNTRES;

struct tagZoneCtlBlockAccountReq;
typedef struct tagZoneCtlBlockAccountReq           	ZONECTLBLOCKACCOUNTREQ;
typedef struct tagZoneCtlBlockAccountReq           	*LPZONECTLBLOCKACCOUNTREQ;

struct tagZoneCtlBlockAccountRes;
typedef struct tagZoneCtlBlockAccountRes           	ZONECTLBLOCKACCOUNTRES;
typedef struct tagZoneCtlBlockAccountRes           	*LPZONECTLBLOCKACCOUNTRES;

struct tagZoneCtlSilenceAccountReq;
typedef struct tagZoneCtlSilenceAccountReq         	ZONECTLSILENCEACCOUNTREQ;
typedef struct tagZoneCtlSilenceAccountReq         	*LPZONECTLSILENCEACCOUNTREQ;

struct tagZoneCtlSilenceAccountRes;
typedef struct tagZoneCtlSilenceAccountRes         	ZONECTLSILENCEACCOUNTRES;
typedef struct tagZoneCtlSilenceAccountRes         	*LPZONECTLSILENCEACCOUNTRES;

struct tagSSRestoreRoleReq;
typedef struct tagSSRestoreRoleReq                 	SSRESTOREROLEREQ;
typedef struct tagSSRestoreRoleReq                 	*LPSSRESTOREROLEREQ;

struct tagSSRestoreRoleRes;
typedef struct tagSSRestoreRoleRes                 	SSRESTOREROLERES;
typedef struct tagSSRestoreRoleRes                 	*LPSSRESTOREROLERES;

struct tagSSRoleStoragePath;
typedef struct tagSSRoleStoragePath                	SSROLESTORAGEPATH;
typedef struct tagSSRoleStoragePath                	*LPSSROLESTORAGEPATH;

struct tagZoneCopyRoleReq;
typedef struct tagZoneCopyRoleReq                  	ZONECOPYROLEREQ;
typedef struct tagZoneCopyRoleReq                  	*LPZONECOPYROLEREQ;

struct tagZoneCopyRoleRes;
typedef struct tagZoneCopyRoleRes                  	ZONECOPYROLERES;
typedef struct tagZoneCopyRoleRes                  	*LPZONECOPYROLERES;

struct tagZoneGetBulletinListReq;
typedef struct tagZoneGetBulletinListReq           	ZONEGETBULLETINLISTREQ;
typedef struct tagZoneGetBulletinListReq           	*LPZONEGETBULLETINLISTREQ;

struct tagSSBulletin;
typedef struct tagSSBulletin                       	SSBULLETIN;
typedef struct tagSSBulletin                       	*LPSSBULLETIN;

struct tagZoneGetBulletinListRes;
typedef struct tagZoneGetBulletinListRes           	ZONEGETBULLETINLISTRES;
typedef struct tagZoneGetBulletinListRes           	*LPZONEGETBULLETINLISTRES;

struct tagZoneAddBulletinReq;
typedef struct tagZoneAddBulletinReq               	ZONEADDBULLETINREQ;
typedef struct tagZoneAddBulletinReq               	*LPZONEADDBULLETINREQ;

struct tagZoneAddBulletinRes;
typedef struct tagZoneAddBulletinRes               	ZONEADDBULLETINRES;
typedef struct tagZoneAddBulletinRes               	*LPZONEADDBULLETINRES;

struct tagZoneDelBulletinReq;
typedef struct tagZoneDelBulletinReq               	ZONEDELBULLETINREQ;
typedef struct tagZoneDelBulletinReq               	*LPZONEDELBULLETINREQ;

struct tagZoneDelBulletinRes;
typedef struct tagZoneDelBulletinRes               	ZONEDELBULLETINRES;
typedef struct tagZoneDelBulletinRes               	*LPZONEDELBULLETINRES;

struct tagZoneCtlGetBulletinListReq;
typedef struct tagZoneCtlGetBulletinListReq        	ZONECTLGETBULLETINLISTREQ;
typedef struct tagZoneCtlGetBulletinListReq        	*LPZONECTLGETBULLETINLISTREQ;

struct tagZoneCtlGetBulletinListRes;
typedef struct tagZoneCtlGetBulletinListRes        	ZONECTLGETBULLETINLISTRES;
typedef struct tagZoneCtlGetBulletinListRes        	*LPZONECTLGETBULLETINLISTRES;

struct tagZoneCtlAddBulletinReq;
typedef struct tagZoneCtlAddBulletinReq            	ZONECTLADDBULLETINREQ;
typedef struct tagZoneCtlAddBulletinReq            	*LPZONECTLADDBULLETINREQ;

struct tagZoneCtlAddBulletinRes;
typedef struct tagZoneCtlAddBulletinRes            	ZONECTLADDBULLETINRES;
typedef struct tagZoneCtlAddBulletinRes            	*LPZONECTLADDBULLETINRES;

struct tagZoneCtlDelBulletinReq;
typedef struct tagZoneCtlDelBulletinReq            	ZONECTLDELBULLETINREQ;
typedef struct tagZoneCtlDelBulletinReq            	*LPZONECTLDELBULLETINREQ;

struct tagZoneCtlDelBulletinRes;
typedef struct tagZoneCtlDelBulletinRes            	ZONECTLDELBULLETINRES;
typedef struct tagZoneCtlDelBulletinRes            	*LPZONECTLDELBULLETINRES;

struct tagSSItemIdent;
typedef struct tagSSItemIdent                      	SSITEMIDENT;
typedef struct tagSSItemIdent                      	*LPSSITEMIDENT;

struct tagZoneCreateItemReq;
typedef struct tagZoneCreateItemReq                	ZONECREATEITEMREQ;
typedef struct tagZoneCreateItemReq                	*LPZONECREATEITEMREQ;

struct tagZoneCreateItemRes;
typedef struct tagZoneCreateItemRes                	ZONECREATEITEMRES;
typedef struct tagZoneCreateItemRes                	*LPZONECREATEITEMRES;

struct tagZoneUpdateRoleListCacheReq;
typedef struct tagZoneUpdateRoleListCacheReq       	ZONEUPDATEROLELISTCACHEREQ;
typedef struct tagZoneUpdateRoleListCacheReq       	*LPZONEUPDATEROLELISTCACHEREQ;

struct tagZoneAddRoleDesignationReq;
typedef struct tagZoneAddRoleDesignationReq        	ZONEADDROLEDESIGNATIONREQ;
typedef struct tagZoneAddRoleDesignationReq        	*LPZONEADDROLEDESIGNATIONREQ;

struct tagZoneAddRoleDesignationRes;
typedef struct tagZoneAddRoleDesignationRes        	ZONEADDROLEDESIGNATIONRES;
typedef struct tagZoneAddRoleDesignationRes        	*LPZONEADDROLEDESIGNATIONRES;

struct tagZoneDelRoleDesignationReq;
typedef struct tagZoneDelRoleDesignationReq        	ZONEDELROLEDESIGNATIONREQ;
typedef struct tagZoneDelRoleDesignationReq        	*LPZONEDELROLEDESIGNATIONREQ;

struct tagZoneDelRoleDesignationRes;
typedef struct tagZoneDelRoleDesignationRes        	ZONEDELROLEDESIGNATIONRES;
typedef struct tagZoneDelRoleDesignationRes        	*LPZONEDELROLEDESIGNATIONRES;

struct tagZoneGetRoleDesignationListReq;
typedef struct tagZoneGetRoleDesignationListReq    	ZONEGETROLEDESIGNATIONLISTREQ;
typedef struct tagZoneGetRoleDesignationListReq    	*LPZONEGETROLEDESIGNATIONLISTREQ;

struct tagZoneGetRoleDesignationListRes;
typedef struct tagZoneGetRoleDesignationListRes    	ZONEGETROLEDESIGNATIONLISTRES;
typedef struct tagZoneGetRoleDesignationListRes    	*LPZONEGETROLEDESIGNATIONLISTRES;

struct tagZoneSetRoleRespactReq;
typedef struct tagZoneSetRoleRespactReq            	ZONESETROLERESPACTREQ;
typedef struct tagZoneSetRoleRespactReq            	*LPZONESETROLERESPACTREQ;

struct tagZoneSetRoleRespactRes;
typedef struct tagZoneSetRoleRespactRes            	ZONESETROLERESPACTRES;
typedef struct tagZoneSetRoleRespactRes            	*LPZONESETROLERESPACTRES;

struct tagZoneDelRoleRespactReq;
typedef struct tagZoneDelRoleRespactReq            	ZONEDELROLERESPACTREQ;
typedef struct tagZoneDelRoleRespactReq            	*LPZONEDELROLERESPACTREQ;

struct tagZoneDelRoleRespactRes;
typedef struct tagZoneDelRoleRespactRes            	ZONEDELROLERESPACTRES;
typedef struct tagZoneDelRoleRespactRes            	*LPZONEDELROLERESPACTRES;

struct tagZoneGetRoleRespactListReq;
typedef struct tagZoneGetRoleRespactListReq        	ZONEGETROLERESPACTLISTREQ;
typedef struct tagZoneGetRoleRespactListReq        	*LPZONEGETROLERESPACTLISTREQ;

struct tagZoneGetRoleRespactListRes;
typedef struct tagZoneGetRoleRespactListRes        	ZONEGETROLERESPACTLISTRES;
typedef struct tagZoneGetRoleRespactListRes        	*LPZONEGETROLERESPACTLISTRES;

struct tagZoneChgRolePosReq;
typedef struct tagZoneChgRolePosReq                	ZONECHGROLEPOSREQ;
typedef struct tagZoneChgRolePosReq                	*LPZONECHGROLEPOSREQ;

struct tagZoneChgRolePosRes;
typedef struct tagZoneChgRolePosRes                	ZONECHGROLEPOSRES;
typedef struct tagZoneChgRolePosRes                	*LPZONECHGROLEPOSRES;

struct tagZoneGetRolePetInfoReq;
typedef struct tagZoneGetRolePetInfoReq            	ZONEGETROLEPETINFOREQ;
typedef struct tagZoneGetRolePetInfoReq            	*LPZONEGETROLEPETINFOREQ;

struct tagZoneGetRolePetInfoRes;
typedef struct tagZoneGetRolePetInfoRes            	ZONEGETROLEPETINFORES;
typedef struct tagZoneGetRolePetInfoRes            	*LPZONEGETROLEPETINFORES;

struct tagZoneSetRolePetInfoReq;
typedef struct tagZoneSetRolePetInfoReq            	ZONESETROLEPETINFOREQ;
typedef struct tagZoneSetRolePetInfoReq            	*LPZONESETROLEPETINFOREQ;

struct tagZoneSetRolePetInfoRes;
typedef struct tagZoneSetRolePetInfoRes            	ZONESETROLEPETINFORES;
typedef struct tagZoneSetRolePetInfoRes            	*LPZONESETROLEPETINFORES;

struct tagZoneGetRoleRideInfoReq;
typedef struct tagZoneGetRoleRideInfoReq           	ZONEGETROLERIDEINFOREQ;
typedef struct tagZoneGetRoleRideInfoReq           	*LPZONEGETROLERIDEINFOREQ;

struct tagZoneGetRoleRideInfoRes;
typedef struct tagZoneGetRoleRideInfoRes           	ZONEGETROLERIDEINFORES;
typedef struct tagZoneGetRoleRideInfoRes           	*LPZONEGETROLERIDEINFORES;

struct tagZoneSetRoleRideInfoReq;
typedef struct tagZoneSetRoleRideInfoReq           	ZONESETROLERIDEINFOREQ;
typedef struct tagZoneSetRoleRideInfoReq           	*LPZONESETROLERIDEINFOREQ;

struct tagZoneSetRoleRideInfoRes;
typedef struct tagZoneSetRoleRideInfoRes           	ZONESETROLERIDEINFORES;
typedef struct tagZoneSetRoleRideInfoRes           	*LPZONESETROLERIDEINFORES;

struct tagGetRoleQiYueListReq;
typedef struct tagGetRoleQiYueListReq              	GETROLEQIYUELISTREQ;
typedef struct tagGetRoleQiYueListReq              	*LPGETROLEQIYUELISTREQ;

struct tagGetRoleQiYueListRes;
typedef struct tagGetRoleQiYueListRes              	GETROLEQIYUELISTRES;
typedef struct tagGetRoleQiYueListRes              	*LPGETROLEQIYUELISTRES;

struct tagSetRoleQiYueReq;
typedef struct tagSetRoleQiYueReq                  	SETROLEQIYUEREQ;
typedef struct tagSetRoleQiYueReq                  	*LPSETROLEQIYUEREQ;

struct tagSetRoleQiYueRes;
typedef struct tagSetRoleQiYueRes                  	SETROLEQIYUERES;
typedef struct tagSetRoleQiYueRes                  	*LPSETROLEQIYUERES;

struct tagAddRoleQiYueReq;
typedef struct tagAddRoleQiYueReq                  	ADDROLEQIYUEREQ;
typedef struct tagAddRoleQiYueReq                  	*LPADDROLEQIYUEREQ;

struct tagAddRoleQiYueRes;
typedef struct tagAddRoleQiYueRes                  	ADDROLEQIYUERES;
typedef struct tagAddRoleQiYueRes                  	*LPADDROLEQIYUERES;

struct tagDelRoleQiYueReq;
typedef struct tagDelRoleQiYueReq                  	DELROLEQIYUEREQ;
typedef struct tagDelRoleQiYueReq                  	*LPDELROLEQIYUEREQ;

struct tagDelRoleQiYueRes;
typedef struct tagDelRoleQiYueRes                  	DELROLEQIYUERES;
typedef struct tagDelRoleQiYueRes                  	*LPDELROLEQIYUERES;

union tagSSCsCmd;
typedef union  tagSSCsCmd                          	SSCSCMD;
typedef union  tagSSCsCmd                          	*LPSSCSCMD;

struct tagSSZoneCtrl;
typedef struct tagSSZoneCtrl                       	SSZONECTRL;
typedef struct tagSSZoneCtrl                       	*LPSSZONECTRL;

struct tagSSCsCtrl;
typedef struct tagSSCsCtrl                         	SSCSCTRL;
typedef struct tagSSCsCtrl                         	*LPSSCSCTRL;

struct tagSSAasReq;
typedef struct tagSSAasReq                         	SSAASREQ;
typedef struct tagSSAasReq                         	*LPSSAASREQ;

struct tagSSAasRes;
typedef struct tagSSAasRes                         	SSAASRES;
typedef struct tagSSAasRes                         	*LPSSAASRES;

struct tagSSUpdateAccountRep;
typedef struct tagSSUpdateAccountRep               	SSUPDATEACCOUNTREP;
typedef struct tagSSUpdateAccountRep               	*LPSSUPDATEACCOUNTREP;

struct tagSSCashBillReq;
typedef struct tagSSCashBillReq                    	SSCASHBILLREQ;
typedef struct tagSSCashBillReq                    	*LPSSCASHBILLREQ;

struct tagSSCashBillRes;
typedef struct tagSSCashBillRes                    	SSCASHBILLRES;
typedef struct tagSSCashBillRes                    	*LPSSCASHBILLRES;

struct tagSSQueryBillReq;
typedef struct tagSSQueryBillReq                   	SSQUERYBILLREQ;
typedef struct tagSSQueryBillReq                   	*LPSSQUERYBILLREQ;

struct tagSSQueryBillRes;
typedef struct tagSSQueryBillRes                   	SSQUERYBILLRES;
typedef struct tagSSQueryBillRes                   	*LPSSQUERYBILLRES;

union tagSSPkgBody;
typedef union  tagSSPkgBody                        	SSPKGBODY;
typedef union  tagSSPkgBody                        	*LPSSPKGBODY;

struct tagSSPkg;
typedef struct tagSSPkg                            	SSPKG;
typedef struct tagSSPkg                            	*LPSSPKG;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagTIPInfo
{
    short family;                         
    unsigned short port;                           
    tdr_ip_t ip;                             
};

union tagTFrameHeadData
{
    TIPINFO IPInfo;                          	/* TFRAMEHEAD_EXTRA_IP,   */
};

struct tagTFrameAuthJC
{
    int Uin;                            
    int UinFlag;                        
    char BirthDay[BIRTHDAY_LEN];         
    int AccSilenceEnd;                   	/*  Ver.111  */
};

union tagTFrameAuthData
{
    TFRAMEAUTHJC AuthJC;                          	/* AUTH_JC,   */
};

struct tagTFrameCmdStart
{
    int AuthType;                        	/*    Bind Macrosgroup:AUTH,*/
    TFRAMEAUTHDATA AuthData;                       
};

struct tagTFrameCmdStop
{
    int Reason;                         
};

struct tagTFrameIdent
{
    int ID;                             
    int ConnIdx;                        
};

struct tagTFrameCmdInProc
{
    char Flag;                            	/*    Bind Macrosgroup:BROADCAST_FLAG,*/
    char NoEnc;                          
    short Count;                          
    TFRAMEIDENT Idents[TFRAMEHEAD_MAX_BATCH_IDENT];
};

struct tagTFrameCmdRelay
{
    int Uin;                            
    int RelayType;                      
    TFRAMEIDENT Old;                            
    TFRAMEIDENT New;                            
};

struct tagTFrameCmdSetRouting
{
    char SerializerName[SERLIZER_NAME_LEN];
    int ID;                              	/*   连接在逻辑服务端上的索引,含义同head字段 */
};

union tagTRoutingOption
{
    TFRAMECMDSETROUTING CmdRouting;                      	/* TFRAMEHEAD_SET_ROUTING,   */
};

struct tagTFrameCmdNotify
{
    int Uin;                            
    char ConnKey[TFRAMEHEAD_CONNECTKEY_LEN];
    char Identity[IDENT_LEN];            
    unsigned char SetRouting;                     
    TROUTINGOPTION Routing;                        
};

union tagTFrameCmdData
{
    TFRAMECMDSTART Start;                           	/* TFRAMEHEAD_CMD_START,   */
    TFRAMECMDSTOP Stop;                            	/* TFRAMEHEAD_CMD_STOP,   */
    TFRAMECMDINPROC InProc;                          	/* TFRAMEHEAD_CMD_INPROC,   */
    TFRAMECMDRELAY Relay;                           	/* TFRAMEHEAD_CMD_RELAY,   */
    TFRAMECMDNOTIFY Notify;                          	/* TFRAMEHEAD_CMD_NOTIFY,   */
    TFRAMECMDSETROUTING SetRouting;                      	/* TFRAMEHEAD_CMD_SETROUTING,   */
};

struct tagTTimeVal
{
    int sec;                            
    int usec;                           
};

union tagTTimeStampData
{
    TTIMEVAL TimeVal;                         	/* TFRAMEHEAD_TIMESTAMP_TIMEVAL,   */
};

struct tagtframehead
{
    char Ver;                             	/*   版本信息,默认为零 */
    char Cmd;                            
    char ExtraType;                      
    char TimeStampType;                  
    int ID;                             
    int ConnIdx;                        
    TFRAMEHEADDATA ExtraInfo;                      
    TTIMESTAMPDATA TimeStamp;                      
    TFRAMECMDDATA CmdData;                        
};

struct tagSSPkgHead
{
    unsigned short Magic;                          
    unsigned short Cmd;                             	/*    Bind Macrosgroup:SSCmd,*/
    unsigned short HeadLen;                        
    unsigned short BodyLen;                        
    unsigned short Ver;                            
    unsigned short Res;                            
};

struct tagSSDirReport
{
    unsigned short WorldID;                        
    unsigned short PlayerNum;                      
    unsigned short PlayerMaxNum;                   
    unsigned short Port;                           
    int IP;                             
};

struct tagHourData
{
    unsigned short PlayerNum;                      
    unsigned short Hour;                           
};

struct tagRePortData
{
    unsigned short WorldID;                        
    unsigned short DataNum;                        
    HOURDATA DirHourData[MAX_DATA_NUM];      
};

struct tagSSRePortDataAll
{
    int time;                           
    int WorldNum;                       
    REPORTDATA RePort[REPORT_MAX_WORLD];       
};

struct tagSSWorldInfoHour
{
    unsigned short WorldID;                        
    unsigned int OnLineNum;                      
};

struct tagSSDirInfoHour
{
    int Time;                           
    int Hour;                           
    int WorldNum;                       
    SSWORLDINFOHOUR WorldInfoHour[MAX_WORLD_NUM];   
};

struct tagDirInfoDB
{
    int WorldID;                        
    int OnlineNum;                      
    unsigned int Time;                           
};

struct tagSSDirInfoDB
{
    int WorldNum;                       
    DIRINFODB DirInfo[MAX_WORLD_NUM];         
};

struct tagZoneChgRoleNameReq
{
    char OldRoleName[MAXROLENAME];        	/*   角色名 */
    char ChgRoleName[MAXROLENAME];        	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
    int Uin;                            
};

struct tagZoneChgRoleNameRes
{
    char ChgRoleName[MAXROLENAME];        	/*   更改后的角色名 */
};

struct tagZoneTestReq
{
    unsigned int Res;                            
};

struct tagZoneOutLineRes
{
    unsigned int Res;                            
};

struct tagZoneTestRes
{
    unsigned int Result;                         
};

struct tagZoneShutDownReq
{
    unsigned int Time;                           
};

struct tagZoneShutDownRes
{
    unsigned int Result;                         
};

struct tagZoneBlockPlayerReq
{
    char Type;                            	/*   0 封锁角色,1 解封锁角色 */
    unsigned int Time;                            	/*   封锁住的时间,以秒为单位 */
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
    char IsTemp;                          	/*   是否只是临时临时踢下线 */
    char Res[3];                         
};

struct tagZoneBlockPlayerRes
{
    char Type;                            	/*   0 封锁角色,1 解封锁角色 */
    char RoleName[MAXROLENAME];           	/*   角色名 */
};

struct tagZoneRoleInfo
{
    int Uin;                            
    tdr_ulonglong RoleID;                         
    char RoleName[ROLE_NAME_LEN];        
    char Gender;                         
    char Career;                         
    unsigned char Head;                           
    unsigned char Level;                          
    ROLEAVATARPROF AvatarProf;                     
    unsigned char Face;                           
};

struct tagZoneRoleBaseInfo
{
    int Uin;                            
    tdr_ulonglong RoleID;                         
    char RoleName[ROLE_NAME_LEN];        
    int BlockEnd;                       
    int SilenceEnd;                     
    unsigned int CreateTime;                     
    unsigned int LastLogin;                      
    unsigned int LastLogout;                     
    int Map;                            
    RESPOS Pos;                            
    char Gender;                         
    char Career;                         
    unsigned char Level;                          
    unsigned char Head;                           
    unsigned char Face;                           
    unsigned char Hair;                           
};

struct tagZoneRoleListReq
{
    int Uin;                            
    int RegionID;                        	/*  Ver.94  */
    int WorldID;                         	/*  Ver.94  */
};

struct tagSSRoleList
{
    tdr_ulonglong RoleID;                          	/*   角色唯一id */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    unsigned char IsDelete;                        	/*   是否逻辑删除 0--否 1--是 */
};

struct tagZoneRoleListRes
{
    int Uin;                            
    unsigned int RoleNum;                        
    SSROLELIST RoleList[ROLE_MAX_NUM];          	/*  Ver.94  */
};

struct tagZoneSilenceRoleReq
{
    unsigned int Time;                            	/*   禁言的时间,以秒为单位 */
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
    char IsTemp;                          	/*   是否只是临时禁言（帐号禁言） */
    char Res[3];                         
};

struct tagZoneSilenceRoleRes
{
    char RoleName[MAXROLENAME];           	/*   角色名 */
};

struct tagZoneGetRoleBaseInfoReq
{
    int Uin;                             	/*   角色登录账号 */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
};

struct tagZoneGetRoleBaseInfoRes
{
    int Result;                          	/*   0 成功  其他 异常 */
    ZONEROLEBASEINFO RoleBaseInfo;                   
};

struct tagZoneSetRoleBaseInfoReq
{
    ZONEROLEBASEINFO RoleBaseInfo;                   
};

struct tagZoneSetRoleBaseInfoRes
{
    int Result;                          	/*   0 成功  其他 异常 */
    char RoleName[MAXROLENAME];           	/*   角色名 */
};

struct tagZoneGetRoleDetailReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
};

struct tagZoneGetRoleDetailRes
{
    ROLEDETAIL RoleDetailInfo;                 
    char RoleName[MAXROLENAME];           	/*  Ver.93  */
    unsigned int MapID;                           	/*  Ver.93  */
    unsigned int X;                               	/*  Ver.93  */
    unsigned int Y;                               	/*  Ver.93  */
    unsigned char IsOnline;                        	/*  Ver.93 0--不在线 非0在线 */
    unsigned int Silence;                         	/*  Ver.93 禁言剩下的时间, 0表示没有禁言 */
    unsigned int Block;                           	/*  Ver.93 冻结角色剩下的时间, 0表示没有冻结 */
};

struct tagZoneSetRoleDetailReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
    ROLEDETAIL RoleDetailInfo;                 
    unsigned int MapID;                           	/*  Ver.93  */
    unsigned int X;                               	/*  Ver.93  */
    unsigned int Y;                               	/*  Ver.93  */
};

struct tagZoneSetRoleDetailRes
{
    char RoleName[MAXROLENAME];           	/*   角色名 */
};

struct tagZoneGetRoleSkillInfoReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
};

struct tagZoneGetRoleSkillInfoRes
{
    SKILLINFO RoleSkillInfo;                  
};

struct tagZoneSetRoleFairyReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
    int OpType;                          	/*    Bind Macrosgroup:RoleFairyOp,*/
    unsigned int FairyID;                        
    unsigned int FairyLV;                        
};

struct tagZoneSetRoleFairyRes
{
    int OpType;                          	/*    Bind Macrosgroup:RoleFairyOp,*/
    char RoleName[MAXROLENAME];           	/*   角色名 */
};

struct tagZoneSetRoleSkillInfoReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
    int Type;                            	/*    Bind Macrosgroup:RoleSkillOp,*/
    SKILLDATA ZoneSkillData;                  
};

struct tagZoneSetRoleSkillInfoRes
{
    char RoleName[MAXROLENAME];           	/*   角色名 */
};

struct tagZoneSetRoleDiathesisReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
    int OpType;                          	/*    Bind Macrosgroup:RoleDiathesisOp,*/
    DIATHESISDATA ZoneDiathesisData;              
};

struct tagZoneSetRoleDiathesisRes
{
    char RoleName[MAXROLENAME];           	/*   角色名 */
};

struct tagZoneGetRoleDiathesisReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
};

struct tagZoneGetRoleDiathesisRes
{
    DIATHESISINFO ZoneDiathesisInfo;              
};

struct tagZoneGetRoleItemListReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
};

struct tagZoneGetRoleItemListRes
{
    ROLEPACKAGE ZoneRolePackage;                 	/*   角色背包 */
    ROLEWEAR ZoneRoleWear;                    	/*   角色已穿戴的装备 */
};

struct tagZoneGetRoleTaskReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
};

struct tagZoneGetRoleTaskRes
{
    TASKINFO TaskInfo;                       
};

struct tagZoneDelRoleTaskReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
    unsigned int TaskID;                         
};

struct tagZoneDelRoleTaskRes
{
    char RoleName[MAXROLENAME];           	/*   角色名 */
};

struct tagZoneSetRoleItemListReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
    int PackType;                        	/*   背包类型 Bind Macrosgroup:LIST_TYPE,*/
    int OPType;                          	/*   操作方式 Bind Macrosgroup:RoleItemOp,*/
    ROLEGRID ZoneRoleGrid;                   
};

struct tagZoneSetRoleItemListRes
{
    char RoleName[MAXROLENAME];           	/*   角色名 */
};

struct tagZoneLoadScriptReq
{
    int Type;                            	/*    Bind Macrosgroup:LOADSCRIPT_TYPE,*/
    char Name[MAX_SCRIPT_NAME];          
};

struct tagZoneReLoadReq
{
    unsigned int Res;                            
};

struct tagZoneLoadScriptRes
{
    int Result;                         
};

struct tagZoneReLoadRes
{
    int Result;                         
};

union tagSSCtrlCmd
{
    ZONETESTREQ TestReq;                         	/* TEST_REQ,   */
    ZONETESTRES TestRes;                         	/* TEST_RES,   */
    ZONESHUTDOWNREQ ShutDownReq;                     	/* SHUTDOWN_REQ,   */
    ZONESHUTDOWNRES ShutDownRes;                     	/* SHUTDOWN_RES,   */
    ZONELOADSCRIPTREQ LoadScriptReq;                   	/* LOADSCRIPT_REQ,   */
    ZONELOADSCRIPTRES LoadScriptRes;                   	/* LOADSCRIPT_RES,   */
    ZONERELOADREQ ReLoadReq;                       	/* RELOAD_REQ,   */
    ZONERELOADRES ReLoadRes;                       	/* RELOAD_RES,   */
};

struct tagAsynReq
{
    int Cmd;                            
    int ConnIdx;                        
    TIPINFO IPInfo;                         
    int DataLen;                        
    unsigned char Data[CS_ASYN_DATA];             
};

struct tagAsynRes
{
    ASYNREQ AsynReq;                        
    int Result;                         
};

struct tagInformerAccount
{
    int UinFlag;                         	/*   帐号标记，例如vip用户等 */
    char Pass9Account[INFORMER_ACCOUNT_LOGIN_NAME_LEN];
    char PasswdHash[16];                  	/*   用户密码的二次hash */
    char BirthDay[INFORMER_BIRTHDAY_LEN]; 	/*   生日 */
    char Gender;                          	/*  Ver.125 性别 */
    char RegisterTs[REGISTER_TIME_LEN];   	/*  Ver.125 注册时间 e.g. 201008181302 */
};

struct tagSSGetAccountReq
{
    char LoginName[INFORMER_ACCOUNT_LOGIN_NAME_LEN];
    unsigned short ExtraDataLen;                   
    unsigned char Res[2];                         
    unsigned char ExtraData[4096];                
};

struct tagSSGetAccountRes
{
    unsigned char Found;                          
    unsigned char Res1[3];                        
    INFORMERACCOUNT Account;                        
    unsigned short ExtraDataLen;                   
    unsigned char Res2[2];                        
    unsigned char ExtraData[4096];                
};

struct tagAccGetInfoFromUinReq
{
    unsigned int Uin;                            
};

struct tagAccGetIDFromRoleNameExReq
{
    int Index;                          
    char RoleNamePattern[ACC_PATTERN_LEN];
};

struct tagAccGetIDFromLoginNameExReq
{
    int Index;                          
    char LoginNamePattern[ACC_PATTERN_LEN];
};

struct tagSSAccInfo
{
    int Uin;                             	/*   帐号内部标识 */
    int UinFlag;                         	/*   帐号的属性标识，按位或，请参见proto_comm.h中的enum tagUIN_FLAG  */
    char LoginName[INFORMER_ACCOUNT_LOGIN_NAME_LEN]; 	/*   帐号登录名 */
    char BirthDay[INFORMER_BIRTHDAY_LEN]; 	/*   帐号生日 */
    int SilenceEndTime;                  	/*   time(NULL)相对的禁言到期时间 */
    int FreezeEndTime;                   	/*   time(NULL)相对的 */
};

struct tagAccGetInfoRes
{
    unsigned char Found;                          
    unsigned char Res[3];                         
    SSACCINFO AccountInfo;                    
};

struct tagAccIDInfo
{
    int Uin;                             	/*   帐号内部标识 */
    char LoginName[INFORMER_ACCOUNT_LOGIN_NAME_LEN]; 	/*   帐号登录名 */
};

struct tagAccGetIDRes
{
    unsigned int ResNum;                         
    ACCIDINFO AccountIDs[ACC_MAX_RES];        
};

struct tagAccSetSilenceReq
{
    ACCIDINFO AccIDInfo;                      
    char Enable;                         
    char Res[3];                         
    int SilenceTime;                    
};

struct tagAccSetSilenceRes
{
    char Succeeded;                      
    char Res[3];                         
};

struct tagAccSetFreezeReq
{
    ACCIDINFO AccIDInfo;                      
    char Enable;                         
    char Res[3];                         
    int FreezeTime;                     
};

struct tagAccSetFreezeRes
{
    char Succeeded;                      
    char Res[3];                         
};

struct tagAccSetRoleNameReq
{
    tdr_ulonglong RoleID;                         
    char RoleName[ROLE_NAME_LEN];        
};

struct tagAccSetRoleNameRes
{
    char Succeeded;                      
    char Res[3];                         
};

struct tagAccGetRoleListReq
{
    int Uin;                            
    int Index;                          
};

struct tagSSAccRoleLite
{
    tdr_ulonglong RoleID;                         
    char RoleName[ROLE_NAME_LEN];        
    unsigned char RegionID;                       
    char Res1[3];                        
    unsigned short ServerID;                       
    char Res2[2];                        
    int DelTime;                        
};

struct tagAccGetRoleListRes
{
    int ResNum;                         
    SSACCROLELITE RoleArray[ROLE_MAX_RES];        
};

struct tagZoneConnCtx
{
    int ConnIdx;                        
    TIPINFO IPInfo;                         
};

struct tagZoneGetMailListReq
{
    char RoleName[ROLE_NAME_LEN];        
};

struct tagZoneGetMailListRes
{
    int ResNum;                         
    MAILHEAD MailHeads[MAIL_MAX_NUM];        
};

struct tagZoneGetMailReq
{
    char RoleName[ROLE_NAME_LEN];        
    tdr_ulonglong MailID;                         
};

struct tagZoneGetMailRes
{
    unsigned char Found;                          
    char Res[3];                         
    MAIL MailData;                       
};

struct tagZoneDelMailReq
{
    char RoleName[ROLE_NAME_LEN];        
    tdr_ulonglong MailID;                         
};

struct tagZoneDelMailRes
{
    char Succeeded;                      
    char Res[3];                         
};

struct tagZoneCtlDelMailReq
{
    ZONEDELMAILREQ Core;                           
    ZONECONNCTX Extra;                          
};

struct tagZoneCtlDelMailRes
{
    ZONEDELMAILRES Core;                           
    ZONEDELMAILREQ ReqCopy;                        
    ZONECONNCTX Extra;                          
};

struct tagZoneSendMailReq
{
    char To[ROLE_NAME_LEN_SAVE];          	/*   收件人 */
    char Send[ROLE_NAME_LEN_SAVE];        	/*   发件人 */
    char Title[NAME_LEN];                 	/*   标题 */
    char Text[SHORT_DESC_LEN];            	/*   正文 */
    unsigned char ItemNum;                         	/*   邮寄的物品数量 */
    unsigned char Res;                            
    ROLEGRID Items[MAIL_MAX_ITEM];            	/*   邮寄的物品ID */
    unsigned int Money;                           	/*   邮寄的钱 */
};

struct tagZoneSendMailRes
{
    char Succeeded;                      
    char Res[3];                         
    tdr_ulonglong MailID;                         
};

struct tagZoneCtlSendMailReq
{
    ZONESENDMAILREQ Core;                           
    ZONECONNCTX Extra;                          
};

struct tagZoneCtlSendMailRes
{
    ZONESENDMAILRES Core;                           
    ZONECONNCTX Extra;                          
};

struct tagZoneBlockAccountReq
{
    int Uin;                            
    int BlockTime;                      
};

struct tagZoneBlockAccountRes
{
    char Succeeded;                      
    char Res[3];                         
};

struct tagZoneSilenceAccountReq
{
    int Uin;                            
    char Enable;                         
    char Res[3];                         
    int SilenceTime;                    
};

struct tagZoneSilenceAccountRes
{
    char Succeeded;                      
    char Res[3];                         
};

struct tagZoneCtlBlockAccountReq
{
    ZONEBLOCKACCOUNTREQ Core;                           
    ZONECONNCTX Extra;                          
};

struct tagZoneCtlBlockAccountRes
{
    ZONEBLOCKACCOUNTRES Core;                           
    ZONECONNCTX Extra;                          
};

struct tagZoneCtlSilenceAccountReq
{
    ZONESILENCEACCOUNTREQ Core;                           
    ZONECONNCTX Extra;                          
};

struct tagZoneCtlSilenceAccountRes
{
    ZONESILENCEACCOUNTRES Core;                           
    ZONECONNCTX Extra;                          
};

struct tagSSRestoreRoleReq
{
    int Uin;                            
    tdr_ulonglong RoleID;                         
};

struct tagSSRestoreRoleRes
{
    char Succeeded;                      
    char Res[3];                         
};

struct tagSSRoleStoragePath
{
    char RegionID;                       
    char Res1[3];                        
    short WorldID;                        
    char Res2[2];                        
    tdr_ulonglong RoleID;                         
    char RoleName[ROLE_NAME_LEN];        
};

struct tagZoneCopyRoleReq
{
    int SrcUin;                         
    tdr_ulonglong SrcRoleID;                      
    char SrcRoleName[ROLE_NAME_LEN];      	/*  Ver.137  */
    int DstUin;                         
    tdr_ulonglong DstRoleID;                      
    char DstRoleName[ROLE_NAME_LEN];     
};

struct tagZoneCopyRoleRes
{
    char Succeeded;                      
    char Res[3];                         
};

struct tagZoneGetBulletinListReq
{
    int Res;                            
};

struct tagSSBulletin
{
    BULLETINENTRY Core;                           
    int ActiveTime;                     
};

struct tagZoneGetBulletinListRes
{
    char Num;                            
    char Res[3];                         
    SSBULLETIN BulletinArray[MAX_BULLETIN_NUM];
};

struct tagZoneAddBulletinReq
{
    SSBULLETIN Bulletin;                       
};

struct tagZoneAddBulletinRes
{
    char Succeeded;                      
    char Res[3];                         
};

struct tagZoneDelBulletinReq
{
    int ID;                             
};

struct tagZoneDelBulletinRes
{
    char Succeeded;                      
    char Res[3];                         
};

struct tagZoneCtlGetBulletinListReq
{
    ZONEGETBULLETINLISTREQ Core;                           
    ZONECONNCTX Extra;                          
};

struct tagZoneCtlGetBulletinListRes
{
    ZONEGETBULLETINLISTRES Core;                           
    ZONECONNCTX Extra;                          
};

struct tagZoneCtlAddBulletinReq
{
    ZONEADDBULLETINREQ Core;                           
    ZONECONNCTX Extra;                          
};

struct tagZoneCtlAddBulletinRes
{
    ZONEADDBULLETINRES Core;                           
    ZONECONNCTX Extra;                          
};

struct tagZoneCtlDelBulletinReq
{
    ZONEDELBULLETINREQ Core;                           
    ZONECONNCTX Extra;                          
};

struct tagZoneCtlDelBulletinRes
{
    ZONEDELBULLETINRES Core;                           
    ZONECONNCTX Extra;                          
};

struct tagSSItemIdent
{
    int DefID;                          
    unsigned short Num;                            
};

struct tagZoneCreateItemReq
{
    unsigned char Num;                            
    char Res[3];                         
    SSITEMIDENT ItemIdents[ROLE_GRID_MAX_RES];  
};

struct tagZoneCreateItemRes
{
    unsigned char Num;                            
    char Res[3];                         
    ROLEGRID RoleGrids[ROLE_GRID_MAX_RES];   
};

struct tagZoneUpdateRoleListCacheReq
{
    int Uin;                            
};

struct tagZoneAddRoleDesignationReq
{
    char RoleName[ROLE_NAME_LEN];        
    tdr_ulonglong RoleID;                         
    int Uin;                            
    int DesignationID;                  
};

struct tagZoneAddRoleDesignationRes
{
    char Succeeded;                      
    char Res[3];                         
};

struct tagZoneDelRoleDesignationReq
{
    char RoleName[ROLE_NAME_LEN];        
    tdr_ulonglong RoleID;                         
    int Uin;                            
    int DesignationID;                  
};

struct tagZoneDelRoleDesignationRes
{
    char Succeeded;                      
    char Res[3];                         
};

struct tagZoneGetRoleDesignationListReq
{
    char RoleName[ROLE_NAME_LEN];        
    tdr_ulonglong RoleID;                         
    int Uin;                            
};

struct tagZoneGetRoleDesignationListRes
{
    char Succeeded;                      
    char Res[3];                         
    ROLEDESIGNATIONS Designations;                   
};

struct tagZoneSetRoleRespactReq
{
    char RoleName[ROLE_NAME_LEN];        
    tdr_ulonglong RoleID;                         
    int Uin;                            
    int RespactPartyID;                 
    int RespactValue;                   
};

struct tagZoneSetRoleRespactRes
{
    char Succeeded;                      
    char Res[3];                         
};

struct tagZoneDelRoleRespactReq
{
    char RoleName[ROLE_NAME_LEN];        
    tdr_ulonglong RoleID;                         
    int Uin;                            
    int RespactPartyID;                 
};

struct tagZoneDelRoleRespactRes
{
    char Succeeded;                      
    char Res[3];                         
};

struct tagZoneGetRoleRespactListReq
{
    char RoleName[ROLE_NAME_LEN];        
    tdr_ulonglong RoleID;                         
    int Uin;                            
};

struct tagZoneGetRoleRespactListRes
{
    char Succeeded;                      
    char Res[3];                         
    RESPACTINFO RespactInfo;                    
};

struct tagZoneChgRolePosReq
{
    char RoleName[MAXROLENAME];           	/*   角色名 */
    int Uin;                             	/*   角色Uin */
    tdr_ulonglong RoleID;                          	/*   角色ID */
    int Map;                             	/*   地图ID */
    int X;                               	/*   坐标 */
    int Y;                              
};

struct tagZoneChgRolePosRes
{
    char RoleName[MAXROLENAME];           	/*   角色名 */
};

struct tagZoneGetRolePetInfoReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
};

struct tagZoneGetRolePetInfoRes
{
    PETPACKAGE RolePetInfo;                    
};

struct tagZoneSetRolePetInfoReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
    int Type;                            	/*    Bind Macrosgroup:RolePetOp,*/
    ROLEPET ZoneRolePetData;                
};

struct tagZoneSetRolePetInfoRes
{
    char RoleName[MAXROLENAME];           	/*   角色名 */
};

struct tagZoneGetRoleRideInfoReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
};

struct tagZoneGetRoleRideInfoRes
{
    ROLERIDELIST RoleRideInfo;                   
};

struct tagZoneSetRoleRideInfoReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
    int Type;                            	/*    Bind Macrosgroup:RoleRideOp,*/
    RIDEGRID ZoneRoleRideData;               
};

struct tagZoneSetRoleRideInfoRes
{
    char RoleName[MAXROLENAME];           	/*   角色名 */
};

struct tagGetRoleQiYueListReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
};

struct tagGetRoleQiYueListRes
{
    QIYUEINFO QiYueInfo;                       	/*   契约列表 */
};

struct tagSetRoleQiYueReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
    unsigned int QiYueID;                         	/*   增加的契约id */
};

struct tagSetRoleQiYueRes
{
    unsigned int Result;                          	/*   0成功 非0失败 */
    char RoleName[MAXROLENAME];           	/*   角色名 */
};

struct tagAddRoleQiYueReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
    unsigned int QiYueID;                         	/*   增加的契约id */
};

struct tagAddRoleQiYueRes
{
    unsigned int Result;                          	/*   0成功 非0失败 */
    char RoleName[MAXROLENAME];           	/*   角色名 */
};

struct tagDelRoleQiYueReq
{
    int Uin;                             	/*   角色Uin */
    char RoleName[MAXROLENAME];           	/*   角色名 */
    tdr_ulonglong RoleID;                          	/*   角色ID */
    unsigned int QiYueID;                         	/*   增加的契约id */
};

struct tagDelRoleQiYueRes
{
    unsigned int Result;                          	/*   0成功 非0失败 */
    char RoleName[MAXROLENAME];           	/*   角色名 */
};

union tagSSCsCmd
{
    ZONEBLOCKPLAYERREQ BlockPlayerReq;                  	/* BLOCKPLAYER_REQ,   */
    ZONEBLOCKPLAYERRES BlockPlayerRes;                  	/* BLOCKPLAYER_RES,   */
    ZONEROLELISTREQ RoleListReq;                     	/* ROLE_LIST_REQ,   */
    ZONEROLELISTRES RoleListRes;                     	/* ROLE_LIST_RES,   */
    ZONESILENCEROLEREQ SilenceRoleReq;                  	/* SILENCE_ROLE_REQ,   */
    ZONESILENCEROLERES SilenceRoleRes;                  	/* SILENCE_ROLE_RES,   */
    ASYNREQ ZoneReq;                         	/* ZONE_REQ,   */
    ASYNRES ZoneRes;                         	/* ZONE_RES,   */
    ZONEGETROLEDETAILREQ GetRoleDetailReq;                	/* GET_ROLE_DETAIL_REQ,   */
    ZONEGETROLEDETAILRES GetRoleDetailRes;                	/* GET_ROLE_DETAIL_RES,   */
    ZONESETROLEDETAILREQ SetRoleDetailReq;                	/* SET_ROLE_DETAIL_REQ,   */
    ZONESETROLEDETAILRES SetRoleDetailRes;                	/* SET_ROLE_DETAIL_RES,   */
    ZONEGETROLESKILLINFOREQ GetRoleSkillInfoReq;             	/* GET_ROLE_SKILLINFO_REQ,   */
    ZONEGETROLESKILLINFORES GetRoleSkillInfoRes;             	/* GET_ROLE_SKILLINFO_RES,   */
    ZONESETROLESKILLINFOREQ SetRoleSkillInfoReq;             	/* SET_ROLE_SKILLINFO_REQ,   */
    ZONESETROLESKILLINFORES SetRoleSkillInfoRes;             	/* SET_ROLE_SKILLINFO_RES,   */
    ZONEGETROLEITEMLISTREQ GetRoleItemListReq;              	/* GET_ROLE_ITEMLIST_REQ,   */
    ZONEGETROLEITEMLISTRES GetRoleItemListRes;              	/* GET_ROLE_ITEMLIST_RES,   */
    ZONESETROLEITEMLISTREQ SetRoleItemListReq;              	/* SET_ROLE_ITEMLIST_REQ,   */
    ZONESETROLEITEMLISTRES SetRoleItemListRes;              	/* SET_ROLE_ITEMLIST_RES,   */
    ZONEGETROLEDIATHESISREQ GetRoleDiathesisReq;             	/* GET_ROLE_DIATHESIS_REQ,   */
    ZONEGETROLEDIATHESISRES GetRoleDiathesisRes;             	/* GET_ROLE_DIATHESIS_RES,   */
    ZONESETROLEDIATHESISREQ SetRoleDiathesisReq;             	/* SET_ROLE_DIATHESIS_REQ,   */
    ZONESETROLEDIATHESISRES SetRoleDiathesisRes;             	/* SET_ROLE_DIATHESIS_RES,   */
    ZONEGETROLETASKREQ GetRoleTaskReq;                  	/* GET_ROLE_TASK_REQ, Ver.94  */
    ZONEGETROLETASKRES GetRoleTaskRes;                  	/* GET_ROLE_TASK_RES, Ver.94  */
    ZONEGETMAILLISTREQ GetRoleMailListReq;              	/* GET_ROLE_MAIL_LIST_REQ, Ver.94  */
    ZONEGETMAILLISTRES GetRoleMailListRes;              	/* GET_ROLE_MAIL_LIST_RES, Ver.94  */
    ZONEGETMAILREQ GetRoleMailReq;                  	/* GET_ROLE_MAIL_REQ, Ver.94  */
    ZONEGETMAILRES GetRoleMailRes;                  	/* GET_ROLE_MAIL_RES, Ver.94  */
    SSRESTOREROLEREQ RestoreRoleReq;                  	/* RESTORE_ROLE_REQ, Ver.94  */
    SSRESTOREROLERES RestoreRoleRes;                  	/* RESTORE_ROLE_RES, Ver.94  */
    ZONEDELMAILREQ DelMailReq;                      	/* DEL_ROLE_MAIL_REQ, Ver.94  */
    ZONEDELMAILRES DelMailRes;                      	/* DEL_ROLE_MAIL_RES, Ver.94  */
    ZONESENDMAILREQ SendMailReq;                     	/* SEND_MAIL_REQ, Ver.94  */
    ZONESENDMAILRES SendMailRes;                     	/* SEND_MAIL_RES, Ver.94  */
    ACCGETINFOFROMUINREQ GetAccInfoFromUinReq;            	/* GET_ACCOUNT_INFO_FROM_UIN_REQ, Ver.94  */
    ACCGETIDFROMROLENAMEEXREQ GetAccIDFromRoleNameExReq;       	/* GET_ACCOUNT_ID_FROM_ROLENAME_EX_REQ, Ver.94  */
    ACCGETIDFROMLOGINNAMEEXREQ GetAccIDFromLoginNameExReq;      	/* GET_ACCOUNT_ID_FROM_LOGINNAME_EX_REQ, Ver.94  */
    ACCGETINFORES GetAccInfoRes;                   	/* GET_ACCOUNT_INFO_RES, Ver.94  */
    ACCGETIDRES GetAccIDRes;                     	/* GET_ACCOUNT_ID_RES, Ver.94  */
    ACCGETROLELISTREQ GetAccRoleListReq;               	/* GET_ACCOUNT_ROLELIST_REQ, Ver.94  */
    ACCGETROLELISTRES GetAccRoleListRes;               	/* GET_ACCOUNT_ROLELIST_RES, Ver.94  */
    ACCSETSILENCEREQ SetAccSilenceReq;                	/* SET_ACCOUNT_SILENCE_REQ, Ver.94  */
    ACCSETSILENCERES SetAccSilenceRes;                	/* SET_ACCOUNT_SILENCE_RES, Ver.94  */
    ACCSETFREEZEREQ SetAccFreezeReq;                 	/* SET_ACCOUNT_FREEZE_REQ, Ver.94  */
    ACCSETFREEZERES SetAccFreezeRes;                 	/* SET_ACCOUNT_FREEZE_RES, Ver.94  */
    ZONEDELROLETASKREQ DelRoleTaskReq;                  	/* DEL_ROLE_TASK_REQ, Ver.94  */
    ZONEDELROLETASKRES DelRoleTaskRes;                  	/* DEL_ROLE_TASK_RES, Ver.94  */
    ZONECTLDELMAILREQ CtlDelMailReq;                   	/* CTL_DEL_ROLE_MAIL_REQ, Ver.94  */
    ZONECTLDELMAILRES CtlDelMailRes;                   	/* CTL_DEL_ROLE_MAIL_RES, Ver.94  */
    ZONECTLSENDMAILREQ CtlSendMailReq;                  	/* CTL_SEND_MAIL_REQ, Ver.94  */
    ZONECTLSENDMAILRES CtlSendMailRes;                  	/* CTL_SEND_MAIL_RES, Ver.94  */
    ZONECHGROLENAMEREQ ChgRoleNameReq;                  	/* CHG_ROLE_NAME_REQ, Ver.94  */
    ZONECHGROLENAMERES ChgRoleNameRes;                  	/* CHG_ROLE_NAME_RES, Ver.94  */
    ZONEBLOCKACCOUNTREQ BlockAccountReq;                 	/* BLOCK_ACCOUNT_REQ, Ver.94  */
    ZONEBLOCKACCOUNTRES BlockAccountRes;                 	/* BLOCK_ACCOUNT_RES, Ver.94  */
    ZONESILENCEACCOUNTREQ SilenceAccountReq;               	/* SILENCE_ACCOUNT_REQ, Ver.94  */
    ZONESILENCEACCOUNTRES SilenceAccountRes;               	/* SILENCE_ACCOUNT_RES, Ver.94  */
    ZONECTLBLOCKACCOUNTREQ CtlBlockAccountReq;              	/* CTL_BLOCK_ACCOUNT_REQ, Ver.94  */
    ZONECTLBLOCKACCOUNTRES CtlBlockAccountRes;              	/* CTL_BLOCK_ACCOUNT_RES, Ver.94  */
    ZONECTLSILENCEACCOUNTREQ CtlSilenceAccountReq;            	/* CTL_SILENCE_ACCOUNT_REQ, Ver.94  */
    ZONECTLSILENCEACCOUNTRES CtlSilenceAccountRes;            	/* CTL_SILENCE_ACCOUNT_RES, Ver.94  */
    ZONECOPYROLEREQ CopyRoleReq;                     	/* COPY_ROLE_REQ, Ver.94  */
    ZONECOPYROLERES CopyRoleRes;                     	/* COPY_ROLE_RES, Ver.94  */
    ZONEGETBULLETINLISTREQ GetBulletinListReq;              	/* GET_BULLETIN_LIST_REQ, Ver.112  */
    ZONEGETBULLETINLISTRES GetBulletinListRes;              	/* GET_BULLETIN_LIST_RES, Ver.112  */
    ZONEADDBULLETINREQ AddBulletinReq;                  	/* ADD_BULLETIN_REQ, Ver.112  */
    ZONEADDBULLETINRES AddBulletinRes;                  	/* ADD_BULLETIN_RES, Ver.112  */
    ZONEDELBULLETINREQ DelBulletinReq;                  	/* DEL_BULLETIN_REQ, Ver.112  */
    ZONEDELBULLETINRES DelBulletinRes;                  	/* DEL_BULLETIN_RES, Ver.112  */
    ZONECTLGETBULLETINLISTREQ CtlGetBulletinListReq;           	/* CTL_GET_BULLETIN_LIST_REQ, Ver.112  */
    ZONECTLGETBULLETINLISTRES CtlGetBulletinListRes;           	/* CTL_GET_BULLETIN_LIST_RES, Ver.112  */
    ZONECTLADDBULLETINREQ CtlAddBulletinReq;               	/* CTL_ADD_BULLETIN_REQ, Ver.112  */
    ZONECTLADDBULLETINRES CtlAddBulletinRes;               	/* CTL_ADD_BULLETIN_RES, Ver.112  */
    ZONECTLDELBULLETINREQ CtlDelBulletinReq;               	/* CTL_DEL_BULLETIN_REQ, Ver.112  */
    ZONECTLDELBULLETINRES CtlDelBulletinRes;               	/* CTL_DEL_BULLETIN_RES, Ver.112  */
    ACCSETROLENAMEREQ SetAccRoleNameReq;               	/* SET_ACCOUNT_ROLENAME_REQ, Ver.112  */
    ACCSETROLENAMERES SetAccRoleNameRes;               	/* SET_ACCOUNT_ROLENAME_RES, Ver.112  */
    ZONECREATEITEMREQ CreateRoleItemReq;               	/* CREATE_ITEM_REQ, Ver.112  */
    ZONECREATEITEMRES CreateRoleItemRes;               	/* CREATE_ITEM_RES, Ver.112  */
    ZONEUPDATEROLELISTCACHEREQ UpdateRoleListCacheReq;          	/* UPDATE_ROLELIST_CACHE_REQ, Ver.112  */
    ZONECHGROLEPOSREQ ChgRolePosReq;                   	/* CHG_ROLE_POS_REQ, Ver.112  */
    ZONECHGROLEPOSRES ChgRolePosRes;                   	/* CHG_ROLE_POS_RES, Ver.112  */
    ZONEGETROLERIDEINFOREQ GetRoleRideInfoReq;              	/* GET_ROLE_RIDE_REQ, Ver.128  */
    ZONEGETROLERIDEINFORES GetRoleRideInfoRes;              	/* GET_ROLE_RIDE_RES, Ver.128  */
    ZONESETROLERIDEINFOREQ SetRoleRideInfoReq;              	/* SET_ROLE_RIDE_REQ, Ver.128  */
    ZONESETROLERIDEINFORES SetRoleRideInfoRes;              	/* SET_ROLE_RIDE_RES, Ver.128  */
    GETROLEQIYUELISTREQ GetRoleQiYueListReq;             	/* GET_ROLE_QIYUELIST_REQ, Ver.134  */
    GETROLEQIYUELISTRES GetRoleQiYueListRes;             	/* GET_ROLE_QIYUELIST_RES, Ver.134  */
    SETROLEQIYUEREQ SetRoleQiYueReq;                 	/* SET_ROLE_QIYUE_REQ, Ver.134  */
    SETROLEQIYUERES SetRoleQiYueRes;                 	/* SET_ROLE_QIYUE_RES, Ver.134  */
    ADDROLEQIYUEREQ AddRoleQiYueReq;                 	/* ADD_ROLE_QIYUE_REQ, Ver.134  */
    ADDROLEQIYUERES AddRoleQiYueRes;                 	/* ADD_ROLE_QIYUE_RES, Ver.134  */
    DELROLEQIYUEREQ DelRoleQiYueReq;                 	/* DEL_ROLE_QIYUE_REQ, Ver.134  */
    DELROLEQIYUERES DelRoleQiYueRes;                 	/* DEL_ROLE_QIYUE_RES, Ver.134  */
    ZONESETROLEFAIRYREQ SetRoleFairyReq;                 	/* MODIFY_ROLE_FAIRY_REQ, Ver.135  */
    ZONESETROLEFAIRYRES SetRoleFairyRes;                 	/* MODIFY_ROLE_FAIRY_RES, Ver.135  */
    ZONEGETROLEPETINFOREQ GetRolePetInfoReq;               	/* GET_ROLE_PET_REQ, Ver.136  */
    ZONEGETROLEPETINFORES GetRolePetInfoRes;               	/* GET_ROLE_PET_RES, Ver.136  */
    ZONESETROLEPETINFOREQ SetRolePetInfoReq;               	/* SET_ROLE_PET_REQ, Ver.136  */
    ZONESETROLEPETINFORES SetRolePetInfoRes;               	/* SET_ROLE_PET_RES, Ver.136  */
    ZONEOUTLINERES ZoneOutLineRes;                  	/* OUTLINE_RES, Ver.137  */
    ZONEADDROLEDESIGNATIONREQ AddRoleDesignationReq;           	/* ADD_ROLE_DESIGNATION_REQ, Ver.137  */
    ZONEADDROLEDESIGNATIONRES AddRoleDesignationRes;           	/* ADD_ROLE_DESIGNATION_RES, Ver.137  */
    ZONEDELROLEDESIGNATIONREQ DelRoleDesignationReq;           	/* DEL_ROLE_DESIGNATION_REQ, Ver.137  */
    ZONEDELROLEDESIGNATIONRES DelRoleDesignationRes;           	/* DEL_ROLE_DESIGNATION_RES, Ver.137  */
    ZONEGETROLEDESIGNATIONLISTREQ GetRoleDesignationListReq;       	/* GET_ROLE_DESIGNATION_LIST_REQ, Ver.137  */
    ZONEGETROLEDESIGNATIONLISTRES GetRoleDesignationListRes;       	/* GET_ROLE_DESIGNATION_LIST_RES, Ver.137  */
    ZONESETROLERESPACTREQ SetRoleRespactReq;               	/* SET_ROLE_RESPACT_REQ, Ver.137  */
    ZONESETROLERESPACTRES SetRoleRespactRes;               	/* SET_ROLE_RESPACT_RES, Ver.137  */
    ZONEDELROLERESPACTREQ DelRoleRespactReq;               	/* DEL_ROLE_RESPACT_REQ, Ver.137  */
    ZONEDELROLERESPACTRES DelRoleRespactRes;               	/* DEL_ROLE_RESPACT_RES, Ver.137  */
    ZONEGETROLERESPACTLISTREQ GetRoleRespactListReq;           	/* GET_ROLE_RESPACT_LIST_REQ, Ver.137  */
    ZONEGETROLERESPACTLISTRES GetRoleRespactListRes;           	/* GET_ROLE_RESPACT_LIST_RES, Ver.137  */
};

struct tagSSZoneCtrl
{
    unsigned int Cmd;                             	/*    Bind Macrosgroup:CtrlCmd,*/
    SSCTRLCMD CtrlCmd;                        
};

struct tagSSCsCtrl
{
    unsigned int Cmd;                             	/*    Bind Macrosgroup:CsCmd,*/
    SSCSCMD CsCmd;                          
};

struct tagSSAasReq
{
    int Uin;                            
    int SvrID;                          
    int tOnline;                         	/*  Ver.120  */
    int tOffline;                        	/*  Ver.120  */
    unsigned char ActType;                         	/*    Bind Macrosgroup:AAS_ACT_TYPE,*/
};

struct tagSSAasRes
{
    int Uin;                            
    int tOnline;                        
    int tOffline;                       
};

struct tagSSUpdateAccountRep
{
    char LoginName[INFORMER_ACCOUNT_LOGIN_NAME_LEN];
};

struct tagSSCashBillReq
{
    unsigned int MessageId;                       	/*   消息类型 */
    tdr_ulonglong Sequence;                        	/*   交易流水号 */
    char Pass9Account[INFORMER_ACCOUNT_LOGIN_NAME_LEN]; 	/*   登录名 */
    unsigned int ServerID;                        	/*   充值到的大区编号 */
    tdr_ulonglong Amount;                          	/*   充值金额 */
    tdr_ulonglong Points;                          	/*   充值点数 */
    tdr_ulonglong Bonus;                           	/*   奖励点数 */
    tdr_ulonglong PropsID;                         	/*   赠送的道具包编号 */
    char PropsName[200];                  	/*   道具包名称 */
};

struct tagSSCashBillRes
{
    int Result;                          	/*   0冲值成功,非0失败 */
    SSCASHBILLREQ CashBillReq;                     	/*   返回请求包 */
};

struct tagSSQueryBillReq
{
    unsigned int MessageId;                       	/*   消息类型 */
    tdr_ulonglong Sequence;                        	/*   交易流水号 */
    char Pass9Account[INFORMER_ACCOUNT_LOGIN_NAME_LEN]; 	/*   登录名 */
    unsigned int ServerID;                        	/*   充值到的大区编号 */
};

struct tagSSQueryBillRes
{
    unsigned int MessageId;                       	/*   消息类型 */
    tdr_ulonglong Sequence;                        	/*   流水号 */
    unsigned int Result;                          	/*   错误码 */
    unsigned int QueryTs;                         	/*   查询时间 */
    tdr_ulonglong Points;                          	/*   充值点数 */
    tdr_ulonglong Bonus;                           	/*   奖励点数 */
    tdr_ulonglong Amount;                          	/*   充值金额 */
};

union tagSSPkgBody
{
    SSDIRREPORT DirReport;                       	/* DIR_REPORT,   */
    SSZONECTRL ZoneCtrl;                        	/* ZONE_CTRL, Ver.44  */
    SSCSCTRL CsCtrL;                          	/* CS_CTRL, Ver.44  */
    SSREPORTDATAALL RePortDataAll;                   	/* RECORD_DIR_INFO,   */
    SSDIRINFOHOUR DirInfoHour;                     	/* DIR_INFO_HOUR,   */
    SSDIRINFODB DirInfoDB;                       	/* DIR_INFO_DB, Ver.45  */
    SSAASREQ AasReq;                          	/* AAS_GAME_REQ, Ver.91  */
    SSAASRES AasRes;                          	/* AAS_GAME_RES, Ver.91  */
    SSGETACCOUNTREQ GetAccountReq;                   	/* INFORMER_GET_ACCOUNT_REQ, Ver.92  */
    SSGETACCOUNTRES GetAccountRes;                   	/* INFORMER_GET_ACCOUNT_RES, Ver.92  */
    SSUPDATEACCOUNTREP UpdateAccountRep;                	/* UPDATE_ACCOUNT_REP, Ver.94  */
    SSCASHBILLREQ CashBillReq;                     	/* CASH_BILL_REQ, Ver.127  */
    SSCASHBILLRES CashBillRes;                     	/* CASH_BILL_RES, Ver.127  */
    SSQUERYBILLREQ QueryBillReq;                    	/* QUERY_BILL_REQ, Ver.127  */
    SSQUERYBILLRES QueryBillRes;                    	/* QUERY_BILL_RES, Ver.127  */
};

struct tagSSPkg
{
    SSPKGHEAD Head;                           
    SSPKGBODY Body;                           
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* PROTO_SS_H */
