/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef UNITE_SVR_DESC_H
#define UNITE_SVR_DESC_H


#ifndef TDR_METALIB_UNITE_SVR_VERSION 
#define TDR_METALIB_UNITE_SVR_VERSION 	10 /*version of metalib*/
#endif

#ifndef TDR_METALIB_UNITE_SVR_HASH 
#define TDR_METALIB_UNITE_SVR_HASH 	"afb70cad819892129663f82bdd234e77" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */

#define ZONE_SVR_URL_LEN                         	32
#define MAX_UNITE_WORLD_NUM                      	8


#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagworldone;
typedef struct tagworldone                         	WORLDONE;
typedef struct tagworldone                         	*LPWORLDONE;

struct tagunite_svr_conf;
typedef struct tagunite_svr_conf                   	UNITE_SVR_CONF;
typedef struct tagunite_svr_conf                   	*LPUNITE_SVR_CONF;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagworldone
{
    int iSrcWorldID;                     	/*   源区ID */
    int iDstWorldID;                     	/*   合到目标区后新的worldid */
    char szSrcDBName[ZONE_SVR_URL_LEN];   	/*   源角色数据库信息 */
    char szSrcDBConnect[ZONE_SVR_URL_LEN];
    char szSrcDBUser[ZONE_SVR_URL_LEN];  
    char szSrcDBPasswd[ZONE_SVR_URL_LEN];
};

struct tagunite_svr_conf
{
    char szMetaFile[128];                 	/*   role_db_meta.tdr */
    int iSrcRegionID;                    	/*   源区ID */
    int iSrcWorldID;                     	/*   合服时才需要填写 */
    char szSrcRoleDBName[ZONE_SVR_URL_LEN]; 	/*   合服时才需要填写 */
    char szSrcRoleDBConnect[ZONE_SVR_URL_LEN]; 	/*   合服时才需要填写 */
    char szSrcRoleDBUser[ZONE_SVR_URL_LEN]; 	/*   合服时才需要填写 */
    char szSrcRoleDBPasswd[ZONE_SVR_URL_LEN]; 	/*   合服时才需要填写 */
    char szSrcAccDBName[ZONE_SVR_URL_LEN]; 	/*   源accout数据库信息 */
    char szSrcAccDBConnect[ZONE_SVR_URL_LEN];
    char szSrcAccDBUser[ZONE_SVR_URL_LEN];
    char szSrcAccDBPasswd[ZONE_SVR_URL_LEN];
    char szSrcBillDBName[ZONE_SVR_URL_LEN]; 	/*   源bill数据库信息 */
    char szSrcBillDBConnect[ZONE_SVR_URL_LEN];
    char szSrcBillDBUser[ZONE_SVR_URL_LEN];
    char szSrcBillDBPasswd[ZONE_SVR_URL_LEN];
    int iDestWorldID;                    	/*   目标服Id */
    int iDestRegionID;                   	/*   目标区ID */
    char szDestRoleDBName[ZONE_SVR_URL_LEN]; 	/*   目标角色数据库信息 */
    char szDestRoleDBConnect[ZONE_SVR_URL_LEN];
    char szDestRoleDBUser[ZONE_SVR_URL_LEN];
    char szDestRoleDBPasswd[ZONE_SVR_URL_LEN];
    char szDstAccDBName[ZONE_SVR_URL_LEN]; 	/*   目标accout数据库信息 */
    char szDstAccDBConnect[ZONE_SVR_URL_LEN];
    char szDstAccDBUser[ZONE_SVR_URL_LEN];
    char szDstAccDBPasswd[ZONE_SVR_URL_LEN];
    char szDstBillDBName[ZONE_SVR_URL_LEN]; 	/*   目标bill数据库信息 */
    char szDstBillDBConnect[ZONE_SVR_URL_LEN];
    char szDstBillDBUser[ZONE_SVR_URL_LEN];
    char szDstBillDBPasswd[ZONE_SVR_URL_LEN];
    char szDstRegionDBName[ZONE_SVR_URL_LEN]; 	/*   目标region数据库信息 */
    char szDstRegionDBConnect[ZONE_SVR_URL_LEN];
    char szDstRegionDBUser[ZONE_SVR_URL_LEN];
    char szDstRegionDBPasswd[ZONE_SVR_URL_LEN];
    int iAccFlag;                        	/*   如果遇到重名角色或者工会,名字要不要加大区ID标记 0-不加大区标记 1-加 */
    int iWorldFlag;                      	/*   如果遇到重名角色或者工会,名字要不要加服ID标记 0-不加大区标记 1-加 */
    int iWorldNum;                       	/*   合区时才需要填写 */
    WORLDONE astWorldList[MAX_UNITE_WORLD_NUM]; 	/*   合区时才需要填写 */
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* UNITE_SVR_DESC_H */
