/* soapCsServiceClient.c
   Generated by gSOAP 2.8.9 from cs_serviceRaw.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapCsServiceH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapCsServiceClient.c ver 2.8.9 2014-07-04 09:31:50 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__FindAccountByNameFirst(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__FindAccountByNameFirstReq *FindAccountByNameFirstReq, struct soapCsService1__FindAccountByNameFirstRes *FindAccountByNameFirstRes)
{	struct __soapCsService1__FindAccountByNameFirst soap_tmp___soapCsService1__FindAccountByNameFirst;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/FindAccountByNameFirst";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__FindAccountByNameFirst.FindAccountByNameFirstReq = FindAccountByNameFirstReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__FindAccountByNameFirst(soap, &soap_tmp___soapCsService1__FindAccountByNameFirst);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__FindAccountByNameFirst(soap, &soap_tmp___soapCsService1__FindAccountByNameFirst, "-soapCsService1:FindAccountByNameFirst", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__FindAccountByNameFirst(soap, &soap_tmp___soapCsService1__FindAccountByNameFirst, "-soapCsService1:FindAccountByNameFirst", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!FindAccountByNameFirstRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__FindAccountByNameFirstRes(soap, FindAccountByNameFirstRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__FindAccountByNameFirstRes(soap, FindAccountByNameFirstRes, "soapCsService1:FindAccountByNameFirstRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__FindAccountByNameNext(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__FindAccountByNameNextReq *FindAccountByNameNextReq, struct soapCsService1__FindAccountByNameNextRes *FindAccountByNameNextRes)
{	struct __soapCsService1__FindAccountByNameNext soap_tmp___soapCsService1__FindAccountByNameNext;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/FindAccountByNameNext";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__FindAccountByNameNext.FindAccountByNameNextReq = FindAccountByNameNextReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__FindAccountByNameNext(soap, &soap_tmp___soapCsService1__FindAccountByNameNext);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__FindAccountByNameNext(soap, &soap_tmp___soapCsService1__FindAccountByNameNext, "-soapCsService1:FindAccountByNameNext", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__FindAccountByNameNext(soap, &soap_tmp___soapCsService1__FindAccountByNameNext, "-soapCsService1:FindAccountByNameNext", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!FindAccountByNameNextRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__FindAccountByNameNextRes(soap, FindAccountByNameNextRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__FindAccountByNameNextRes(soap, FindAccountByNameNextRes, "soapCsService1:FindAccountByNameNextRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__FindHandleClose(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__FindHandleCloseReq *FindHandleCloseReq, struct soapCsService1__FindHandleCloseRes *FindHandleCloseRes)
{	struct __soapCsService1__FindHandleClose soap_tmp___soapCsService1__FindHandleClose;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/FindHandleClose";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__FindHandleClose.FindHandleCloseReq = FindHandleCloseReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__FindHandleClose(soap, &soap_tmp___soapCsService1__FindHandleClose);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__FindHandleClose(soap, &soap_tmp___soapCsService1__FindHandleClose, "-soapCsService1:FindHandleClose", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__FindHandleClose(soap, &soap_tmp___soapCsService1__FindHandleClose, "-soapCsService1:FindHandleClose", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!FindHandleCloseRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__FindHandleCloseRes(soap, FindHandleCloseRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__FindHandleCloseRes(soap, FindHandleCloseRes, "soapCsService1:FindHandleCloseRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__FindAccountByRoleFirst(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__FindAccountByRoleFirstReq *FindAccountByRoleFirstReq, struct soapCsService1__FindAccountByRoleFirstRes *FindAccountByRoleFirstRes)
{	struct __soapCsService1__FindAccountByRoleFirst soap_tmp___soapCsService1__FindAccountByRoleFirst;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/FindAccountByRoleFirst";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__FindAccountByRoleFirst.FindAccountByRoleFirstReq = FindAccountByRoleFirstReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__FindAccountByRoleFirst(soap, &soap_tmp___soapCsService1__FindAccountByRoleFirst);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__FindAccountByRoleFirst(soap, &soap_tmp___soapCsService1__FindAccountByRoleFirst, "-soapCsService1:FindAccountByRoleFirst", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__FindAccountByRoleFirst(soap, &soap_tmp___soapCsService1__FindAccountByRoleFirst, "-soapCsService1:FindAccountByRoleFirst", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!FindAccountByRoleFirstRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__FindAccountByRoleFirstRes(soap, FindAccountByRoleFirstRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__FindAccountByRoleFirstRes(soap, FindAccountByRoleFirstRes, "soapCsService1:FindAccountByRoleFirstRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__FindAccountByRoleNext(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__FindAccountByRoleNextReq *FindAccountByRoleNextReq, struct soapCsService1__FindAccountByRoleNextRes *FindAccountByRoleNextRes)
{	struct __soapCsService1__FindAccountByRoleNext soap_tmp___soapCsService1__FindAccountByRoleNext;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/FindAccountByRoleNext";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__FindAccountByRoleNext.FindAccountByRoleNextReq = FindAccountByRoleNextReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__FindAccountByRoleNext(soap, &soap_tmp___soapCsService1__FindAccountByRoleNext);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__FindAccountByRoleNext(soap, &soap_tmp___soapCsService1__FindAccountByRoleNext, "-soapCsService1:FindAccountByRoleNext", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__FindAccountByRoleNext(soap, &soap_tmp___soapCsService1__FindAccountByRoleNext, "-soapCsService1:FindAccountByRoleNext", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!FindAccountByRoleNextRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__FindAccountByRoleNextRes(soap, FindAccountByRoleNextRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__FindAccountByRoleNextRes(soap, FindAccountByRoleNextRes, "soapCsService1:FindAccountByRoleNextRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__GetRegionWorldInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__GetRegionWorldInfoReq *GetRegionWorldInfoReq, struct soapCsService1__GetRegionWorldInfoRes *GetRegionWorldInfoRes)
{	struct __soapCsService1__GetRegionWorldInfo soap_tmp___soapCsService1__GetRegionWorldInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/GetRegionWorldInfo";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__GetRegionWorldInfo.GetRegionWorldInfoReq = GetRegionWorldInfoReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__GetRegionWorldInfo(soap, &soap_tmp___soapCsService1__GetRegionWorldInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__GetRegionWorldInfo(soap, &soap_tmp___soapCsService1__GetRegionWorldInfo, "-soapCsService1:GetRegionWorldInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__GetRegionWorldInfo(soap, &soap_tmp___soapCsService1__GetRegionWorldInfo, "-soapCsService1:GetRegionWorldInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!GetRegionWorldInfoRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__GetRegionWorldInfoRes(soap, GetRegionWorldInfoRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__GetRegionWorldInfoRes(soap, GetRegionWorldInfoRes, "soapCsService1:GetRegionWorldInfoRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__FindRegionAccountByNameRoleFirst(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__FindRegionAccountByNameRoleFirstReq *FindRegionAccountByNameRoleFirstReq, struct soapCsService1__FindRegionAccountByNameRoleFirstRes *FindRegionAccountByNameRoleFirstRes)
{	struct __soapCsService1__FindRegionAccountByNameRoleFirst soap_tmp___soapCsService1__FindRegionAccountByNameRoleFirst;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/FindRegionAccountByNameRoleFirst";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__FindRegionAccountByNameRoleFirst.FindRegionAccountByNameRoleFirstReq = FindRegionAccountByNameRoleFirstReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__FindRegionAccountByNameRoleFirst(soap, &soap_tmp___soapCsService1__FindRegionAccountByNameRoleFirst);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__FindRegionAccountByNameRoleFirst(soap, &soap_tmp___soapCsService1__FindRegionAccountByNameRoleFirst, "-soapCsService1:FindRegionAccountByNameRoleFirst", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__FindRegionAccountByNameRoleFirst(soap, &soap_tmp___soapCsService1__FindRegionAccountByNameRoleFirst, "-soapCsService1:FindRegionAccountByNameRoleFirst", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!FindRegionAccountByNameRoleFirstRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__FindRegionAccountByNameRoleFirstRes(soap, FindRegionAccountByNameRoleFirstRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__FindRegionAccountByNameRoleFirstRes(soap, FindRegionAccountByNameRoleFirstRes, "soapCsService1:FindRegionAccountByNameRoleFirstRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__FindRegionAccountByNameRoleNext(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__FindRegionAccountByNameRoleNextReq *FindRegionAccountByNameRoleNextReq, struct soapCsService1__FindRegionAccountByNameRoleNextRes *FindRegionAccountByNameRoleNextRes)
{	struct __soapCsService1__FindRegionAccountByNameRoleNext soap_tmp___soapCsService1__FindRegionAccountByNameRoleNext;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/FindRegionAccountByNameRoleNext";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__FindRegionAccountByNameRoleNext.FindRegionAccountByNameRoleNextReq = FindRegionAccountByNameRoleNextReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__FindRegionAccountByNameRoleNext(soap, &soap_tmp___soapCsService1__FindRegionAccountByNameRoleNext);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__FindRegionAccountByNameRoleNext(soap, &soap_tmp___soapCsService1__FindRegionAccountByNameRoleNext, "-soapCsService1:FindRegionAccountByNameRoleNext", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__FindRegionAccountByNameRoleNext(soap, &soap_tmp___soapCsService1__FindRegionAccountByNameRoleNext, "-soapCsService1:FindRegionAccountByNameRoleNext", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!FindRegionAccountByNameRoleNextRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__FindRegionAccountByNameRoleNextRes(soap, FindRegionAccountByNameRoleNextRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__FindRegionAccountByNameRoleNextRes(soap, FindRegionAccountByNameRoleNextRes, "soapCsService1:FindRegionAccountByNameRoleNextRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__KickOffByLoginName(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__KickOffByLoginNameReq *KickOffByLoginNameReq, struct soapCsService1__KickOffByLoginNameRes *KickOffByLoginNameRes)
{	struct __soapCsService1__KickOffByLoginName soap_tmp___soapCsService1__KickOffByLoginName;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/KickOffByLoginName";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__KickOffByLoginName.KickOffByLoginNameReq = KickOffByLoginNameReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__KickOffByLoginName(soap, &soap_tmp___soapCsService1__KickOffByLoginName);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__KickOffByLoginName(soap, &soap_tmp___soapCsService1__KickOffByLoginName, "-soapCsService1:KickOffByLoginName", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__KickOffByLoginName(soap, &soap_tmp___soapCsService1__KickOffByLoginName, "-soapCsService1:KickOffByLoginName", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!KickOffByLoginNameRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__KickOffByLoginNameRes(soap, KickOffByLoginNameRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__KickOffByLoginNameRes(soap, KickOffByLoginNameRes, "soapCsService1:KickOffByLoginNameRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__SetAccountFreeze(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__SetAccountFreezeReq *SetAccountFreezeReq, struct soapCsService1__SetAccountFreezeRes *SetAccountFreezeRes)
{	struct __soapCsService1__SetAccountFreeze soap_tmp___soapCsService1__SetAccountFreeze;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/SetAccountFreeze";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__SetAccountFreeze.SetAccountFreezeReq = SetAccountFreezeReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__SetAccountFreeze(soap, &soap_tmp___soapCsService1__SetAccountFreeze);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__SetAccountFreeze(soap, &soap_tmp___soapCsService1__SetAccountFreeze, "-soapCsService1:SetAccountFreeze", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__SetAccountFreeze(soap, &soap_tmp___soapCsService1__SetAccountFreeze, "-soapCsService1:SetAccountFreeze", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!SetAccountFreezeRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__SetAccountFreezeRes(soap, SetAccountFreezeRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__SetAccountFreezeRes(soap, SetAccountFreezeRes, "soapCsService1:SetAccountFreezeRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__SetAccountSilence(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__SetAccountSilenceReq *SetAccountSilenceReq, struct soapCsService1__SetAccountSilenceRes *SetAccountSilenceRes)
{	struct __soapCsService1__SetAccountSilence soap_tmp___soapCsService1__SetAccountSilence;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/SetAccountSilence";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__SetAccountSilence.SetAccountSilenceReq = SetAccountSilenceReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__SetAccountSilence(soap, &soap_tmp___soapCsService1__SetAccountSilence);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__SetAccountSilence(soap, &soap_tmp___soapCsService1__SetAccountSilence, "-soapCsService1:SetAccountSilence", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__SetAccountSilence(soap, &soap_tmp___soapCsService1__SetAccountSilence, "-soapCsService1:SetAccountSilence", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!SetAccountSilenceRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__SetAccountSilenceRes(soap, SetAccountSilenceRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__SetAccountSilenceRes(soap, SetAccountSilenceRes, "soapCsService1:SetAccountSilenceRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__SetAccSafelock(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__SetAccSafelockReq *SetAccSafelockReq, struct soapCsService1__SetAccSafelockRes *SetAccSafelockRes)
{	struct __soapCsService1__SetAccSafelock soap_tmp___soapCsService1__SetAccSafelock;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/SetAccSafelock";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__SetAccSafelock.SetAccSafelockReq = SetAccSafelockReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__SetAccSafelock(soap, &soap_tmp___soapCsService1__SetAccSafelock);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__SetAccSafelock(soap, &soap_tmp___soapCsService1__SetAccSafelock, "-soapCsService1:SetAccSafelock", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__SetAccSafelock(soap, &soap_tmp___soapCsService1__SetAccSafelock, "-soapCsService1:SetAccSafelock", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!SetAccSafelockRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__SetAccSafelockRes(soap, SetAccSafelockRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__SetAccSafelockRes(soap, SetAccSafelockRes, "soapCsService1:SetAccSafelockRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__GetRoleList(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__GetRoleListReq *GetRoleListReq, struct soapCsService1__GetRoleListRes *GetRoleListRes)
{	struct __soapCsService1__GetRoleList soap_tmp___soapCsService1__GetRoleList;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/GetRoleList";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__GetRoleList.GetRoleListReq = GetRoleListReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__GetRoleList(soap, &soap_tmp___soapCsService1__GetRoleList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__GetRoleList(soap, &soap_tmp___soapCsService1__GetRoleList, "-soapCsService1:GetRoleList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__GetRoleList(soap, &soap_tmp___soapCsService1__GetRoleList, "-soapCsService1:GetRoleList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!GetRoleListRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__GetRoleListRes(soap, GetRoleListRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__GetRoleListRes(soap, GetRoleListRes, "soapCsService1:GetRoleListRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__FindFirstRoleByRolename(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__FindFirstRoleByRolenameReq *FindFirstRoleByRolenameReq, struct soapCsService1__FindFirstRoleByRolenameRes *FindFirstRoleByRolenameRes)
{	struct __soapCsService1__FindFirstRoleByRolename soap_tmp___soapCsService1__FindFirstRoleByRolename;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/FindFirstRoleByRolename";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__FindFirstRoleByRolename.FindFirstRoleByRolenameReq = FindFirstRoleByRolenameReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__FindFirstRoleByRolename(soap, &soap_tmp___soapCsService1__FindFirstRoleByRolename);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__FindFirstRoleByRolename(soap, &soap_tmp___soapCsService1__FindFirstRoleByRolename, "-soapCsService1:FindFirstRoleByRolename", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__FindFirstRoleByRolename(soap, &soap_tmp___soapCsService1__FindFirstRoleByRolename, "-soapCsService1:FindFirstRoleByRolename", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!FindFirstRoleByRolenameRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__FindFirstRoleByRolenameRes(soap, FindFirstRoleByRolenameRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__FindFirstRoleByRolenameRes(soap, FindFirstRoleByRolenameRes, "soapCsService1:FindFirstRoleByRolenameRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__FindNextRole(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__FindNextRoleReq *FindNextRoleReq, struct soapCsService1__FindNextRoleRes *FindNextRoleRes)
{	struct __soapCsService1__FindNextRole soap_tmp___soapCsService1__FindNextRole;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/FindNextRole";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__FindNextRole.FindNextRoleReq = FindNextRoleReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__FindNextRole(soap, &soap_tmp___soapCsService1__FindNextRole);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__FindNextRole(soap, &soap_tmp___soapCsService1__FindNextRole, "-soapCsService1:FindNextRole", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__FindNextRole(soap, &soap_tmp___soapCsService1__FindNextRole, "-soapCsService1:FindNextRole", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!FindNextRoleRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__FindNextRoleRes(soap, FindNextRoleRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__FindNextRoleRes(soap, FindNextRoleRes, "soapCsService1:FindNextRoleRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__GetRoleInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__GetRoleInfoReq *GetRoleInfoReq, struct soapCsService1__GetRoleInfoRes *GetRoleInfoRes)
{	struct __soapCsService1__GetRoleInfo soap_tmp___soapCsService1__GetRoleInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/GetRoleInfo";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__GetRoleInfo.GetRoleInfoReq = GetRoleInfoReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__GetRoleInfo(soap, &soap_tmp___soapCsService1__GetRoleInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__GetRoleInfo(soap, &soap_tmp___soapCsService1__GetRoleInfo, "-soapCsService1:GetRoleInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__GetRoleInfo(soap, &soap_tmp___soapCsService1__GetRoleInfo, "-soapCsService1:GetRoleInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!GetRoleInfoRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__GetRoleInfoRes(soap, GetRoleInfoRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__GetRoleInfoRes(soap, GetRoleInfoRes, "soapCsService1:GetRoleInfoRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__GetItemInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__GetItemInfoReq *GetItemInfoReq, struct soapCsService1__GetItemInfoRes *GetItemInfoRes)
{	struct __soapCsService1__GetItemInfo soap_tmp___soapCsService1__GetItemInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/GetItemInfo";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__GetItemInfo.GetItemInfoReq = GetItemInfoReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__GetItemInfo(soap, &soap_tmp___soapCsService1__GetItemInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__GetItemInfo(soap, &soap_tmp___soapCsService1__GetItemInfo, "-soapCsService1:GetItemInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__GetItemInfo(soap, &soap_tmp___soapCsService1__GetItemInfo, "-soapCsService1:GetItemInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!GetItemInfoRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__GetItemInfoRes(soap, GetItemInfoRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__GetItemInfoRes(soap, GetItemInfoRes, "soapCsService1:GetItemInfoRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__GetSkillInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__GetSkillInfoReq *GetSkillInfoReq, struct soapCsService1__GetSkillInfoRes *GetSkillInfoRes)
{	struct __soapCsService1__GetSkillInfo soap_tmp___soapCsService1__GetSkillInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/GetSkillInfo";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__GetSkillInfo.GetSkillInfoReq = GetSkillInfoReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__GetSkillInfo(soap, &soap_tmp___soapCsService1__GetSkillInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__GetSkillInfo(soap, &soap_tmp___soapCsService1__GetSkillInfo, "-soapCsService1:GetSkillInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__GetSkillInfo(soap, &soap_tmp___soapCsService1__GetSkillInfo, "-soapCsService1:GetSkillInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!GetSkillInfoRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__GetSkillInfoRes(soap, GetSkillInfoRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__GetSkillInfoRes(soap, GetSkillInfoRes, "soapCsService1:GetSkillInfoRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__BlockRole(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__BlockRoleReq *BlockRoleReq, struct soapCsService1__BlockRoleRes *BlockRoleRes)
{	struct __soapCsService1__BlockRole soap_tmp___soapCsService1__BlockRole;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/BlockRole";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__BlockRole.BlockRoleReq = BlockRoleReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__BlockRole(soap, &soap_tmp___soapCsService1__BlockRole);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__BlockRole(soap, &soap_tmp___soapCsService1__BlockRole, "-soapCsService1:BlockRole", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__BlockRole(soap, &soap_tmp___soapCsService1__BlockRole, "-soapCsService1:BlockRole", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!BlockRoleRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__BlockRoleRes(soap, BlockRoleRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__BlockRoleRes(soap, BlockRoleRes, "soapCsService1:BlockRoleRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__SilenceRole(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__SilenceRoleReq *SilenceRoleReq, struct soapCsService1__SilenceRoleRes *SilenceRoleRes)
{	struct __soapCsService1__SilenceRole soap_tmp___soapCsService1__SilenceRole;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/SilenceRole";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__SilenceRole.SilenceRoleReq = SilenceRoleReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__SilenceRole(soap, &soap_tmp___soapCsService1__SilenceRole);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__SilenceRole(soap, &soap_tmp___soapCsService1__SilenceRole, "-soapCsService1:SilenceRole", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__SilenceRole(soap, &soap_tmp___soapCsService1__SilenceRole, "-soapCsService1:SilenceRole", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!SilenceRoleRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__SilenceRoleRes(soap, SilenceRoleRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__SilenceRoleRes(soap, SilenceRoleRes, "soapCsService1:SilenceRoleRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__ChgRolePos(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__ChgRolePosReq *ChgRolePosReq, struct soapCsService1__ChgRolePosRes *ChgRolePosRes)
{	struct __soapCsService1__ChgRolePos soap_tmp___soapCsService1__ChgRolePos;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/ChgRolePos";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__ChgRolePos.ChgRolePosReq = ChgRolePosReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__ChgRolePos(soap, &soap_tmp___soapCsService1__ChgRolePos);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__ChgRolePos(soap, &soap_tmp___soapCsService1__ChgRolePos, "-soapCsService1:ChgRolePos", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__ChgRolePos(soap, &soap_tmp___soapCsService1__ChgRolePos, "-soapCsService1:ChgRolePos", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ChgRolePosRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__ChgRolePosRes(soap, ChgRolePosRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__ChgRolePosRes(soap, ChgRolePosRes, "soapCsService1:ChgRolePosRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__FindFirstMaillist(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__FindFirstMaillistReq *FindFirstMaillistReq, struct soapCsService1__FindFirstMaillistRes *FindFirstMaillistRes)
{	struct __soapCsService1__FindFirstMaillist soap_tmp___soapCsService1__FindFirstMaillist;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/FindFirstMaillist";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__FindFirstMaillist.FindFirstMaillistReq = FindFirstMaillistReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__FindFirstMaillist(soap, &soap_tmp___soapCsService1__FindFirstMaillist);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__FindFirstMaillist(soap, &soap_tmp___soapCsService1__FindFirstMaillist, "-soapCsService1:FindFirstMaillist", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__FindFirstMaillist(soap, &soap_tmp___soapCsService1__FindFirstMaillist, "-soapCsService1:FindFirstMaillist", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!FindFirstMaillistRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__FindFirstMaillistRes(soap, FindFirstMaillistRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__FindFirstMaillistRes(soap, FindFirstMaillistRes, "soapCsService1:FindFirstMaillistRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__FindNextMaillist(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__FindNextMaillistReq *FindNextMaillistReq, struct soapCsService1__FindNextMaillistRes *FindNextMaillistRes)
{	struct __soapCsService1__FindNextMaillist soap_tmp___soapCsService1__FindNextMaillist;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/FindNextMaillist";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__FindNextMaillist.FindNextMaillistReq = FindNextMaillistReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__FindNextMaillist(soap, &soap_tmp___soapCsService1__FindNextMaillist);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__FindNextMaillist(soap, &soap_tmp___soapCsService1__FindNextMaillist, "-soapCsService1:FindNextMaillist", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__FindNextMaillist(soap, &soap_tmp___soapCsService1__FindNextMaillist, "-soapCsService1:FindNextMaillist", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!FindNextMaillistRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__FindNextMaillistRes(soap, FindNextMaillistRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__FindNextMaillistRes(soap, FindNextMaillistRes, "soapCsService1:FindNextMaillistRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__GetRideInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__GetRideInfoReq *GetRideInfoReq, struct soapCsService1__GetRideInfoRes *GetRideInfoRes)
{	struct __soapCsService1__GetRideInfo soap_tmp___soapCsService1__GetRideInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/GetRideInfo";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__GetRideInfo.GetRideInfoReq = GetRideInfoReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__GetRideInfo(soap, &soap_tmp___soapCsService1__GetRideInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__GetRideInfo(soap, &soap_tmp___soapCsService1__GetRideInfo, "-soapCsService1:GetRideInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__GetRideInfo(soap, &soap_tmp___soapCsService1__GetRideInfo, "-soapCsService1:GetRideInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!GetRideInfoRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__GetRideInfoRes(soap, GetRideInfoRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__GetRideInfoRes(soap, GetRideInfoRes, "soapCsService1:GetRideInfoRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__GetBulletinList(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__GetBulletinListReq *GetBulletinListReq, struct soapCsService1__GetBulletinListRes *GetBulletinListRes)
{	struct __soapCsService1__GetBulletinList soap_tmp___soapCsService1__GetBulletinList;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/GetBulletinList";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__GetBulletinList.GetBulletinListReq = GetBulletinListReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__GetBulletinList(soap, &soap_tmp___soapCsService1__GetBulletinList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__GetBulletinList(soap, &soap_tmp___soapCsService1__GetBulletinList, "-soapCsService1:GetBulletinList", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__GetBulletinList(soap, &soap_tmp___soapCsService1__GetBulletinList, "-soapCsService1:GetBulletinList", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!GetBulletinListRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__GetBulletinListRes(soap, GetBulletinListRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__GetBulletinListRes(soap, GetBulletinListRes, "soapCsService1:GetBulletinListRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__AddBulletin(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__AddBulletinReq *AddBulletinReq, struct soapCsService1__AddBulletinRes *AddBulletinRes)
{	struct __soapCsService1__AddBulletin soap_tmp___soapCsService1__AddBulletin;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/AddBulletin";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__AddBulletin.AddBulletinReq = AddBulletinReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__AddBulletin(soap, &soap_tmp___soapCsService1__AddBulletin);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__AddBulletin(soap, &soap_tmp___soapCsService1__AddBulletin, "-soapCsService1:AddBulletin", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__AddBulletin(soap, &soap_tmp___soapCsService1__AddBulletin, "-soapCsService1:AddBulletin", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!AddBulletinRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__AddBulletinRes(soap, AddBulletinRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__AddBulletinRes(soap, AddBulletinRes, "soapCsService1:AddBulletinRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__AddBulletinToAll(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__AddBulletinToAllReq *AddBulletinToAllReq, struct soapCsService1__AddBulletinToAllRes *AddBulletinToAllRes)
{	struct __soapCsService1__AddBulletinToAll soap_tmp___soapCsService1__AddBulletinToAll;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/AddBulletinToAll";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__AddBulletinToAll.AddBulletinToAllReq = AddBulletinToAllReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__AddBulletinToAll(soap, &soap_tmp___soapCsService1__AddBulletinToAll);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__AddBulletinToAll(soap, &soap_tmp___soapCsService1__AddBulletinToAll, "-soapCsService1:AddBulletinToAll", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__AddBulletinToAll(soap, &soap_tmp___soapCsService1__AddBulletinToAll, "-soapCsService1:AddBulletinToAll", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!AddBulletinToAllRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__AddBulletinToAllRes(soap, AddBulletinToAllRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__AddBulletinToAllRes(soap, AddBulletinToAllRes, "soapCsService1:AddBulletinToAllRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__DelBulletin(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__DelBulletinReq *DelBulletinReq, struct soapCsService1__DelBulletinRes *DelBulletinRes)
{	struct __soapCsService1__DelBulletin soap_tmp___soapCsService1__DelBulletin;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/DelBulletin";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__DelBulletin.DelBulletinReq = DelBulletinReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__DelBulletin(soap, &soap_tmp___soapCsService1__DelBulletin);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__DelBulletin(soap, &soap_tmp___soapCsService1__DelBulletin, "-soapCsService1:DelBulletin", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__DelBulletin(soap, &soap_tmp___soapCsService1__DelBulletin, "-soapCsService1:DelBulletin", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!DelBulletinRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__DelBulletinRes(soap, DelBulletinRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__DelBulletinRes(soap, DelBulletinRes, "soapCsService1:DelBulletinRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__DelBulletinFromAll(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__DelBulletinFromAllReq *DelBulletinFromAllReq, struct soapCsService1__DelBulletinFromAllRes *DelBulletinFromAllRes)
{	struct __soapCsService1__DelBulletinFromAll soap_tmp___soapCsService1__DelBulletinFromAll;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/CsService/DelBulletinFromAll";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__DelBulletinFromAll.DelBulletinFromAllReq = DelBulletinFromAllReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__DelBulletinFromAll(soap, &soap_tmp___soapCsService1__DelBulletinFromAll);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__DelBulletinFromAll(soap, &soap_tmp___soapCsService1__DelBulletinFromAll, "-soapCsService1:DelBulletinFromAll", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__DelBulletinFromAll(soap, &soap_tmp___soapCsService1__DelBulletinFromAll, "-soapCsService1:DelBulletinFromAll", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!DelBulletinFromAllRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__DelBulletinFromAllRes(soap, DelBulletinFromAllRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__DelBulletinFromAllRes(soap, DelBulletinFromAllRes, "soapCsService1:DelBulletinFromAllRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__ReloadServer(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__ReloadServerReq *ReloadServerReq, struct soapCsService1__ReloadServerRes *ReloadServerRes)
{	struct __soapCsService1__ReloadServer soap_tmp___soapCsService1__ReloadServer;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/cs_service/ReloadServer";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__ReloadServer.ReloadServerReq = ReloadServerReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__ReloadServer(soap, &soap_tmp___soapCsService1__ReloadServer);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__ReloadServer(soap, &soap_tmp___soapCsService1__ReloadServer, "-soapCsService1:ReloadServer", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__ReloadServer(soap, &soap_tmp___soapCsService1__ReloadServer, "-soapCsService1:ReloadServer", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ReloadServerRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__ReloadServerRes(soap, ReloadServerRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__ReloadServerRes(soap, ReloadServerRes, "soapCsService1:ReloadServerRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__ParseBlob(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__ParseBlobReq *ParseBlobReq, struct soapCsService1__ParseBlobRes *ParseBlobRes)
{	struct __soapCsService1__ParseBlob soap_tmp___soapCsService1__ParseBlob;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/cs_service/ParseBlob";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__ParseBlob.ParseBlobReq = ParseBlobReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__ParseBlob(soap, &soap_tmp___soapCsService1__ParseBlob);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__ParseBlob(soap, &soap_tmp___soapCsService1__ParseBlob, "-soapCsService1:ParseBlob", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__ParseBlob(soap, &soap_tmp___soapCsService1__ParseBlob, "-soapCsService1:ParseBlob", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ParseBlobRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__ParseBlobRes(soap, ParseBlobRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__ParseBlobRes(soap, ParseBlobRes, "soapCsService1:ParseBlobRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__CashPropsGiftBill(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__CashPropsGiftBillReq *CashPropsGiftBillReq, struct soapCsService1__CashPropsGiftBillRes *CashPropsGiftBillRes)
{	struct __soapCsService1__CashPropsGiftBill soap_tmp___soapCsService1__CashPropsGiftBill;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/cs_service/CashPropsGiftBill";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__CashPropsGiftBill.CashPropsGiftBillReq = CashPropsGiftBillReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__CashPropsGiftBill(soap, &soap_tmp___soapCsService1__CashPropsGiftBill);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__CashPropsGiftBill(soap, &soap_tmp___soapCsService1__CashPropsGiftBill, "-soapCsService1:CashPropsGiftBill", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__CashPropsGiftBill(soap, &soap_tmp___soapCsService1__CashPropsGiftBill, "-soapCsService1:CashPropsGiftBill", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!CashPropsGiftBillRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__CashPropsGiftBillRes(soap, CashPropsGiftBillRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__CashPropsGiftBillRes(soap, CashPropsGiftBillRes, "soapCsService1:CashPropsGiftBillRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__SendSysMail(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__SendSysMailReq *SendSysMailReq, struct soapCsService1__SendSysMailRes *SendSysMailRes)
{	struct __soapCsService1__SendSysMail soap_tmp___soapCsService1__SendSysMail;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/cs_service/SendSysMail";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__SendSysMail.SendSysMailReq = SendSysMailReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__SendSysMail(soap, &soap_tmp___soapCsService1__SendSysMail);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__SendSysMail(soap, &soap_tmp___soapCsService1__SendSysMail, "-soapCsService1:SendSysMail", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__SendSysMail(soap, &soap_tmp___soapCsService1__SendSysMail, "-soapCsService1:SendSysMail", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!SendSysMailRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__SendSysMailRes(soap, SendSysMailRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__SendSysMailRes(soap, SendSysMailRes, "soapCsService1:SendSysMailRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__SetAccountUinFlag(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__SetAccountUinFlagReq *SetAccountUinFlagReq, struct soapCsService1__SetAccountUinFlagRes *SetAccountUinFlagRes)
{	struct __soapCsService1__SetAccountUinFlag soap_tmp___soapCsService1__SetAccountUinFlag;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/cs_service/SetAccountUinFlag";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__SetAccountUinFlag.SetAccountUinFlagReq = SetAccountUinFlagReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__SetAccountUinFlag(soap, &soap_tmp___soapCsService1__SetAccountUinFlag);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__SetAccountUinFlag(soap, &soap_tmp___soapCsService1__SetAccountUinFlag, "-soapCsService1:SetAccountUinFlag", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__SetAccountUinFlag(soap, &soap_tmp___soapCsService1__SetAccountUinFlag, "-soapCsService1:SetAccountUinFlag", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!SetAccountUinFlagRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__SetAccountUinFlagRes(soap, SetAccountUinFlagRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__SetAccountUinFlagRes(soap, SetAccountUinFlagRes, "soapCsService1:SetAccountUinFlagRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__ExchangeClanLeader(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__ExchangeClanLeaderReq *ExchangeClanLeaderReq, struct soapCsService1__ExchangeClanLeaderRes *ExchangeClanLeaderRes)
{	struct __soapCsService1__ExchangeClanLeader soap_tmp___soapCsService1__ExchangeClanLeader;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/cs_service/ExchangeClanLeader";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__ExchangeClanLeader.ExchangeClanLeaderReq = ExchangeClanLeaderReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__ExchangeClanLeader(soap, &soap_tmp___soapCsService1__ExchangeClanLeader);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__ExchangeClanLeader(soap, &soap_tmp___soapCsService1__ExchangeClanLeader, "-soapCsService1:ExchangeClanLeader", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__ExchangeClanLeader(soap, &soap_tmp___soapCsService1__ExchangeClanLeader, "-soapCsService1:ExchangeClanLeader", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ExchangeClanLeaderRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__ExchangeClanLeaderRes(soap, ExchangeClanLeaderRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__ExchangeClanLeaderRes(soap, ExchangeClanLeaderRes, "soapCsService1:ExchangeClanLeaderRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__RestoreDeletedRole(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__RestoreDeletedRoleReq *RestoreDeletedRoleReq, struct soapCsService1__RestoreDeletedRoleRes *RestoreDeletedRoleRes)
{	struct __soapCsService1__RestoreDeletedRole soap_tmp___soapCsService1__RestoreDeletedRole;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/cs_service/RestoreDeletedRole";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__RestoreDeletedRole.RestoreDeletedRoleReq = RestoreDeletedRoleReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__RestoreDeletedRole(soap, &soap_tmp___soapCsService1__RestoreDeletedRole);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__RestoreDeletedRole(soap, &soap_tmp___soapCsService1__RestoreDeletedRole, "-soapCsService1:RestoreDeletedRole", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__RestoreDeletedRole(soap, &soap_tmp___soapCsService1__RestoreDeletedRole, "-soapCsService1:RestoreDeletedRole", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!RestoreDeletedRoleRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__RestoreDeletedRoleRes(soap, RestoreDeletedRoleRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__RestoreDeletedRoleRes(soap, RestoreDeletedRoleRes, "soapCsService1:RestoreDeletedRoleRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__ChgRoleName(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__ChgRoleNameReq *ChgRoleNameReq, struct soapCsService1__ChgRoleNameRes *ChgRoleNameRes)
{	struct __soapCsService1__ChgRoleName soap_tmp___soapCsService1__ChgRoleName;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/cs_service/ChgRoleName";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__ChgRoleName.ChgRoleNameReq = ChgRoleNameReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__ChgRoleName(soap, &soap_tmp___soapCsService1__ChgRoleName);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__ChgRoleName(soap, &soap_tmp___soapCsService1__ChgRoleName, "-soapCsService1:ChgRoleName", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__ChgRoleName(soap, &soap_tmp___soapCsService1__ChgRoleName, "-soapCsService1:ChgRoleName", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ChgRoleNameRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__ChgRoleNameRes(soap, ChgRoleNameRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__ChgRoleNameRes(soap, ChgRoleNameRes, "soapCsService1:ChgRoleNameRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__ShopCgi(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__ShopCgiReq *ShopCgiReq, struct soapCsService1__ShopCgiRes *ShopCgiRes)
{	struct __soapCsService1__ShopCgi soap_tmp___soapCsService1__ShopCgi;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/cs_service/ShopCgi";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__ShopCgi.ShopCgiReq = ShopCgiReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__ShopCgi(soap, &soap_tmp___soapCsService1__ShopCgi);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__ShopCgi(soap, &soap_tmp___soapCsService1__ShopCgi, "-soapCsService1:ShopCgi", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__ShopCgi(soap, &soap_tmp___soapCsService1__ShopCgi, "-soapCsService1:ShopCgi", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ShopCgiRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__ShopCgiRes(soap, ShopCgiRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__ShopCgiRes(soap, ShopCgiRes, "soapCsService1:ShopCgiRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__SetPetInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__SetPetInfoReq *SetPetInfoReq, struct soapCsService1__SetPetInfoRes *SetPetInfoRes)
{	struct __soapCsService1__SetPetInfo soap_tmp___soapCsService1__SetPetInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/cs_service/SetPetInfo";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__SetPetInfo.SetPetInfoReq = SetPetInfoReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__SetPetInfo(soap, &soap_tmp___soapCsService1__SetPetInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__SetPetInfo(soap, &soap_tmp___soapCsService1__SetPetInfo, "-soapCsService1:SetPetInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__SetPetInfo(soap, &soap_tmp___soapCsService1__SetPetInfo, "-soapCsService1:SetPetInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!SetPetInfoRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__SetPetInfoRes(soap, SetPetInfoRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__SetPetInfoRes(soap, SetPetInfoRes, "soapCsService1:SetPetInfoRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__SetSecondPwd(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__SetSecondPwdReq *SetSecondPwdReq, struct soapCsService1__SetSecondPwdRes *SetSecondPwdRes)
{	struct __soapCsService1__SetSecondPwd soap_tmp___soapCsService1__SetSecondPwd;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/cs_service/SetSecondPwd";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__SetSecondPwd.SetSecondPwdReq = SetSecondPwdReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__SetSecondPwd(soap, &soap_tmp___soapCsService1__SetSecondPwd);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__SetSecondPwd(soap, &soap_tmp___soapCsService1__SetSecondPwd, "-soapCsService1:SetSecondPwd", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__SetSecondPwd(soap, &soap_tmp___soapCsService1__SetSecondPwd, "-soapCsService1:SetSecondPwd", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!SetSecondPwdRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__SetSecondPwdRes(soap, SetSecondPwdRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__SetSecondPwdRes(soap, SetSecondPwdRes, "soapCsService1:SetSecondPwdRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__GetRoleMailData(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__GetRoleMailDataReq *GetRoleMailDataReq, struct soapCsService1__GetRoleMailDataRes *GetRoleMailDataRes)
{	struct __soapCsService1__GetRoleMailData soap_tmp___soapCsService1__GetRoleMailData;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/cs_service/GetRoleMailData";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__GetRoleMailData.GetRoleMailDataReq = GetRoleMailDataReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__GetRoleMailData(soap, &soap_tmp___soapCsService1__GetRoleMailData);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__GetRoleMailData(soap, &soap_tmp___soapCsService1__GetRoleMailData, "-soapCsService1:GetRoleMailData", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__GetRoleMailData(soap, &soap_tmp___soapCsService1__GetRoleMailData, "-soapCsService1:GetRoleMailData", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!GetRoleMailDataRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__GetRoleMailDataRes(soap, GetRoleMailDataRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__GetRoleMailDataRes(soap, GetRoleMailDataRes, "soapCsService1:GetRoleMailDataRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___soapCsService1__SetItemInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct soapCsService1__SetItemInfoReq *SetItemInfoReq, struct soapCsService1__SetItemInfoRes *SetItemInfoRes)
{	struct __soapCsService1__SetItemInfo soap_tmp___soapCsService1__SetItemInfo;
	if (!soap_endpoint)
		soap_endpoint = "http://192.168.0.57:800/cgi-bin/cs_service";
	if (!soap_action)
		soap_action = "http://www.ljy0.com/cs_service/SetItemInfo";
	soap->encodingStyle = NULL;
	soap_tmp___soapCsService1__SetItemInfo.SetItemInfoReq = SetItemInfoReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___soapCsService1__SetItemInfo(soap, &soap_tmp___soapCsService1__SetItemInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___soapCsService1__SetItemInfo(soap, &soap_tmp___soapCsService1__SetItemInfo, "-soapCsService1:SetItemInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___soapCsService1__SetItemInfo(soap, &soap_tmp___soapCsService1__SetItemInfo, "-soapCsService1:SetItemInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!SetItemInfoRes)
		return soap_closesock(soap);
	soap_default_soapCsService1__SetItemInfoRes(soap, SetItemInfoRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get_soapCsService1__SetItemInfoRes(soap, SetItemInfoRes, "soapCsService1:SetItemInfoRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapCsServiceClient.c */
