/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef GAMESTAT_DESC_H
#define GAMESTAT_DESC_H


#ifndef TDR_METALIB_GAMESTAT_VERSION 
#define TDR_METALIB_GAMESTAT_VERSION 	10 /*version of metalib*/
#endif

#ifndef TDR_METALIB_GAMESTAT_HASH 
#define TDR_METALIB_GAMESTAT_HASH 	"e9554a4827cd8079f706712ca1727391" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */

#define GAMESTAT_URL_LEN                         	32
#define MAX_WORLD                                	128
#define MAX_REGION                               	64


#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagZoneInfo;
typedef struct tagZoneInfo                         	ZONEINFO;
typedef struct tagZoneInfo                         	*LPZONEINFO;

struct tagRegionInfo;
typedef struct tagRegionInfo                       	REGIONINFO;
typedef struct tagRegionInfo                       	*LPREGIONINFO;

struct taggamestat_conf;
typedef struct taggamestat_conf                    	GAMESTAT_CONF;
typedef struct taggamestat_conf                    	*LPGAMESTAT_CONF;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagZoneInfo
{
    int iWorldid;                        	/*   服ID */
};

struct tagRegionInfo
{
    int iRegionid;                       	/*   区ID */
    int iWorldNum;                       	/*   有多服 */
    ZONEINFO astWorld[MAX_WORLD];             	/*   服id列表 */
};

struct taggamestat_conf
{
    char szMetaFile[128];                
    char szDBConnect[GAMESTAT_URL_LEN];  
    char szDBUser[GAMESTAT_URL_LEN];     
    char szPasswd[GAMESTAT_URL_LEN];     
    char szLogDBConnect[GAMESTAT_URL_LEN];
    char szLogDBUser[GAMESTAT_URL_LEN];  
    char szLogPasswd[GAMESTAT_URL_LEN];  
    int iRegionNum;                      	/*   有多区 */
    REGIONINFO astRegion[MAX_REGION];           	/*   区id列表 */
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* GAMESTAT_DESC_H */
