/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef RESCONV_H
#define RESCONV_H


#ifndef TDR_METALIB_RESCONV_VERSION 
#define TDR_METALIB_RESCONV_VERSION 	4 /*version of metalib*/
#endif

#ifndef TDR_METALIB_RESCONV_HASH 
#define TDR_METALIB_RESCONV_HASH 	"6c53fc2a9163d7cf096959b486e9d986" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */

#define TRES_FILE_MAGIC                          	1397052237
#define TRES_TRANSLATE_METALIB_HASH_LEN          	36 	/* 元数据库hash值的长度 */
#define TRES_ENCORDING_LEN                       	32 	/* max length for encording string */


#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagTResHead;
typedef struct tagTResHead                         	TRESHEAD;
typedef struct tagTResHead                         	*LPTRESHEAD;



/*   Define structs/unions.   */

#pragma pack(1)

/* struct of the Head of Resource File */
struct tagTResHead
{
    int iMagic;                          	/*   Magic number of Resource file */
    int iVersion;                        	/*   version of the Resource file */
    int iUnit;                           	/*   size of each resource calced by Byte */
    int iCount;                          	/*   total count of resources */
    char szMetalibHash[TRES_TRANSLATE_METALIB_HASH_LEN]; 	/*  Ver.2 hash of the resource metalib */
    int iResVersion;                     	/*  Ver.3 version of the Resource struct */
    tdr_datetime_t tCreateTime;                     	/*  Ver.4 create time of resource file */
    char szResEncording[TRES_ENCORDING_LEN]; 	/*  Ver.4 encording of the rescource data */
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* RESCONV_H */
