/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef DIR_SVR_CONF_DESC_H
#define DIR_SVR_CONF_DESC_H


#ifndef TDR_METALIB_DIR_SVR_VERSION 
#define TDR_METALIB_DIR_SVR_VERSION 	10 /*version of metalib*/
#endif

#ifndef TDR_METALIB_DIR_SVR_HASH 
#define TDR_METALIB_DIR_SVR_HASH 	"c69ac2cef0ff146af4fe89aeba33f5ca" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */

#define DIR_STRING_LEN                           	256
#define AUTH_CONN_IP_LEN                         	128
#define DIR_DEF_OUTER_PORT                       	6638
#define DIR_DEF_INNER_PORT                       	6639
#define MAX_DIR_SLAVE                            	8
#define MAX_REGION                               	32
#define CREAT_XML_FILENAME_MAX                   	256

/* MasterFlag*/
enum tagMasterFlag 
{
    DIR_MASTER = 0, 
    DIR_BAK = 1, 
    DIR_SLAVE = 2, 
    DIR_SLAVE1 = 3, 
};


#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagAuthConn;
typedef struct tagAuthConn                         	AUTHCONN;
typedef struct tagAuthConn                         	*LPAUTHCONN;

struct tagbusy_degree;
typedef struct tagbusy_degree                      	BUSY_DEGREE;
typedef struct tagbusy_degree                      	*LPBUSY_DEGREE;

struct tagdir_svrconf;
typedef struct tagdir_svrconf                      	DIR_SVRCONF;
typedef struct tagdir_svrconf                      	*LPDIR_SVRCONF;

struct tagdir_svrrun_status;
typedef struct tagdir_svrrun_status                	DIR_SVRRUN_STATUS;
typedef struct tagdir_svrrun_status                	*LPDIR_SVRRUN_STATUS;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagAuthConn
{
    char AuthConnIP[AUTH_CONN_IP_LEN];   
    unsigned short AuthConnPort;                   
    char AuthConnIP_Bak1[AUTH_CONN_IP_LEN];
    char AuthConnIP_Bak2[AUTH_CONN_IP_LEN];
    unsigned short RegionID;                       
};

struct tagbusy_degree
{
    char Excellence;                      	/*   服务状态很好时在线人数的比例 */
    char Normal;                          	/*   服务状态正常时在线人数的比例 */
    char Busy;                            	/*   服务状态繁忙时在线人数的比例 */
    char Full;                            	/*   服务状态拥挤时在线人数的比例 */
};

struct tagdir_svrconf
{
    unsigned int MasterFlag;                      	/*   dir_master,bak,slave Bind Macrosgroup:MasterFlag,*/
    char DirBakAddr[DIR_STRING_LEN];      	/*   dir_bak的接入地址 */
    unsigned char AuthConnNum;                    
    AUTHCONN AuthConn[MAX_REGION];           
    int DirSlaveAddrNum;                
    char DirSlaveAddrList[MAX_DIR_SLAVE][DIR_STRING_LEN]; 	/*   dir_slave的接入地址列表 */
    char BlackWhiteCfgPath[DIR_STRING_LEN]; 	/*   黑白名单配置文件路径 */
    char WorldListCfgPath[DIR_STRING_LEN]; 	/*   区服列表配置文件 */
    char BindInnerAddr[DIR_STRING_LEN];   	/*   内网接收udp的地址 */
    int UpdataDBInterVal;                	/*   在线在数写入数据库时间间隔,单位:分 */
    char ReportAddr[DIR_STRING_LEN];      	/*   在线人数纪录udp地址 */
    BUSY_DEGREE BusyDegree;                      	/*   服务器是否繁忙的比例 */
    char XmlFileName[CREAT_XML_FILENAME_MAX]; 	/*   生成xml文件路径文件名 */
    int XmlInterval;                     	/*   生成xml文件时间间隔|单位:秒 */
};

struct tagdir_svrrun_status
{
    tdr_longlong RecvCltMsg;                     
    tdr_longlong BadCltMsg;                      
    tdr_longlong SendCltMsgFail;                 
    tdr_longlong SendAllWorldInfo;               
    tdr_longlong SendLatestWorldInfo;            
    tdr_longlong RecvSvrMsg;                     
    tdr_longlong BadSvrMsg;                      
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* DIR_SVR_CONF_DESC_H */
