//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ObjectEditor.rc
//
#define UNIT_VIEW_SHOW                  1
#define UE_EFFECT_LIST                  0x0001
#define UNIT_VIEW_SHOWONLY              2
#define UE_MOTION                       0x0002
#define UNIT_VIEW_HIDE                  3
#define UE_MOTION_BRO_COMMON            0x0004
#define UE_MOTION_BRO_PRIVATE           0x0008
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_TOOLBAR_SKILLTEMPLATE       108
#define IDR_MENU_SAVESKILL              113
#define IDR_MENU_MONSTER_OP             114
#define IDR_MENU_MONSTER_AI             115
#define IDR_MAINFRAME                   128
#define IDR_ObjectEditorTYPE            129
#define IDR_MENU_LAYERLOD               130
#define IDR_TOOLBAR_LAYERLOD            131
#define IDD_DIALOG_POSTEFFECT           133
#define IDD_DIALOG_COLORKEYS            134
#define IDD_DIALOG_ZOOMKEYS             135
#define IDD_DIALOG_ALPHAKEYS            136
#define IDD_DIALOG_EVENTKEYS            137
#define IDD_DIALOG1                     138
#define IDD_DIALOG_BINDOBJECT           138
#define IDR_TOOLBAR_UNKNOWNOBJ          139
#define IDR_TOOLBAR_ANIM                141
#define IDD_DIALOG_ANIMFILES            143
#define IDR_TOOLBAR_BONE                144
#define IDD_DIALOG_SELECTSKILL          146
#define IDR_MENU_EFFECTLIST             146
#define IDD_DIALOG_EFFECTNAME           147
#define IDR_TOOLBAR_AVATAR              147
#define IDD_DIALOG_MOTIONPROPERTY       148
#define IDD_DIALOG_SELECTANIM           149
#define IDD_DIALOG_LOADAVATAR           150
#define IDB_BITMAP_LOGO_ICON            151
#define IDD_DIALOG_NEWCOLORKEY          152
#define IDD_DIALOG_NEWFLOATKEY          153
#define IDD_DIALOG_DIRECTION            154
#define IDD_DIALOG_RIBBONSECTION        157
#define IDD_DIALOG_SECTIONINFO          158
#define IDR_MENU_NEW_POST               161
#define IDR_MENU_SPEED                  180
#define IDR_TOOLBAR_PARTICLE            185
#define IDR_MENU_FRAMELIMIT             187
#define IDR_TOOLBAR_EFFECTLIST          188
#define IDR_MENU_NEWEFFECT              190
#define IDR_TOOLBAR_LIGHT               191
#define IDR_TOOLBAR_BILLBOARD           193
#define IDD_DIALOG_NPCLOADSAVE          195
#define IDR_TOOLBAR_RIBBON              199
#define IDR_TOOLBAR_BEAM                201
#define IDR_TOOLBAR_ITEMBROWSER         203
#define IDR_TOOLBAR_ITEMSEARCH          205
#define IDR_TOOLBAR_MOTION              219
#define IDD_DIALOG_LAYERINFO            221
#define IDR_TOOLBAR_ITEM                228
#define IDR_TOOLBAR_SKILL               230
#define IDD_DIALOG_NEWITEM              233
#define IDR_TOOLBAR_SOUND               235
#define IDD_DIALOG_NEWKEYFRAME          239
#define IDR_TOOLBAR_DECAL               246
#define IDR_TOOLBAR_GEOMETRY            253
#define IDR_MENU_BROWSER_POP            255
#define IDD_DIALOG_EULAR                257
#define IDR_TOOLBAR_BROWSER             258
#define IDR_TOOLBAR_MOTIONBROWSER       260
#define IDR_MENU_MOTIONBROWSER          262
#define IDI_ICON_COMMON_MOTION          265
#define IDI_ICON_PRIVATE_MOTION         266
#define IDI_ICON_GRAY_MOTION            267
#define IDI_ICON_COMMON_MOTION_TASK     268
#define IDI_ICON_PRIVATE_MOTION_TASK    269
#define IDI_ICON_FOLDER                 270
#define IDD_DIALOG_MERGEMOTION          272
#define IDR_TOOLBAR_VIRTUALNODE         273
#define IDR_MENU_BACKGROUND             275
#define IDR_MENU_MOTIONSAVE             276
#define IDC_SLIDER_ZOOM                 1000
#define IDC_EDIT_ZOOM                   1001
#define IDC_LIST_ZOOM                   1002
#define IDC_EDIT_UVOFFSET               1003
#define IDC_BTN_DELETE_COLORKEY         1004
#define IDC_EDIT_SECTION_X              1004
#define IDC_EDIT_SECTION_Y              1005
#define IDC_BUTTON2                     1007
#define IDC_CHECK_RANDOM_FRAME          1008
#define IDC_EDIT_BINDOBJ_ANCHOR         1009
#define IDC_CMB_MOO_ANCHOR              1018
#define IDC_COMBO_MERGETO               1018
#define IDC_COMBO_NEWITEM_QUALITY       1018
#define IDC_CMB_AN_MAINANIM             1018
#define IDC_CMO_ANSEL_ANIMS             1018
#define IDC_EDIT_EFFECTNAME             1019
#define IDC_CMB_MOO_POSINTERPOL         1019
#define IDC_EDIT_DESC                   1033
#define IDC_BTN_DELEVENT                1038
#define IDC_EDIT_NPCID                  1041
#define IDC_EDIT_NPCNAME                1042
#define IDC_EDIT_NPCSCALE               1043
#define IDC_EDIT_MOO_START              1044
#define IDC_EDIT_Y                      1044
#define IDC_EDIT_NPCTRANS               1044
#define IDC_EDIT_MOO_END                1045
#define IDC_EDIT_NPCDESC                1045
#define IDC_EDIT_MOO_SORTINDEX          1046
#define IDC_EDIT_NPCHEIGHT              1046
#define IDC_EDIT_NPCSCALE3              1047
#define IDC_EDIT_NPCRADIUS              1047
#define IDC_LIST_EVENTKEYS              1048
#define IDC_LIST_ANIMFILES              1048
#define IDC_LIST_NPCLIST                1050
#define IDC_EDIT_CKINFO                 1053
#define IDC_EDIT_FKINFO                 1054
#define IDC_EDIT_EVENTKEY               1057
#define IDC_EDIT_MOO_X                  1057
#define IDC_EDIT_ROLL                   1057
#define IDC_EDIT_NEWITEM_ID             1057
#define IDC_EDIT_AN_TIME                1057
#define IDC_EDIT_ANSEL_START            1057
#define IDC_EDIT_START                  1057
#define IDC_EDIT_HROT                   1057
#define IDC_EDIT_MIDDLE                 1060
#define IDC_EDIT_MOO_Z                  1061
#define IDC_EDIT_PITCH                  1061
#define IDC_EDIT_ANSEL_PRIORITY         1061
#define IDC_EDIT_END                    1061
#define IDC_EDIT_X                      1061
#define IDC_CUSTOM1                     1062
#define IDC_SLD_VROT                    1063
#define IDC_EDIT_VROT                   1064
#define IDC_SLD_ACCLEN                  1065
#define IDC_EDIT_Z                      1066
#define IDC_EDIT_ACCLEN                 1068
#define IDC_SLD_HROT                    1069
#define IDC_LIST_EFFECT                 1071
#define IDC_EDIT_MOO_Y                  1072
#define IDC_RDO_EFFECT                  1073
#define IDC_RDO_ANIM                    1074
#define IDC_RADIO_KEYFRAME_COPY         1074
#define IDC_RDO_ONCE                    1074
#define IDC_COMBO_ANIM_ID               1075
#define IDC_CMB_ANIMSEL                 1076
#define IDC_EDIT_ANSEL_END              1077
#define IDC_EDIT_AN_NAME                1078
#define IDC_LIST_SELECTSKILL            1079
#define IDC_LIST_KEYFRAME               1079
#define IDC_EDIT_MOO_NAME               1080
#define IDC_EDIT_MOO_PRIORITY           1080
#define IDC_EDIT_YAW                    1080
#define IDC_EDIT_NEWITEM_NAME           1080
#define IDC_EDIT_FLT_POS                1080
#define IDC_RDO_POST                    1081
#define IDC_RADIO_KEYFRAME_LERP         1081
#define IDC_RDO_LOOP                    1081
#define IDC_EDIT_FLT_VALUE              1081
#define IDC_CHK_MOO_NOSTART             1082
#define IDC_CHK_MOO_NOEND               1083
#define IDC_CHK_MOO_OVERWRITE           1084
#define IDC_CHK_ANSEL_NOSTART           1085
#define IDC_CHK_ANSEL_NOEND             1086
#define IDC_CHK_MOO_FREEZE              1087
#define IDC_CHK_ANSEL_OVERWRITE         1087
#define IDC_CMP_POSTEFFECT              1089
#define IDC_COMBO_POSTTYPE              1090
#define IDC_COMBO_POSTTYPE2             1090
#define IDC_EDIT_POST_START             1091
#define IDC_EDIT_POST_END               1092
#define IDC_CHK_POST_NOSTART            1093
#define IDC_CHK_POST_NOEND              1094
#define IDC_RDO_ONCESTOP                1095
#define IDC_BTN_POSTSETTING             1096
#define IDC_SLIDER_COLORKEY_ALPHA       1097
#define IDC_EDIT_COLORKEY_ALPHA         1098
#define IDC_STATIC_COLORKEY             1099
#define IDC_LIST_COLORKEY               1102
#define IDC_CURKF                       1103
#define IDC_CHECK_PUBLIC                1113
#define IDC_STATIC_TITLE                1116
#define IDC_CHECK_NO_DELETE             1118
#define IDC_CMB_MOO_PARENT              1119
#define IDC_LIST_POS                    1120
#define IDC_LIST_CLRKEY                 1121
#define IDC_BTN_ADDEVENT                1124
#define IDC_TREE_EVENTKEYS              1125
#define IDC_BTN_PREDEFINED              1126
#define IDC_BTN_ADD_FROM_PRE            1127
#define ID_BTN_MO_NEW_POST              2057
#define ID_NEW_FILE                     32774
#define ID_NEW_EFFECT                   32775
#define ID_SET_HIGHLOD                  32776
#define ID_SET_MIDDLELOD                32777
#define ID_SET_LOWLOD                   32778
#define ID_SET_NOHANDLE                 32779
#define ID_EXIT_LOD                     32780
#define ID_TB_LAYER_HLOD                32781
#define ID_TB_LAYER_MLOD                32782
#define ID_LOAD_EFFECT                  32782
#define ID_TB_LAYER_LLOD                32783
#define ID_BUTTON_UNOBJ_VISIBLE         32784
#define ID_BUTTON_UNOBJ_CLICK           32785
#define ID_SAVE_SCENE                   32785
#define ID_BUTTON_UNOBJ_APPLY           32786
#define ID_BUTTON_UNOBJ_LOCKAPPLY       32787
#define ID_BUTTON_UNOBJ_REMOVE          32788
#define ID_BUTTON_ANIMPLAY_SINGLE       32789
#define ID_BUTTON_ANIMPLAY_SELECTED     32790
#define ID_BUTTON_ANIMPLAY_ADD          32791
#define ID_MNU_EDITVIEW                 32791
#define ID_BUTTON_ANIM_PAUSE            32792
#define ID_BUTTON_ANIM_STOP             32793
#define ID_BRS_BTN_SPETEX               32793
#define ID_BUTTON_ANIM_UP               32794
#define ID_BTN_AVA_LOADMOD              32794
#define ID_BUTTON_ANIM_DOWN             32795
#define ID_BUTTON_ANIM_REMOVE           32796
#define ID_BTN_PTL_SAVE                 32796
#define ID_BUTTON_APPLY_BONE            32797
#define ID_MNU_MODELVIEW                32797
#define ID_BUTTON_SHOW_BONE             32798
#define ID_32799                        32799
#define ID_32801                        32801
#define ID_MNU_RESVIEW                  32801
#define ID_BTN_MON_SAVESINGLE           32803
#define ID_BTN_AVA_APPAVA               32803
#define ID_32804                        32804
#define ID_BTN_MO_NEW_EVENT             32807
#define ID_32808                        32808
#define ID_32809                        32809
#define ID_BTN_RESETVIEW                32810
#define ID_32810                        32810
#define ID_EDIT_MODADDR                 32811
#define ID_32811                        32811
#define ID_LST_CHANGESPD                32812
#define ID_LST_CHANGECLR                32813
#define ID_COPY_LAYER                   32814
#define ID_CUT_LAYER                    32815
#define ID_PASTE_LAYER                  32816
#define ID_SEL_ALLKEYS                  32817
#define ID_BUTTON_UPDATE_ANCHOR         32819
#define ID_NEWPOST_32820                32820
#define ID_MENU_NEWPOST                 32821
#define ID_BUTTON32823                  32823
#define ID_BTN_ITM_DELETE               32824
#define ID_MNU_SPD1                     32825
#define ID_NEWPOST_32825                32825
#define ID_MNU_SPD2                     32826
#define ID_MNU_SPD3                     32827
#define ID_MNU_SPD4                     32828
#define ID_MNU_SPD5                     32829
#define ID_MNU_SPD6                     32830
#define ID_MNU_SPD7                     32831
#define ID_MNU_SPD8                     32832
#define ID_MNU_SPD9                     32833
#define ID_BTN_OPEN                     32834
#define ID_TEST_CMD                     32837
#define ID_MENU_NEWPOST_CAMERASHAKE     32838
#define ID_MENU_NEWPOST_FROZEN          32839
#define ID_MENU_NEWPOST_TRANSPARENT     32840
#define ID_BTN_LT_SAVE                  32844
#define ID_BTN_PTL_NEWFRAME             32845
#define ID_BTN_PTL_DELETEFRAME          32847
#define ID_BTN_PTL_APPLY                32853
#define ID_BTN_PTL_REMOVE               32860
#define ID_BTN_PTL_VISIBLE              32863
#define ID_MNU_UNLIMITEDFRAME           32868
#define ID_MNU_HIGHFRAME                32869
#define ID_MNU_MIDFRAME                 32870
#define ID_MNU_LOWFRAME                 32871
#define ID_LST_FRAMELIMIT               32872
#define ID_BTN_EDT_NEWEFFECT            32874
#define ID_BTN_EDT_LOADEFFECT           32875
#define ID_MNU_INSERT_NORPAR            32880
#define ID_MNU_INSERT_LIGHT             32882
#define ID_BTN_LT_APPLY                 32883
#define ID_BTN_LT_VISIBLE               32885
#define ID_BTN_LT_REMOVE                32886
#define ID_BTN_ITM_OVERWRITE            32887
#define ID_BTN_BLB_VISIBLE              32888
#define ID_BTN_BLB_APPLY                32889
#define ID_BTN_BLB_SAVE                 32890
#define ID_BTN_BLB_REMOVE               32891
#define ID_MNU_INSERT_BILLBOARD         32893
#define ID_SAVENPC                      32895
#define ID_BTN_AVA_ENABLEAVA            32896
#define ID_MNU_AVAVIEW                  32898
#define ID_BTN_AVA_SAVEASNPC            32899
#define ID_BTN_AVA_LOADNPC              32900
#define ID_MNU_EDITEFFECT               32902
#define ID_BTN_RIB_NEWFRAME             32903
#define ID_BTN_RIB_DELFRAME             32904
#define ID_BTN_RIB_UP                   32905
#define ID_BTN_RIB_DOWN                 32906
#define ID_BTN_RIB_VISIBLE              32907
#define ID_BTN_RIB_APPLY                32908
#define ID_BTN_RIB_SAVE                 32909
#define ID_BTN_RIB_DELETE               32910
#define ID_MNU_INSERT_RIBBON            32913
#define ID_BTN_BEA_VISIBLE              32914
#define ID_BTN_BEA_APPLY                32915
#define ID_BTN_BEA_SAVE                 32916
#define ID_BTN_BEA_DELETE               32917
#define ID_MNU_INSERT_BEAM              32920
#define ID_MNU_ITEMVIEW                 32922
#define ID_BTN_ITM_NEWITEM              32923
#define ID_BTN_ITM_DELITEM              32926
#define ID_BTN_ITM_EDITITEM             32927
#define ID_BTN_ITM_ITEMTYPE             32928
#define ID_BTN_ITM_ITEMPOS              32929
#define ID_BTN_ITM_QUALITY              32930
#define ID_BTN_ITMS_TEXT                32931
#define ID_BTN_ITMS_SEARCH              32933
#define ID_BTN_SETBACKLIGHT             32942
#define ID_OPENNPC                      32944
#define ID_BTN_UNDO                     32945
#define ID_BTN_REDO                     32946
#define ID_ACC_UNDO                     32947
#define ID_ACC_REDO                     32948
#define ID_BTN_PTL_CLICK                32951
#define ID_BTN_BLB_CLICK                32953
#define ID_MNU_SAVE_SM                  32955
#define ID_MNU_OPEN_SM                  32957
#define ID_BTN_LOADBGMESH               32958
#define ID_BTN_LT_CLICK                 32959
#define ID_BTN_PTL_LOCKAPPLY            32960
#define ID_BTN_BLB_LOCKAPPLY            32961
#define ID_BTN_LT_LOCKAPPLY             32962
#define ID_BTN_RIB_LOCKAPPLY            32963
#define ID_BTN_MO_NEWMOTION             32964
#define ID_BTN_MO_DELMOTION             32965
#define ID_BTN_MO_ADDEFFECT             32966
#define ID_BTN_MO_DELEFFECT             32967
#define ID_BTN_MO_PLAYMOTION            32968
#define ID_BTN_MO_COPY                  32971
#define ID_BTN_SHOWGROUND               32976
#define ID_BTN_ITM_ADDITEM              32985
#define ID_BTN_SKL_PLAY                 32986
#define ID_BTN_SKL_SHOWCOORD            32987
#define ID_BTN_SKL_SELFTARGET           32988
#define ID_BTN_SKL_ENABLETARGET         32989
#define ID_BTN_SKL_STOP                 32990
#define ID_BTN_INC_COORD                32991
#define ID_BTN_DEC_COORD                32992
#define ID_BTN_SKL_SAVE                 32995
#define ID_BTN_SKL_LOADSKL              32996
#define ID_BTN_SND_VISIBLE              33002
#define ID_BTN_SND_CLICK                33003
#define ID_BTN_SND_APPLY                33004
#define ID_BTN_SND_LOCKAPP              33005
#define ID_BTN_SND_SAVE                 33006
#define ID_BTN_SND_REMOVE               33007
#define ID_MNU_INSERT_SOUND             33009
#define ID_BTN_MON_SAVEMON              33010
#define ID_BTN_MON_LOADMON              33011
#define ID_BTN_DCL_NEWFRAME             33013
#define ID_BTN_DCL_DELFRAME             33014
#define ID_BTN_DCL_UP                   33015
#define ID_BTN_DCL_DOWN                 33016
#define ID_BTN_DCL_VISIBLE              33017
#define ID_BTN_DCL_SELECT               33018
#define ID_BTN_DCL_APPLY                33019
#define ID_BTN_DCL_LOCKAPP              33020
#define ID_BTN_DCL_SAVE                 33021
#define ID_BTN_DCL_REMOVE               33022
#define ID_BTN_SHOWBOUNDING             33025
#define ID_BTN_EDT_APPLYALL             33028
#define ID_BTN_PTL_DEL_REPLACEOBJ       33029
#define ID_BTN_SKL_SKILLTYPE            33030
#define ID_BTN_COODPOS                  33033
#define ID_BTN_COODROT                  33034
#define ID_BTN_CHANGEREF                33037
#define ID_BTN_PTL_NEW_CLD              33038
#define ID_BTN_PTL_DEL_CLD              33039
#define ID_BTN_COODSCALE                33045
#define ID_MNU_SRTPROP                  33048
#define ID_BTN_MO_MERGE                 33049
#define ID_BTN_MO_APART                 33050
#define ID_BTN_ITM_CLEAREQUIP           33052
#define ID_MNU_SET_INTEGRATE            33056
#define ID_MNU_SET_INDEPENDENT          33057
#define ID_BTN_GEO_NEWFRAME             33058
#define ID_BTN_GEO_DELFRAME             33059
#define ID_BTN_GEO_DOWN                 33061
#define ID_BTN_GEO_VISIBLE              33062
#define ID_BTN_GEO_APPLY                33063
#define ID_BTN_GEO_LOCKAPPLY            33064
#define ID_BTN_GEO_DELETE               33066
#define ID_BTN_GEO_SAVE                 33067
#define ID_BTN_GEO_UP                   33068
#define ID_MNU_INSERT_DECAL             33070
#define ID_MNU_INSERT_GEOM              33071
#define ID_MNU_RESVIEW2                 33076
#define ID_MNU_RESVIEW3                 33077
#define ID_MNU_RESVIEW4                 33078
#define ID_MNU_COPY                     33082
#define ID_MNU_PASTE                    33083
#define ID_MNU_DELETE                   33084
#define ID_BTN_MO_STOPMOTION            33089
#define ID_BTN_AABB                     33090
#define ID_BTN_EDT_REFRESHLIST          33091
#define ID_BTN_MO_NEWMOTIONFROMBONE     33094
#define ID_BRS_BTN_OPENEXPLORER         33095
#define ID_BTN_MO_RULER_IN              33096
#define ID_BTN_MO_RULER_OUT             33097
#define ID_MB_BTN_NEW_COMMON_MO         33098
#define ID_MOTIONBROWSER_EDIT           33103
#define ID_MOTIONBROWSER_DELETE         33104
#define ID_MB_BTN_NEW_PRIVATE_MO        33105
#define ID_BTN_MON_SAVETOLIB            33106
#define ID_MOTIONBROWSER_COPYTOPRIVATE  33108
#define ID_MB_BTN_IMPORT_COMMON_TASK    33109
#define ID_MB_BTN_IMPORT_PRIVATE_TASK   33111
#define ID_FOLDER_RENAME                33115
#define ID_FOLDER_DELETE                33116
#define ID_FOLDER_CREATE_SUB            33117
#define ID_BTN_MO_NEW_PATTICLE          33118
#define ID_BTN_MO_NEW_LIGHT             33120
#define ID_BTN_MO_NEW_RIBBON            33121
#define ID_BTN_MO_NEW_SOUND             33123
#define ID_BTN_MO_NEW_DECAL             33124
#define ID_BTN_MO_NEW_BILLBOARD         33126
#define ID_BTN_MO_NEW_BEAM              33127
#define ID_BTN_MO_NEW_GEOM              33128
#define ID_BTN_MO_NEW_VIRTUAL           33129
#define ID_BRS_BTN_ICON                 33130
#define ID_BRS_BTN_LIST                 33131
#define ID_BTN_PLANT_PRODUCT            33133
#define ID_BTN_BLB_NEWFRAME             33134
#define ID_BTN_BLB_DELFRAME             33135
#define ID_BTN_MO_MERGEMOTION           33138
#define ID_BTN_RIB_CLICK                33140
#define ID_BTN_MON_SHOWPATH             33141
#define ID_BTN_VIR_CLICK                33142
#define ID_BTN_VIR_APPLY                33143
#define ID_BTN_VIR_LOCKAPP              33144
#define ID_BTN_VIR_REMOVE               33145
#define ID_MNU_INSERT_VIRTUAL           33147
#define ID_BTN_MO_LOOPPLAY              33151
#define ID_BACKGROUND_STREET            33154
#define ID_BACKGROUND_OTHER             33155
#define ID_BACKGROUND_NONE              33157
#define ID_BTN_DISTORT                  33158
#define ID_BTN_MON_SAVEOBJASMON         33159
#define ID_BTN_MON_SAVESINGLEEFFECT     33160
#define ID_MB_EXPLORE                   33166
#define ID_BRS_BTN_CHARACTOR            33170
#define ID_BRS_BTN_PUBEFF               33172
#define ID_BTN_TOPVIEW                  33189
#define ID_BTN_FONTVIEW                 33191
#define ID_BTN_ORTHO                    33192
#define ID_BTN_PROJ                     33193
#define ID_BTN_LEFTVIEW                 33194
#define ID_BTN_MON_SAVESHOWMOD          33199
#define ID_MB_LOADSHOWMOD               33202
#define ID_BTN_GLOW                     33203
#define ID_BRS_BTN_MODELRES             40013
#define ID_BRS_BTN_CHUNKDATA            40022
#define ID_BTN_SKILLTEMPLATE            40034
#define ID_BTN_ST_PLAY                  40035
#define ID_BTN_ST_STOP                  40036
#define ID_BTN_ST_SAVE                  40037
#define ID_BTN_ST_OPEN                  40038
#define ID_BTN_Edit_MODEL               40041
#define ID_BTN_FORTYFIVEVIEW            40043
#define ID_BTN_ST_HITACTOR              40045
#define ID_BTN_ST_BEHITACTOR            40046
#define ID_BTN_ST_MONSTERAI             40048
#define ID_BTN_HIDEACTOR                40052
#define ID_BTN_ST_DELETE                40053
#define ID_BTN_ADD_AS_TEMP_PARAMS       40055
#define ID_BTN_DEL_AS_TEMP_PARAMS       40056
#define ID_SAVE_SKILL                   40059
#define ID_SAVE_AS_SKILL                40060
#define ID_ADD_MONSTER                  40063
#define ID_CLEAR_MONSTER                40064
#define ID_MONSTER_AI_MOVE              40069
#define ID_MONSTER_AI_ATTACK            40070
#define ID_MONSTER_AI_STAND             40071
#define UNIT_INDEX_NONE                 -11
#define UNIT_INDEX_ALL                  -10

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32828
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
