/*
**      MCDEF.H
**      Macro define file.
**      Copyright(C) 2001, Jack.
**
**      Jim, 2002.12.17.
**
**
*/
#ifndef _MCDEF_H_
#define _MCDEF_H_

//                                                                  
// user use command ----------------------                          
//                                                                  
#define CMD_DIALOG                              0x0030   
#define CMD_TALK                                0x0031   
#define CMD_ADD_TALK                            0x0032   
#define CMD_OPTION                              0x0033   
#define CMD_NEXT                                0x0034   
#define CMD_OPEN_STASH                          0x0035   
#define CMD_GET_PLAYER_BASE_ATT                 0x0036   
#define CMD_ENTER_PWORLD                        0x0037   
#define CMD_GET_PWORLD_INFO                     0x0038   
#define CMD_GET_ITEM_NUM_INPAK                  0x0039   
#define CMD_DEC_ITEM_NUM_INPAK                  0x003a   
#define CMD_ADD_EXP                             0x003b   
#define CMD_NEW_MON                             0x003c   
#define CMD_GET_MON_NUM                         0x003d   
#define CMD_TRANSMIT                            0x003e   
#define CMD_MSG_INFO                            0x003f   
#define CMD_GET_PWORLD_VAR                      0x0040   
#define CMD_SET_PWORLD_VAR                      0x0041   
#define CMD_MAP_MSG_INFO                        0x0042   
#define CMD_SVR_MSG_INFO                        0x0043   
#define CMD_DEL_MON                             0x0044   
#define CMD_MON_SKILL                           0x0045   
#define CMD_ADD_MONEY                           0x0046   
#define CMD_IS_CAPTAIN                          0x0047   
#define CMD_TEAM_TRANS                          0x0048   
#define CMD_GET_RAN_POS                         0x0049   
#define CMD_NEW_TMP_ITEM                        0x004a   
#define CMD_GET_PLAYER_ID                       0x004b   
#define CMD_GET_TEAM_PLAYER_ID                  0x004c   
#define CMD_ADD_SYS_MSG_START                   0x004d   
#define CMD_ADD_SYS_MSG                         0x004e   
#define CMD_ADD_SYS_MSG_POS                     0x004f   
#define CMD_SET_SYS_MSG_MODE                    0x0050   
#define CMD_OPEN_NPC_SHOP                       0x0051   
#define CMD_RESET_PWORLD                        0x0052   
#define CMD_NEW_NPC                             0x0053   
#define CMD_DEL_NPC                             0x0054   
#define CMD_GET_NPC_NUM                         0x0055   
#define CMD_PWORLD_OVER                         0x0056   
#define CMD_GET_TASK_VAR                        0x0057   
#define CMD_SET_TASK_VAR                        0x0058   
#define CMD_TASK_ADD_OPTION                     0x0059   
#define CMD_TASK_DO_OPTION                      0x005a   
#define CMD_TASKCYCLE_DO_OPTION                 0x005b   
#define CMD_TASK_FINI                           0x005c   
#define CMD_TASK_STAT                           0x005d   
#define CMD_EFFECT                              0x005e   
#define CMD_AUTOFLY                             0x005f   
#define CMD_GET_TRIG_TASK                       0x0060   
#define CMD_OPEN_UI                             0x0061   
#define CMD_GET_SKILL_INFO                      0x0062   
#define CMD_GET_DIATHESIS_INFO                  0x0063   
#define CMD_ADD_ITEM_NUM_INPAK                  0x0064   
#define CMD_ADD_ITEM_BAT_INPAK                  0x0065   
#define CMD_GET_NOW_TIME                        0x0066   
#define CMD_GET_POINT_DIST                      0x0067   
#define CMD_GET_PLAYER_MAPINFO                  0x0068   
#define CMD_GET_MAP_RANDPOINT                   0x0069   
#define CMD_OUT_PWORLD_BY_SINGLE                0x006a   
#define CMD_OUT_PWORLD_BY_TEAM                  0x006b   
#define CMD_GET_TIME_SEC                        0x006c   
#define CMD_GET_TMP_NUM                         0x006d   
#define CMD_GET_ROLE_VAR                        0x006e   
#define CMD_SET_ROLE_VAR                        0x006f   
#define CMD_GET_MON_VAR                         0x0070   
#define CMD_SET_MON_VAR                         0x0071   
#define CMD_OPEN_PWORLD_UI                      0x0072   
#define CMD_GET_MON_INFO                        0x0073   
#define CMD_SET_MON_BUFF                        0x0074   
#define CMD_GET_ITEM_OBJ_INFO                   0x0075   
#define CMD_GET_PET_INFO                        0x0076   
#define CMD_TRANSMIT_CAMERA                     0x0077   
#define CMD_COMPEL_CLOSE_PWORLD                 0x0078   
#define CMD_CALL_MON                            0x0079   
#define CMD_ADD_PET_FIGHT                       0x007a   
#define CMD_IS_IN_PWORLD                        0x007b   
#define CMD_NEW_MON_BY_DIR                      0x007c   
#define CMD_ADD_XP                              0x007d   
#define CMD_GET_MAP_NPC_ID                      0x007e   
#define CMD_EFFECT_ID                           0x007f   
#define CMD_ENTER_CLAN_CITY                     0x0080   
#define CMD_DYNAMIC_OPTION_LIST                 0x0081   
#define CMD_DYNAMIC_DO_TASK_OPTION              0x0082   
#define CMD_CLAN_PAY                            0x0083   
#define CMD_GET_TARGET_INFO                     0x0084   
#define CMD_TARGET_ADD_STATUS                   0x0085   
#define CMD_HAS_STATUS                          0x0086   
#define CMD_CLEAN_TARGET                        0x0087   
#define CMD_TARGET_RELATION                     0x0088   
#define CMD_TASKCYCLE_ADD_OPTION                0x0089   
#define CMD_SET_SVR_STATUS                      0x008a   
#define CMD_SET_EVENT_VAR                       0x008b   
#define CMD_GET_EVENT_VAR                       0x008c   
#define CMD_SET_EVENT_BULLETIN                  0x008d   
#define CMD_SET_EVENT_PWORLD                    0x008e   
#define CMD_RANGE_ADD_EXP                       0x008f   
#define CMD_RANGE_ADD_STATUS                    0x0090   
#define CMD_GET_EVENT_STAT                      0x0091   
#define CMD_NEW_LIFE_MON                        0x0092   
#define CMD_GET_PWORLD_ROLE_NUM                 0x0093   
#define CMD_ADD_TMP_ITEM                        0x0094   
#define CMD_ADD_TMP_FAIRY                       0x0095   
#define CMD_GET_AUTO_FLY_INFO                   0x0096   
#define CMD_GET_ITEM_ONEDAY_INFO                0x0097   
#define CMD_ITEM_ADD_ONEDAY                     0x0098   
#define CMD_GET_MAP_MON_ID                      0x0099   
#define CMD_USE_TREASURE_PIC                    0x009a   
#define CMD_TASK_SHARE_TEST                     0x009b   
#define CMD_TEAM_TASK_SHARE                     0x009c   
#define CMD_MON_TASK_AREA_CHECK                 0x009d   
#define CMD_MON_CHG_MAP                         0x009e   
#define CMD_MON_CALL_ENEMY_MON                  0x009f   
#define CMD_SET_MON_TASK_STAT                   0x00a0   
#define CMD_TEAM_MSG_INFO                       0x00a1   
#define CMD_ID_PLAYER_BASE_ATT                  0x00a2   
#define CMD_NEW_CONVOY_MON                      0x00a3   
#define CMD_GROUP_ADD_ONEDAY                    0x00a4   
#define CMD_GET_GROUP_ONEDAY_INFO               0x00a5   
#define CMD_NEW_MAP_MON                         0x00a6   
#define CMD_TEAM_PWORLD_INFO                    0x00a7   
#define CMD_ENTER_PWORLD_NUM_TEST               0x00a8   
#define CMD_GET_MON_PATROL_ID                   0x00a9   
#define CMD_GET_MAP_MON_NUM                     0x00aa   
#define CMD_GET_ITEM_USE_DUR                    0x00ab   
#define CMD_ADD_ITEM_ON_MAP                     0x00ac   
#define CMD_IS_MY_CONVOY_MON                    0x00ad   
#define CMD_GET_ID_PLAYER_STATUS_INFO           0x00ae   
#define CMD_GET_ID_MON_STATUS_INFO              0x00af   
#define CMD_RESET_ALL_GENIUS                    0x00b0   
#define CMD_GET_MON_FIGHT_TIME_COUNT            0x00b1   
#define CMD_MODIFY_MON_PRESS                    0x00b2   
#define CMD_MON_ATK_SPECIFIC_TARGET             0x00b3   
#define CMD_MON_SPEECH                          0x00b4   
#define CMD_NEW_MON_AND_FORCED_MOVE             0x00b5   
#define CMD_GET_MON_CURRENT_PATROL_POS          0x00b6   
#define CMD_SET_MON_CURRENT_PATROL_TIME         0x00b7   
#define CMD_ADD_PWORLD_RESOURCE                 0x00b8   
#define CMD_GET_DISTANCE_BETWEEN_2MON           0x00b9   
#define CMD_GET_MON_NUM_BY_DEFID                0x00ba   
#define CMD_MON_GET_PLAYER_NUM_BY_CAREER        0x00bb   
#define CMD_MON_GET_FRIEND_NUM                  0x00bc   
#define CMD_GET_MON_HP_PERCENT                  0x00bd   
#define CMD_MON_PRESS_GET_FRIEND_PLAYER_NUM     0x00be   
#define CMD_DELETE_MON_BY_DEFID                 0x00bf   
#define CMD_ID_PLAYER_GROUP_ADD_ONEDAY          0x00c0   
#define CMD_ID_PLAYER_GROUP_ONEDAY_INFO         0x00c1   
#define CMD_SET_EVENT_PWORLD_QUEUE              0x00c2   
#define CMD_APPLY_PWORLD_QUEUE                  0x00c3   
#define CMD_DESTROY_MON                         0x00c4   
#define CMD_MON_OWNER_MSG_INFO                  0x00c5   
#define CMD_GET_ID_PLAYER_INFO                  0x00c6   
#define CMD_ADD_FINI_TASK                       0x00c7   
#define CMD_DEL_ID_MON                          0x00c8   
#define CMD_GET_PACK_SPACE                      0x00c9   
#define CMD_NEW_LIFE_NPC                        0x00ca   
#define CMD_IS_SAME_WEEK                        0x00cb   
#define CMD_NEW_OWNER_TMP_ITEM                  0x00cc   
#define CMD_ADD_PLAYER_HP                       0x00cd   
#define CMD_ADD_PLAYER_MP                       0x00ce   
#define CMD_ADD_FIGHT_PET_HP                    0x00cf   
#define CMD_PLAYER_TRANSMIT_CAMERA              0x00d0   
#define CMD_CALL_MON_BY_PATROL                  0x00d1   
#define CMD_PWORLD_REVIVE_PLAYER                0x00d2   
#define CMD_GET_ROLE_TMP_ITEM                   0x00d3   
#define CMD_DEL_ROLE_TMP_ITEM                   0x00d4   
#define CMD_DEL_ROLE_UNUSED_TMP_ITEM            0x00d5   
#define CMD_TASK_RUN                            0x00d6   
#define CMD_DEC_MONEY                           0x00d7   
#define CMD_NPC_DIE                             0x00d8   
#define CMD_HAS_ID_PLAYER_DESIGNATION           0x00d9   
#define CMD_TASK_FAIL                           0x00da   
#define CMD_PLAYER_RIDE_ON                      0x00db   
#define CMD_RIDE_DROP                           0x00dc   
#define CMD_RANGE_SET                           0x00dd   
#define CMD_RUN_TASK_PROGRESS                   0x00de   
#define CMD_BCT_GET_CURR_LAYER                  0x00df   
#define CMD_BCT_PASS                            0x00e0   
#define CMD_BCT_SHEST_AWARD                     0x00e1   
#define CMD_BCT_UI                              0x00e2   
#define CMD_BCT_CALL_MON                        0x00e3   
#define CMD_PLAYER_COLLECT_BREAK                0x00e4   
#define CMD_SET_PWORLD_MAP_CURR                 0x00e5   
#define CMD_CAREER_LEVEL_UP                     0x00e6   
#define CMD_EXP_LIMIT                           0x00e7   
#define CMD_SET_MON_CURR                        0x00e8   
#define CMD_MON_SET_HP                          0x00e9   
#define CMD_GET_MON_PATROLIDX                   0x00ea   
#define CMD_SET_PLAYER_CURR                     0x00eb   
#define CMD_EXIT_CLAN                           0x00ec   
#define CMD_USE_CANGBAOTU_PIC                   0x00ed   
#define CMD_COMMIT_TASK                         0x00ee   
#define CMD_DEC_MONEY_TEST                      0x00ef   
#define CMD_GET_ID_MON_INFO                     0x00f0   
#define CMD_NEW_LINKED_MON_SLOT                 0x00f1   
#define CMD_LINK_MON                            0x00f2   
#define CMD_GET_PLAYER_SECONDARY_SKILL          0x00f3   
#define CMD_ENTER_LOGIC_AREA                    0x00f4   
#define CMD_LEAVE_LOGIC_AREA                    0x00f5   
#define CMD_SET_MON_GROUP                       0x00f6   
#define CMD_ROLE_ITEM_NUM                       0x00f7   
#define CMD_HAS_FAIRY                           0x00f8   
#define CMD_PWORLD_LINKED_MON_INFO              0x00f9   
#define CMD_PLAYER_NEW_LINKED_MON               0x00fa   
#define CMD_NEW_NPC_PRIVATE                     0x00fb   
#define CMD_PWORLD_AGAIN                        0x00fc   
#define CMD_PROCEVT_PLAYER_NUM                  0x00fd   
#define CMD_CALL_MON_TEAM_ALL                   0x00fe   
#define CMD_NPC_COMMIT_OPT                      0x00ff   
#define CMD_GET_COMMIT_ITEM_INFO                0x0100   
#define CMD_DEC_ITEM_NUM_BYIDX                  0x0101   
#define CMD_GET_ROLE_TMP_MACHINE                0x0102   
#define CMD_SET_DIALOG_STYLE                    0x0103   
#define CMD_CIRCLE_NEW_MON                      0x0104   
#define CMD_APPLY_TMP_ITEM                      0x0105   
#define CMD_GIVEBACK_CLAN_MACHINE               0x0106   
#define CMD_LAYDOWN_CLAN_ORE                    0x0107   
#define CMD_GET_PLAYER_PKVAL_TYPE               0x0108   
#define CMD_SET_MAP_VAL                         0x0109   
#define CMD_GET_MAP_VAL                         0x010a   
#define CMD_PLAYER_CLOSE_DIALOG                 0x010b   
#define CMD_SYS_MAIL                            0x010c   
#define CMD_MAIL_TEXT                           0x010d   
#define CMD_ADD_DESIGNATION                     0x010e   
#define CMD_CHOOSE                              0x010f   
#define CMD_ADD_ONLINE_ATTR                     0x0110   
#define CMD_LEARN_SEC_SKILL                     0x0111   
#define CMD_IS_MON_FIGHTING                     0x0112   
#define CMD_SET_BATTLE_WIN                      0x0113   
#define CMD_SET_MON_CAMP_IDX                    0x0114   
#define CMD_SET_REVIVE_POS_CAMP                 0x0115   
#define CMD_NEW_DYN_MON                         0x0116   
#define CMD_GET_ATTACKER_CAMP                   0x0117   
#define CMD_PLAYER_JUMP                         0x0118   
#define CMD_NEW_CAMP_NPC                        0x0119   
#define CMD_MON_GET_PLAYER_NUM_IN_RECT          0x011a   
#define CMD_PLAYER_MOVIE_START                  0x011b   
#define CMD_GET_CLAN_BUILDING_LV                0x011c   
#define CMD_GET_PLAYER_TASK_SPRITE_FLAG         0x011d   
#define CMD_SET_PLAYER_TASK_SPRITE_FLAG         0x011e   
#define CMD_GET_BATTLE_LEVEL_LIMIT              0x011f   
#define CMD_GOTO_CLAN_CITY                      0x0120   
#define CMD_GET_MON_GROUP                       0x0121   
#define CMD_GET_RAND_PWORLD_PLAYER_ID           0x0122   
#define CMD_NEW_MON_MACHINE                     0x0123   
#define CMD_MON_FORCED_MOVE                     0x0124   
#define CMD_PLAYER_SET_HIDE_TASK                0x0125   
#define CMD_MON_FORCED_MOVE_POS                 0x0126   
#define CMD_GET_RADIAN                          0x0127   
#define CMD_GET_ANGLE_POS                       0x0128   
#define CMD_IS_PLAYER_OWNER_MON                 0x0129   
#define CMD_COMMIT_CLAN_ITEM                    0x012a   
#define CMD_PLAYER_CALL_BUB                     0x012b   
#define CMD_GET_PLAYER_MAP_LINE                 0x012c   
#define CMD_SET_PLAYER_MAP_LINE                 0x012d   
#define CMD_MON_PUSH_PRESS                      0x012e   
#define CMD_MON_OWNER_DIS                       0x012f   
#define CMD_GET_CLAN_USED_TECH_POINT            0x0130   
#define CMD_PLAYER_TRIGGER_MON_PRESS            0x0131   
#define CMD_DESTROY_MON_BY_DEFID                0x0132   
#define CMD_IS_CAN_BIANSHEN                     0x0133   
#define CMD_MON_RANGE_ADD_PLAYER_HP             0x0134   
#define CMD_SET_DESIG                           0x0135   
#define CMD_MON_GET_KILLER_ID                   0x0136   
#define CMD_GET_WORLD_FIRST_START_TIME          0x0137   
#define CMD_ADD_BIND_ITEM_NUM_INPAK             0x0138   
#define CMD_ADD_BIND_ITEM_BAT_INPAK             0x0139   
#define CMD_BATTLE_MIN_CAMP_PLAYER_NUM          0x013a   
#define CMD_GET_CMP_FAIRYID                     0x013b   
#define CMD_NEW_MON_MACHINE_BY_DIR              0x013c   
#define CMD_ID_PLAYER_MOTION                    0x013d   
#define CMD_SET_EVENT_BATTLE                    0x013e   
#define CMD_PLAYER_NEED_NEW_NAME                0x013f   
#define CMD_CLAN_NEED_NEW_NAME                  0x0140   
#define CMD_MAP_NEW_NPC                         0x0141   
#define CMD_GET_PWORLD_FIRST_PLAYER_ID          0x0142   
#define CMD_GET_MAP_INST                        0x0143   
#define CMD_IS_ONE_MON_FIGHTING_BY_DEFID        0x0144   
#define CMD_SET_SCRIPT_INT_RET                  0x0145   
#define CMD_GET_PLAYER_NUM_RANGE                0x0146   
#define CMD_OPEN_PWORLD_AWARD_UI                0x0147   
#define CMD_PKG_IS_UNLOCK                       0x0148   
#define CMD_PLAYER_IS_GRABTIME                  0x0149   
#define CMD_GET_MUL_COMMIT_ITEM_INFO            0x014a   
#define CMD_SET_DLG_COMMIT_NUM                  0x014b   
#define CMD_WORLD_ORE_NEW_CHECK                 0x014c   
#define CMD_COMMIT_MUL_CLAN_ITEM                0x014d   
#define CMD_MON_OWNER_TASK_CHECK                0x014e   
#define CMD_AUTO_MOVE                           0x014f   
#define CMD_PLAYER_CLAN_POS_INFO                0x0150   
#define CMD_GET_ROLE_RIDE_ON_MACHINE            0x0151   
#define CMD_MAP_TRANS                           0x0152   
#define CMD_ENTER_WORLD_CITY_CHECK              0x0153   
#define CMD_IS_WORLD_CITY_OWNER                 0x0154   
#define CMD_SET_WORLD_CITY_OPEN_TIME            0x0155   
#define CMD_GET_WORLD_CITY_ENABLE_TIME          0x0156   
#define CMD_SET_WORLD_CITY_ENABLE_TIME          0x0157   
#define CMD_GET_WORLD_CITY_OPEN_TIME            0x0158   
#define CMD_SET_WORLD_BOSS_FIRST_KILL_TIME      0x0159   
#define CMD_GET_WORLD_BOSS_FIRST_KILL_TIME      0x015a   
#define CMD_WORLD_CITY_AREA                     0x015b   
#define CMD_ADD_WORLD_CITY_BUILD_SERIAL         0x015c   
#define CMD_GET_CRAYFISH_NUM_ONEDAY             0x015d   
#define CMD_COMMIT_CRAYFISH_NUM_ONCE            0x015e   
#define CMD_GET_WORLD_CITY_KEEP_NUM             0x015f   
#define CMD_GET_PLAYER_JOIN_CLAN_TIME           0x0160   
#define CMD_SET_WORLD_CITY_EFFIGY               0x0161   
#define CMD_USE_ITEM_SHOW_MAP                   0x0162   
#define CMD_HAS_MASTER_WORLD_CITY               0x0163   
#define CMD_CHOOSE_WITH_TIMER                   0x0164   
#define CMD_GET_MAP_RAND_MON_POS                0x0165   
#define CMD_TARGET_ADD_STATUS_DYN               0x0166   
#define CMD_SET_LUCKY_OPEN                      0x0167   
#define CMD_IS_PLAYER_LUCKY_ATTENDEE            0x0168   
#define CMD_IS_LUCKY_CLOSED                     0x0169   
#define CMD_CLAN_EVERYDAY_PWORLD_STAT_GET       0x016a   
#define CMD_CLAN_EVERYDAY_PWORLD_CREATE         0x016b   
#define CMD_CLAN_EVERYDAY_PWORLD_ENTER          0x016c   
#define CMD_CLAN_EVERYDAY_PWORLD_VAL_CHG        0x016d   
#define CMD_FOR_EACH_MAP_OBJ                    0x016e   
#define CMD_IS_IN_MY_CLAN_CITY                  0x016f   
#define CMD_NEW_CLAN_MON                        0x0170   
#define CMD_GET_CLAN_TECH_LEVEL                 0x0171   
#define CMD_IS_IN_SIEGE_CITY                    0x0172   
#define CMD_GET_CLAN_STABLE                     0x0173   
#define CMD_ADD_CLAN_STABLE                     0x0174   
#define CMD_PLAYER_ADD_STATUS_BY_CLANMON        0x0175   
#define CMD_GET_PLAYER_DAILY_FLAG               0x0176   
#define CMD_SET_PLAYER_DAILY_FLAG               0x0177   
#define CMD_CLAN_MSG_INFO                       0x0178   
#define CMD_DYN_ACTIVE_STATUS_SET               0x0179   
#define CMD_CLAN_TOUCH_ADD                      0x017a   
#define CMD_DYN_ACTIVE_STATUS_GET               0x017b   
#define CMD_UNREAL_WATCH_BOSS_INFO              0x017c   
#define CMD_UNREAL_TEAM_INFO                    0x017d   
#define CMD_GOTO_UNREAL_CAPTAIN_NEAR            0x017e   
#define CMD_GET_UNREAL_LAYER                    0x017f   
#define CMD_SAVE_UNREAL_LAYER                   0x0180   
#define CMD_UNREAL_ENTER                        0x0181   
#define CMD_IS_LAST_UNREAL_BOSS_MAP             0x0182   
#define CMD_UNREAL_ENTER_BOSS_CHECK             0x0183   
#define CMD_DARKMATTER_DROPMONEY                0x0184   
#define CMD_DARKMATTER_FLEE_DROPMONEY           0x0185   
#define CMD_GET_MON_MAPDEFID                    0x0186   
#define CMD_TEAM_TRANS_INSAMEMAPINST            0x0187   
#define CMD_ADD_PLAYER_HP2                      0x0188   
#define CMD_MON_DROP_BOOTYGROUP                 0x0189   
#define CMD_GET_MON_LEVEL                       0x018a   
#define CMD_MAP_DEL_TMP_ITEM                    0x018b   
#define CMD_PLAYER_CLOSE_DIALOG1                0x018c   
#define CMD_NEW_LIFE_DYN_MON                    0x018d   
#define CMD_COUNT_DOWN                          0x018e   
#define CMD_FOLLOW_CANCEL                       0x018f   
#define CMD_MON_DIE_ADD_TEAM_BUFF               0x0190   
#define CMD_IS_CLAN_CAN_SPY                     0x0191   
#define CMD_IS_CLAN_ANTI_SPY_TASK_OPEN          0x0192   
#define CMD_CLAN_SPY_CLOSE                      0x0193   
#define CMD_CLAN_ANTI_SPY_TASK_OPEN             0x0194   
#define CMD_CLAN_SPY_TASK_OPEN                  0x0195   
#define CMD_IS_IN_CLAN_SPY_TARGET_MAP           0x0196   
#define CMD_IS_CLAN_SPY_TASK_OPEN               0x0197   
#define CMD_IS_CLAN_SPY_OPEN                    0x0198   
#define CMD_CLAN_SPY_OPEN                       0x0199   
#define CMD_NEW_DART_CAR                        0x019a   
#define CMD_RESET_DART_CAR                      0x019b   
#define CMD_RESET_DART_CAR_CHECK                0x019c   
#define CMD_GET_DART_CAR_TYPE                   0x019d   
#define CMD_SET_CALL_VAR                        0x019e   
#define CMD_IN_DART_CAR                         0x019f   
#define CMD_IS_PLAYER_IN_JAIL                   0x01a0   
#define CMD_GET_SPY_TARGET_CLAN_ID              0x01a1   
#define CMD_ADD_TARGET_CLAN_STABLE              0x01a2   
#define CMD_SET_PLAYER_SPY_TASK_STAGE_DONE      0x01a3   
#define CMD_GET_PWORLD_TIMER_MON_ALIVE          0x01a4   
#define CMD_GET_PWORLD_TIMER                    0x01a5   
#define CMD_GET_PWORLD_WAVE_MON_ALIVE           0x01a6   
#define CMD_GET_PWORLD_WAVE_MON_COUNT_DOWN      0x01a7   
#define CMD_PWORLD_PUSH_TIMER_MON               0x01a8   
#define CMD_GET_PWORLD_TIMER_MON_COUNT_DOWN     0x01a9   
#define CMD_SET_PWORLD_WAVE_MON_COUNT_DOWN      0x01aa   
#define CMD_GET_ROLE_RIDE_ON_MACHINE_MEM_ID     0x01ab   
#define CMD_SET_PWORLD_TIMER                    0x01ac   
#define CMD_GET_PWORLD_TIMER_MON_ROUND          0x01ad   
#define CMD_GET_PWORLD_WAVE_MON_ROUND           0x01ae   
#define CMD_SET_PWORLD_TIMER_MON_COUNT_DOWN     0x01af   
#define CMD_PWORLD_PUSH_WAVE_MON                0x01b0   
#define CMD_CLAN_MACHINE_PWORLD_CREATE          0x01b1   
#define CMD_IS_PWORLD_OVER                      0x01b2   
#define CMD_GAY_INVITE                          0x01b3   
#define CMD_IS_GAY_GONG                         0x01b4   
#define CMD_ENTER_CLAN_MACHINE_PWORLD           0x01b5   
#define CMD_IS_CLAN_MACHINE_PWORLD_OPEN         0x01b6   
#define CMD_GET_MACHINE_PWORLD_STATUS_INFO      0x01b7   
#define CMD_SET_MONEY_TYPE                      0x01b8   
#define CMD_GET_MACHINE_PWORLD_STATUS           0x01b9   
#define CMD_NEW_MAP_LIFE_NPC                    0x01ba   
#define CMD_COW_PWORLD_CREATE                   0x01bb   
#define CMD_COW_PWORLD_STAUS                    0x01bc   
#define CMD_COW_FINAL_RANGE                     0x01bd   
#define CMD_COW_FINAL_END                       0x01be   
#define CMD_COW_PWORLD_ENTER                    0x01bf   
#define CMD_OPEN_COW_FINAL_RANGE_UI             0x01c0   
#define CMD_COW_FINAL_BEGIN                     0x01c1   
#define CMD_GET_VAILD_ITEM_NUM_INPAK            0x01c2   
#define CMD_DEC_VAILD_ITEM_NUM_INPAK            0x01c3   
#define CMD_STRONG_SALE_INFO                    0x01c4   
#define CMD_STRONG_PLAYER_AWARD                 0x01c5   
#define CMD_STRONG_PWORLD_ADD_RES               0x01c6   
#define CMD_ADD_ID_PLAYER_CONTRI_TEST           0x01c7   
#define CMD_ADD_ID_CLAN_MONEY                   0x01c8   
#define CMD_ADD_ID_CLAN_MONEY_TEST              0x01c9   
#define CMD_GET_ID_PLAYER_CONTRI                0x01ca   
#define CMD_RECORD_ID_PLAYER_CLAN_DONATE        0x01cb   
#define CMD_ADD_ID_PLAYER_CONTRI                0x01cc   
#define CMD_STRONG_ENTER                        0x01cd   
#define CMD_STRONG_IS_OPEN                      0x01ce   
#define CMD_STRONG_CANCEL                       0x01cf   
#define CMD_STRONG_IS_MINE                      0x01d0   
#define CMD_GET_TOP_BY_LEVEL                    0x01d1   
#define CMD_ADD_BIND_ITEM_NUM_INPAK_MONEY       0x01d2   
#define CMD_ADD_ITEM_NUM_INPAK_MONEY            0x01d3   
#define CMD_GET_YUEYU_NUM                       0x01d4   
#define CMD_ADD_YUEYU_NUM                       0x01d5   
#define CMD_SET_EVENT_VAR_BY_ID                 0x01d6   
#define CMD_GET_EVENT_VAR_BY_ID                 0x01d7   
#define CMD_RIDE_OFF                            0x01d8   
#define CMD_RONGLU_TASK_GET                     0x01d9   
#define CMD_RONGLU_CALL_MON                     0x01da   
#define CMD_RONGLU_IS_FULL                      0x01db   
#define CMD_RONGLU_CALL_COLLECT                 0x01dc   
#define CMD_RONGLU_GET_TASKID                   0x01dd   
#define CMD_RONGLU_GET_ITEMID                   0x01de   
#define CMD_GET_RONGLU_TASK_NUM                 0x01df   
#define CMD_GOLD_RATE_GET_MONEY                 0x01e0   
#define CMD_GOLD_RATE_DEC_MONEY                 0x01e1   
#define CMD_GOLD_RATE_GET_DAYNUM                0x01e2   
#define CMD_GET_RAND_LUKY_MAP                   0x01e3   
#define CMD_SET_CLAN_EVERYPWORLD_BOSS_DIE       0x01e4   
#define CMD_ADD_ITEM_NUM_INPAK_NOLIMIT          0x01e5   
#define CMD_ADD_ITEM_BAT_INPAK_NOLIMIT          0x01e6   
#define CMD_ADD_BIND_ITEM_NUM_INPAK_NOLIMIT     0x01e7   
#define CMD_ADD_BIND_ITEM_BAT_INPAK_NOLIMIT     0x01e8   
#define CMD_IS_SAME_DAY                         0x01e9   
#define CMD_GET_CLAN_CREATE_TIME                0x01ea   
#define CMD_SET_WEATHER                         0x01eb   
#define CMD_PLAYER_WORSHIP_EFFIGY_TEST          0x01ec   
#define CMD_PLAYER_WORSHIP_EFFIGY               0x01ed   
#define CMD_PLAYER_EFFIGY_AWARD                 0x01ee   
#define CMD_CITY_EFFIGY_INFO                    0x01ef   
#define CMD_IS_UIN_FLAG_SET                     0x01f0   
#define CMD_CLAN_JOIN_TIME_NO_SAMEDAY           0x01f1   
#define CMD_GET_CUR_MAX_LEVEL                   0x01f2   
#define CMD_PLAYER_BUSY_UI                      0x01f3   
#define CMD_IS_FIRST_STRONG                     0x01f4   
#define CMD_HAS_STRONG_GLORY                    0x01f5   
#define CMD_IS_STRONG_MEMBER                    0x01f6   
#define CMD_PLAYER_CHG_MACHINE                  0x01f7   
#define CMD_PLAYER_MACHINE_ADD_HP               0x01f8   
#define CMD_PLAYER_CAMP_ADD_EXP                 0x01f9   
#define CMD_GET_MON_NUM_RADIUS                  0x01fa   
#define CMD_STRONG_OPEN_GLORY                   0x01fb   
#define CMD_GET_STAR_INFO                       0x01fc   
#define CMD_RONGLU_CHG_GOLD                     0x01fd   
#define CMD_CLAN_BABY_FEED                      0x01fe   
#define CMD_GET_CLAN_BABY_FEED                  0x01ff   
#define CMD_GET_CLAN_BABY_STAT                  0x0200   
#define CMD_CLAN_BABY_CALL                      0x0201   
#define CMD_PLAYER_CLAN_BABY_AWARD              0x0202   
#define CMD_CLAN_BABY_DIE                       0x0203   
#define CMD_TASKCYCLE_STAT                      0x0204   
#define CMD_GET_DAYONLINE                       0x0205   
#define CMD_ARM_IS_FASHION                      0x0206   
#define CMD_PLAYER_TRANSMIT_RAND                0x0207   
#define CMD_RESUME_DART_CAR                     0x0208   
#define CMD_GET_PRE_DART_CAR                    0x0209   
#define CMD_SET_PWORLD_TIMER_W_COUNT_DOWN       0x020a   
#define CMD_GET_NPC_DEFID                       0x020b   
#define CMD_NEW_MAP_LIFE_NPC_EX                 0x020c   
#define CMD_EXCHG_ITEM                          0x020d   
#define CMD_EXCHG_ITEM_GET                      0x020e   
#define CMD_PWORLD_PLAYER_EXP                   0x020f   
#define CMD_COMMIT_ARM_WASH_ADDATTR             0x0210   
#define CMD_SCHOOL_INVITE_UI                    0x0211   
#define CMD_SCHOOL_FINI                         0x0212   
#define CMD_GET_REG_INFO                        0x0213   
#define CMD_COMMIT_XUKONG_ENERGY                0x0214   
#define CMD_BUY_HETONG                          0x0215   
#define CMD_PWORLD_BOX_START                    0x0216   
#define CMD_PWORLD_BOX_AWARD                    0x0217   
#define CMD_HANG_HAI_BEGIN                      0x0218   
#define CMD_HANG_HAI_END                        0x0219   
#define CMD_HANG_HAI_RANGE                      0x021a   
#define CMD_OPEN_HANG_HAI_RANGE_UI              0x021b   
#define CMD_OPEN_YANG_HAI_BANG_UI               0x021c   
#define CMD_YANG_HAI_BANG_START_CHECK           0x021d   
#define CMD_YANG_HAI_BANG_START                 0x021e   
#define CMD_GET_PINGJIU_VAR                     0x021f   
#define CMD_SET_PINGJIU_VAR                     0x0220   
#define CMD_OPEN_STORE_UI                       0x0221   
#define CMD_CLAN_OPEN_DART                      0x0222   
#define CMD_PINJIU_SCREEN_VAGUE                 0x0223   
#define CMD_ITEM_IS_CHENGHAO                    0x0224   
#define CMD_ITEM_IS_FUMO                        0x0225   
#define CMD_ITEM_IS_ZHUZHAO                     0x0226   
#define CMD_ITEM_IS_LIANJIN                     0x0227   
#define CMD_OPEN_SHOP_BY_ID                     0x0228   
#define CMD_PLAYER_CLAN_DEVELOP_RANKING         0x0229   
#define CMD_CLAN_IS_OPEN_DART                   0x022a   
#define CMD_USE_ITEM_IS_BIND                    0x022b   
#define CMD_CAMP_MON_MAP_SHOW_ACTION            0x022c   
#define CMD_SET_CAMP_MON_MAP_SHOW               0x022d   
#define CMD_SET_PAOSHANG_INFO                   0x022e   
#define CMD_GET_PAOSHANG_INFO                   0x022f   
#define CMD_OPEN_PAOSHANG_UI                    0x0230   
#define CMD_GET_POSITEM_INFO                    0x0231   
#define CMD_SET_POSITEM_INFO                    0x0232   
#define CMD_POSITEM_DIR                         0x0233   
#define CMD_PAOSHANG_DUIHUAN_REFRESH            0x0234   
#define CMD_DAQIANGDAO_FENSHU                   0x0235   
#define CMD_SET_MON_OWNER                       0x0236   
#define CMD_SET_DLG_OLD_STAT                    0x0237   
#define CMD_GOLD_RATE_DAYNUM_ADD                0x0238   
#define CMD_STRONG_ACTIVE_LEVEL                 0x0239   
#define CMD_RANGE_CLAN_FANRONG                  0x023a   
#define CMD_ENTER_CLAN_MACHINE_PWORLD_UNITE     0x023b   
#define CMD_IS_EXIST_MACHINE_PWORLD_UINTE       0x023c   
#define CMD_PLOY_GC_GET_AWARD                   0x023d   
#define CMD_PLOY_GC_SET_AWARDE                  0x023e   
#define CMD_PLOY_GC_UI_INFO                     0x023f   
#define CMD_PLOY_GC_PLAYER_CLEAR                0x0240   
#define CMD_DEL_NPC_BY_MAPID                    0x0241   
#define CMD_GET_EVENT_EXIST_TIME                0x0242   
#define CMD_NEW_MAP_LIFE_NPC1                   0x0243   
#define CMD_PLAYER_IS_JIYANG                    0x0244   
#define CMD_PLAYER_PET_UNLOCK                   0x0245   
#define CMD_DIANFENG_FIRST_INFO                 0x0246   
#define CMD_DIANFENG_AWARD                      0x0247   
#define CMD_DIANFENG_FRONT_CHAMPION             0x0248   
#define CMD_DIANFENG_SET_EFFIGY                 0x0249   
#define CMD_GET_GLOBAL_VAR                      0x024a   
#define CMD_SET_GLOBAL_VAR                      0x024b   
#define CMD_APPLY_PWORLD                        0x024c
#define CMD_CANCEL_SPAN_QUEUE                   0x024d
#define CMD_CANCEL_SPAN_QUEUE_CHECK            0x024e
#define CMD_DIANFENG_IF_OPEN                    0x0250   
#define CMD_DIANFENG_ADD_STATUS                 0x0251   
#define CMD_DIANFENG_CLEAR_BAOMING_INFO         0x0252   
#define CMD_DIANFENG_AWARD_CHECK                0x0253   
#define CMD_GET_MZT_LAYER                       0x0254   
#define CMD_UNREAL_GET_EXP_LAYER                0x0255   
#define CMD_SUB_PLAYER_HP                       0x0256   
#define CMD_REMOVE_RELATION_UI                  0x0257   
#define CMD_BROADCAST_WEDDING_TIP               0x0258   
#define CMD_OATH_UI                             0x0259   
#define CMD_GET_WORLD_CAMP_IN_SPAN_MAP          0x025a   
#define CMD_GET_WEAR_POS1                       0x025b   
#define CMD_GET_BAOXIANG_TOUCH_LIMIT            0x025c   
#define CMD_CAREER_ALTER_CHECK                  0x025d   
#define CMD_CAREER_ALTER                        0x025e   
#define CMD_BEGIN_HONEYMOON_TRAVEL_CHECK        0x0260   
#define CMD_BEGIN_WEDDING_CELEBRATION_CHECK     0x0261   
#define CMD_BEGIN_WEDDING_CHECK                 0x0262   
#define CMD_GET_WEDDING_STH                     0x0263   
#define CMD_SET_WEDDING_STH                     0x0264   
#define CMD_ORDER_WEDDING_MEAL_CHECK            0x0265   
#define CMD_NEW_MACHINE_PATROL_SPOUSE           0x0266   
#define CMD_MACHINE_SPOUSE_CHG_MAP              0x0267   
#define CMD_MACHINE_CLEAR                       0x0268   
#define CMD_CHECK_WORLD_LIMIT                   0x0269   
#define CMD_SYS_MAIL_BIND                       0x026a   
#define CMD_BOSS_BAOXIANG_TOUCH_SET             0x026b   
#define CMD_BOSS_BAOXIANG_TOUCH_GET             0x026c   
#define CMD_BCT_BAOXIANG_IF_OPEN                0x026d   
#define CMD_WORD_PWD_UI                         0x026e   
#define CMD_WORD_PWD_RAND_NEW_MON               0x026f   
#define CMD_GET_WORD_PWD_MON_INFO               0x0270   
#define CMD_SPAN_MAP_TRANSMIT                   0x0271   
#define CMD_HOME_ADD_EXP                        0x0272   
#define CMD_HOME_KAIKEN                         0x0273   
#define CMD_HOME_UI                             0x0274   
#define CMD_HOME_ENTER                          0x0275   
#define CMD_HOME_INFO                           0x0276


#endif//_MCDEF_H_
