/* soapStub.h
   Generated by gSOAP 2.8.9 from ws9c.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns1	"http://tempuri.org/"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20809
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (7)
/* xsd:boolean */
enum xsd__boolean {xsd__boolean__false_ = 0, xsd__boolean__true_ = 1};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE__ns1__UseCode
#define SOAP_TYPE__ns1__UseCode (8)
/* ns1:UseCode */
struct _ns1__UseCode
{
	char *pass9;	/* optional element of type xsd:string */
	char *game;	/* optional element of type xsd:string */
	char *areaId;	/* optional element of type xsd:string */
	char *serverId;	/* optional element of type xsd:string */
	int roleId;	/* required element of type xsd:int */
	char *roleName;	/* optional element of type xsd:string */
	char *code;	/* optional element of type xsd:string */
	char *ip;	/* optional element of type xsd:string */
	enum xsd__boolean isSendByClient;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__ns1__UseCodeResponse
#define SOAP_TYPE__ns1__UseCodeResponse (9)
/* ns1:UseCodeResponse */
struct _ns1__UseCodeResponse
{
	char *UseCodeResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__GetCodeDetail
#define SOAP_TYPE__ns1__GetCodeDetail (10)
/* ns1:GetCodeDetail */
struct _ns1__GetCodeDetail
{
	char *game;	/* optional element of type xsd:string */
	char *areaId;	/* optional element of type xsd:string */
	char *serverId;	/* optional element of type xsd:string */
	char *code;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__ns1__GetCodeDetailResponse
#define SOAP_TYPE__ns1__GetCodeDetailResponse (11)
/* ns1:GetCodeDetailResponse */
struct _ns1__GetCodeDetailResponse
{
	char *GetCodeDetailResult;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE___ns1__UseCode
#define SOAP_TYPE___ns1__UseCode (15)
/* Operation wrapper: */
struct __ns1__UseCode
{
	struct _ns1__UseCode *ns1__UseCode;	/* optional element of type ns1:UseCode */
};
#endif

#ifndef SOAP_TYPE___ns1__GetCodeDetail
#define SOAP_TYPE___ns1__GetCodeDetail (19)
/* Operation wrapper: */
struct __ns1__GetCodeDetail
{
	struct _ns1__GetCodeDetail *ns1__GetCodeDetail;	/* optional element of type ns1:GetCodeDetail */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (20)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (21)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (23)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (26)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (27)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __ns1__UseCode(struct soap*, struct _ns1__UseCode *ns1__UseCode, struct _ns1__UseCodeResponse *ns1__UseCodeResponse);

SOAP_FMAC5 int SOAP_FMAC6 __ns1__GetCodeDetail(struct soap*, struct _ns1__GetCodeDetail *ns1__GetCodeDetail, struct _ns1__GetCodeDetailResponse *ns1__GetCodeDetailResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__UseCode(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetCodeDetail(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__UseCode(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__UseCode *ns1__UseCode, struct _ns1__UseCodeResponse *ns1__UseCodeResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetCodeDetail(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__GetCodeDetail *ns1__GetCodeDetail, struct _ns1__GetCodeDetailResponse *ns1__GetCodeDetailResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
