/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef ZONE_CTRL_CONF_DESC_H
#define ZONE_CTRL_CONF_DESC_H


#ifndef TDR_METALIB_ZONE_CTRL_VERSION 
#define TDR_METALIB_ZONE_CTRL_VERSION 	10 /*version of metalib*/
#endif

#ifndef TDR_METALIB_ZONE_CTRL_HASH 
#define TDR_METALIB_ZONE_CTRL_HASH 	"c82da3146493ee36c0557764c6893414" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */



#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagzone_ctrlconf;
typedef struct tagzone_ctrlconf                    	ZONE_CTRLCONF;
typedef struct tagzone_ctrlconf                    	*LPZONE_CTRLCONF;

struct tagzone_ctrlrun_cumulate;
typedef struct tagzone_ctrlrun_cumulate            	ZONE_CTRLRUN_CUMULATE;
typedef struct tagzone_ctrlrun_cumulate            	*LPZONE_CTRLRUN_CUMULATE;

struct tagzone_ctrlrun_status;
typedef struct tagzone_ctrlrun_status              	ZONE_CTRLRUN_STATUS;
typedef struct tagzone_ctrlrun_status              	*LPZONE_CTRLRUN_STATUS;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagzone_ctrlconf
{
    int iRes;                           
};

struct tagzone_ctrlrun_cumulate
{
    int iRes;                           
};

struct tagzone_ctrlrun_status
{
    int iRes;                           
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* ZONE_CTRL_CONF_DESC_H */
