/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef TLOGDATADEF_H
#define TLOGDATADEF_H

/*   
 User Define Macros.   */


/* TLOG_DATA*/
enum tagTLOG_DATA 
{
    TLOG_DATA_TXT = 0, 
    TLOG_DATA_BIN = 1, 
};

#endif /* TLOGDATADEF_H */
