#!/bin/sh


if [ $# != 1 ];then
        echo "parameter errer!"
        echo "./resdb_grant.sh resdb_X_X_X | [dbname]"
        exit -1;
fi

dbname=$1

#wutao
mysql -userver -ptulin#1234 << EOF
	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
	ON $dbname.* 
	TO 'wutao'@'192.168.0.48' 
	IDENTIFIED BY 'wanyouyl';
EOF

#Xulisha

mysql -userver -ptulin#1234 << EOF
	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
	ON $dbname.*
	TO 'xuls'@'192.168.0.109'
	IDENTIFIED BY 'wanyouyl';
EOF

#cp
mysql -userver -ptulin#1234 << EOF
	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
	ON $dbname.ActionStatus 
	TO 'cp'@'192.168.0.41'
	IDENTIFIED BY 'wanyouyl';
	
	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
	ON $dbname.BootyGroupDef 
	TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.DiathesisDef 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.MapMonster 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.MonBootyDef 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.MonsterDef 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.MonsterStateSkillDef 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.NpcDisplayInfo 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.NpcInfoDef 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.OverlayTypeRelationDef 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.PetDef 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.PetLevelDef 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.PetStrengthenDef 
        TO 'cp'@'192.168.0.41';
	
	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.PetTraitDef 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.ProcEvent 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.SceneAreaDef 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.SkillDef 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.StatusDef 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.StatusOverlayDef 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.TaskDef 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.TaskRecycleDef 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.WorldBootyDef 
        TO 'cp'@'192.168.0.41';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.WorldMapSearchDef 
        TO 'cp'@'192.168.0.41';

EOF

#lw
mysql -userver -ptulin#1234 << EOF

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.ActiveHelper 
        TO 'lw'@'192.168.0.54'
	IDENTIFIED BY 'wanyouyl';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.BattleDef 
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.BCTDef 
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.CangBaoTuDef 
        TO 'lw'@'192.168.0.54';
	
	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.FairyDef 
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.FittingsDef 
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.GameEventDef
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.LevelAttrDef
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.LevelUP 
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.MapDef 
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.MapMonster 
        TO 'lw'@'192.168.0.54';
	
	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.MonDynAttrDef 
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.MonsterDef 
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.MonsterSpeechDef 
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.MonsterStateSkillDef 
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.Patroldef  
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.PetDef 
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.PetLevelDef
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.PetStrengthenDef 
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.PetTraitDef 
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.ProcEvent 
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.PworldDef 
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.SkillDef
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.StatusDef 
        TO 'lw'@'192.168.0.54';

	GRANT SELECT,INSERT,UPDATE,DELETE,INDEX,ALTER,CREATE,CREATE VIEW, SHOW VIEW
        ON $dbname.StatusOverlayDef
        TO 'lw'@'192.168.0.54';

EOF

