/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef ACCOUNT_CS_SVR_CONF_DESC_H
#define ACCOUNT_CS_SVR_CONF_DESC_H


#ifndef TDR_METALIB_ACCOUNT_CS_SVR_VERSION 
#define TDR_METALIB_ACCOUNT_CS_SVR_VERSION 	10 /*version of metalib*/
#endif

#ifndef TDR_METALIB_ACCOUNT_CS_SVR_HASH 
#define TDR_METALIB_ACCOUNT_CS_SVR_HASH 	"e14d93ae08fe3b0332589d42315ab25f" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */

#define ACCOUNT_CS_SVR_PATH_LEN                  	1024


#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagaccount_cs_svrconf;
typedef struct tagaccount_cs_svrconf               	ACCOUNT_CS_SVRCONF;
typedef struct tagaccount_cs_svrconf               	*LPACCOUNT_CS_SVRCONF;

struct tagaccount_cs_svrrun_status;
typedef struct tagaccount_cs_svrrun_status         	ACCOUNT_CS_SVRRUN_STATUS;
typedef struct tagaccount_cs_svrrun_status         	*LPACCOUNT_CS_SVRRUN_STATUS;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagaccount_cs_svrconf
{
    int ResShmKey;                      
    char DBMetaDir[ACCOUNT_CS_SVR_PATH_LEN];
};

struct tagaccount_cs_svrrun_status
{
    int Res;                            
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* ACCOUNT_CS_SVR_CONF_DESC_H */
