/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef REGION_GATE_CONF_DESC_H
#define REGION_GATE_CONF_DESC_H


#ifndef TDR_METALIB_REGION_GATE_VERSION 
#define TDR_METALIB_REGION_GATE_VERSION 	10 /*version of metalib*/
#endif

#ifndef TDR_METALIB_REGION_GATE_HASH 
#define TDR_METALIB_REGION_GATE_HASH 	"4589da9ec5e97bd57ebcdd6cda4254fa" /*hash of metalib*/
#endif
/*   
 User Define Macros.   */



#ifdef __cplusplus
extern "C" {
#endif

/*   Define c types.   */


#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
#if defined(WIN32) &&  _MSC_VER < 1300
typedef __int64 tdr_longlong;
typedef unsigned __int64 tdr_ulonglong;
#else
typedef long long tdr_longlong;
typedef unsigned long long tdr_ulonglong;
#endif  /*defined(WIN32) &&  _MSC_VER < 1300*/
typedef unsigned short tdr_wchar_t;  /**<Wchar基本数据类型*/
typedef unsigned int tdr_date_t;	/**<data基本数据类型*/
typedef unsigned int tdr_time_t;	/**<time基本数据类型*/
typedef tdr_ulonglong tdr_datetime_t;  /**<datetime基本数据类型*/
typedef unsigned long int tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/



/*   Structs/unions prototype.   */

struct tagregion_gateconf;
typedef struct tagregion_gateconf                  	REGION_GATECONF;
typedef struct tagregion_gateconf                  	*LPREGION_GATECONF;

struct tagregion_gaterun_status;
typedef struct tagregion_gaterun_status            	REGION_GATERUN_STATUS;
typedef struct tagregion_gaterun_status            	*LPREGION_GATERUN_STATUS;



/*   Define structs/unions.   */

#pragma pack(1)

struct tagregion_gateconf
{
    int ObjShmKey;                      
};

struct tagregion_gaterun_status
{
    int Res;                            
};


#pragma pack()

#ifdef __cplusplus
}
#endif


#endif /* REGION_GATE_CONF_DESC_H */
