<?xml version="1.0" encoding="gb2312"?>
<definitions 
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:s="http://www.w3.org/2001/XMLSchema" 
	xmlns:s0="http://www.ljy0.com/AccService/" 
	xmlns:s1="http://www.ljy0.com/CsService/"
	xmlns:whttp="http://www.w3.org/ns/wsdl/http" 
	xmlns:wsoap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" 
	targetNamespace="http://www.ljy0.com/AccAndCsService/">
	
	<wsdl:import namespace="xmlns:s0" location="acc_service.wsdl"/>
	<wsdl:import namespace="xmlns:s1" location="cs_service.wsdl"/>
	
</definitions>
