CREATE TABLE IF NOT EXISTS Bill (
 Uin INT  NOT NULL  ,
 Sequence BIGINT UNSIGNED    ,
 ServerID BIGINT UNSIGNED    ,
 Amount BIGINT UNSIGNED    ,
 Points BIGINT UNSIGNED    ,
 Bonus BIGINT UNSIGNED    ,
 FreezePoint BIGINT UNSIGNED    ,
 FreezeLastTime INT    ,
 CashTotalPoints BIGINT UNSIGNED    ,
 UsedTotalPoints BIGINT UNSIGNED    ,
PRIMARY KEY(Uin))  ENGINE=InnoDB DEFAULT CHARSET=latin1;
create index Bill_Idx_0 on Bill ( Uin);
CREATE TABLE IF NOT EXISTS AddBillRecord (
 Sequence VARCHAR(32)  NOT NULL  ,
 BillType INT UNSIGNED    ,
 Uin INT    ,
 ServerID INT UNSIGNED    ,
 Amount BIGINT UNSIGNED    ,
 Points BIGINT UNSIGNED    ,
 Bonus BIGINT UNSIGNED    ,
 PropsID BIGINT UNSIGNED    ,
 PropsName VARCHAR(200)    ,
 LogTime DATETIME    ,
PRIMARY KEY(Sequence, BillType))  ENGINE=InnoDB DEFAULT CHARSET=latin1;
create index AddBillRecord_Idx_0 on AddBillRecord ( Uin);
CREATE TABLE IF NOT EXISTS DecBillRecord (
 seqID BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT ,
 Uin INT    ,
 RoleID BIGINT UNSIGNED    ,
 RoleLevel INT    ,
 WorldID INT    ,
 OperType TINYINT    ,
 GodPointNum BIGINT UNSIGNED    ,
 LogTime DATETIME    ,
 KEY(seqID),
PRIMARY KEY(seqID))  ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
create index DecBillRecord_Idx_0 on DecBillRecord ( Uin);
CREATE TABLE IF NOT EXISTS GodCoinConsumeRecord (
 seqID BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT ,
 Uin INT    ,
 RoleID BIGINT UNSIGNED    ,
 RoleLevel INT    ,
 WorldID INT    ,
 OperType INT    ,
 OperSubType INT    ,
 GodCoin BIGINT UNSIGNED    ,
 ShopID INT UNSIGNED    ,
 ShopNum INT UNSIGNED    ,
 OperDesc TEXT    ,
 LogTime DATETIME    ,
 KEY(seqID),
PRIMARY KEY(seqID))  ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
create index GodCoinConsumeRecord_Idx_0 on GodCoinConsumeRecord ( Uin);
CREATE TABLE IF NOT EXISTS PropsDef (
 GroupID INT UNSIGNED  NOT NULL  ,
 CashUp BIGINT UNSIGNED    ,
 BeginDate VARCHAR(9)    ,
 EndDate VARCHAR(9)    ,
 Name VARCHAR(32)    ,
 IconID INT    ,
 Title VARCHAR(64)    ,
 DesHead TEXT    ,
 DesTail TEXT    ,
 PropsGiftItem1_ItemID INT    ,
 PropsGiftItem1_ItemNum INT    ,
 PropsGiftItem2_ItemID INT    ,
 PropsGiftItem2_ItemNum INT    ,
 PropsGiftItem3_ItemID INT    ,
 PropsGiftItem3_ItemNum INT    ,
 PropsGiftItem4_ItemID INT    ,
 PropsGiftItem4_ItemNum INT    ,
 PropsGiftItem5_ItemID INT    ,
 PropsGiftItem5_ItemNum INT    ,
 PropsGiftItem6_ItemID INT    ,
 PropsGiftItem6_ItemNum INT    ,
 PropsGiftItem7_ItemID INT    ,
 PropsGiftItem7_ItemNum INT    ,
 PropsGiftItem8_ItemID INT    ,
 PropsGiftItem8_ItemNum INT    ,
PRIMARY KEY(GroupID, CashUp))  ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS PropsGift (
 Uin INT UNSIGNED  NOT NULL  ,
 GroupID INT UNSIGNED    ,
 CashNow BIGINT UNSIGNED    ,
 LastCashTime DATETIME    ,
 GiftGetNum INT    ,
 GiftGetInfo1_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo1_GetTime INT    ,
 GiftGetInfo2_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo2_GetTime INT    ,
 GiftGetInfo3_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo3_GetTime INT    ,
 GiftGetInfo4_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo4_GetTime INT    ,
 GiftGetInfo5_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo5_GetTime INT    ,
 GiftGetInfo6_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo6_GetTime INT    ,
 GiftGetInfo7_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo7_GetTime INT    ,
 GiftGetInfo8_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo8_GetTime INT    ,
 GiftGetInfo9_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo9_GetTime INT    ,
 GiftGetInfo10_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo10_GetTime INT    ,
 GiftGetInfo11_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo11_GetTime INT    ,
 GiftGetInfo12_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo12_GetTime INT    ,
 GiftGetInfo13_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo13_GetTime INT    ,
 GiftGetInfo14_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo14_GetTime INT    ,
 GiftGetInfo15_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo15_GetTime INT    ,
 GiftGetInfo16_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo16_GetTime INT    ,
 GiftGetInfo17_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo17_GetTime INT    ,
 GiftGetInfo18_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo18_GetTime INT    ,
 GiftGetInfo19_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo19_GetTime INT    ,
 GiftGetInfo20_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo20_GetTime INT    ,
 GiftGetInfo21_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo21_GetTime INT    ,
 GiftGetInfo22_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo22_GetTime INT    ,
 GiftGetInfo23_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo23_GetTime INT    ,
 GiftGetInfo24_CashUp BIGINT UNSIGNED    ,
 GiftGetInfo24_GetTime INT    ,
PRIMARY KEY(Uin, GroupID))  ENGINE=InnoDB DEFAULT CHARSET=latin1;
create index PropsGift_Idx_0 on PropsGift ( Uin);
CREATE TABLE IF NOT EXISTS AccGift (
 ID INT  NOT NULL AUTO_INCREMENT ,
 Uin INT UNSIGNED    ,
 RoleID BIGINT UNSIGNED    ,
 Type INT    ,
 Flag INT    DEFAULT '0',
 Name VARCHAR(32)    ,
 GiftDesc VARCHAR(128)    ,
 GiftItems1_ItemID INT    ,
 GiftItems1_ItemNum INT    ,
 GiftItems2_ItemID INT    ,
 GiftItems2_ItemNum INT    ,
 GiftItems3_ItemID INT    ,
 GiftItems3_ItemNum INT    ,
 GiftItems4_ItemID INT    ,
 GiftItems4_ItemNum INT    ,
 SetGiftTime DATETIME    ,
 GetGiftTime DATETIME    ,
 KEY(ID),
PRIMARY KEY(ID))  ENGINE=InnoDB DEFAULT CHARSET=latin1;
create index AccGift_Idx_0 on AccGift ( Uin);
create index AccGift_Idx_1 on AccGift ( RoleID);
CREATE TABLE IF NOT EXISTS CDKeyTypeDef (
 KeyType VARCHAR(5)  NOT NULL  ,
 EndTime DATETIME    ,
 LimitNum INT    ,
 Items1_ItemID INT    ,
 Items1_ItemNum INT    ,
 Items2_ItemID INT    ,
 Items2_ItemNum INT    ,
 Items3_ItemID INT    ,
 Items3_ItemNum INT    ,
 Items4_ItemID INT    ,
 Items4_ItemNum INT    ,
 SubType TINYINT    ,
 LvlLowLimit INT    ,
 LvlHighLimt INT    ,
PRIMARY KEY(KeyType))  ENGINE=InnoDB DEFAULT CHARSET=latin1;
CREATE TABLE IF NOT EXISTS CDKeyDef (
 CDKey VARCHAR(65)  NOT NULL  ,
 State INT    ,
 RoleID BIGINT UNSIGNED    ,
 SvrID INT    ,
PRIMARY KEY(CDKey))  ENGINE=InnoDB DEFAULT CHARSET=latin1;
create index CDKeyDef_Idx_0 on CDKeyDef ( RoleID);
CREATE TABLE IF NOT EXISTS CDKeyGet (
 CDKey VARCHAR(65)    ,
 RoleID BIGINT UNSIGNED    ,
 SvrID INT    )  ENGINE=InnoDB DEFAULT CHARSET=latin1;
create index CDKeyGet_Idx_0 on CDKeyGet ( RoleID);
